-- ==============================================================
-- Generated by Vitis HLS v2025.1.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity lenet_hls_fc_f6_Pipeline_F6_Output_Loop_p_ZL10f6_weights_13_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 8; 
             AddressWidth     : integer := 7; 
             AddressRange    : integer := 84
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of lenet_hls_fc_f6_Pipeline_F6_Output_Loop_p_ZL10f6_weights_13_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00001111", 1 => "11110001", 2 => "00100101", 3 => "01000111", 
    4 => "10101111", 5 => "00000001", 6 => "00001110", 7 => "11100111", 
    8 => "00010011", 9 => "11001110", 10 => "00000010", 11 => "10101011", 
    12 => "11011110", 13 => "00000101", 14 => "11110100", 15 => "11011011", 
    16 => "11011100", 17 => "10110011", 18 => "00110001", 19 => "11011001", 
    20 => "11101001", 21 => "11101100", 22 => "11101000", 23 => "11110000", 
    24 => "11111011", 25 => "00111000", 26 => "00101100", 27 => "00010100", 
    28 => "11001100", 29 => "00001100", 30 => "11001100", 31 => "11110101", 
    32 => "11010101", 33 => "11111000", 34 => "00001010", 35 => "11100100", 
    36 => "00000000", 37 => "11101101", 38 => "11110001", 39 => "00101000", 
    40 => "00001001", 41 => "11001111", 42 => "11110110", 43 => "00010100", 
    44 => "11001111", 45 => "11100101", 46 => "11011111", 47 => "00001110", 
    48 => "00000001", 49 => "10111011", 50 => "11111110", 51 => "11001111", 
    52 => "00000100", 53 => "00101001", 54 => "00011001", 55 => "11010011", 
    56 => "11010011", 57 => "00100000", 58 => "11010111", 59 => "00111101", 
    60 => "00111000", 61 => "00111001", 62 => "11101110", 63 => "00011011", 
    64 => "00100001", 65 => "00110010", 66 => "00011011", 67 => "00000111", 
    68 => "00100000", 69 => "11111110", 70 => "00011011", 71 => "00110100", 
    72 => "11100000", 73 => "11011001", 74 => "11011100", 75 => "00000001", 
    76 => "00000010", 77 => "00000000", 78 => "00001111", 79 => "11010000", 
    80 => "00011000", 81 => "11110001", 82 => "11011100", 83 => "00001111");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

