-- ==============================================================
-- Generated by Vitis HLS v2025.1.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity lenet_hls_fc_f6_Pipeline_F6_Output_Loop_p_ZL10f6_weights_53_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 8; 
             AddressWidth     : integer := 7; 
             AddressRange    : integer := 84
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of lenet_hls_fc_f6_Pipeline_F6_Output_Loop_p_ZL10f6_weights_53_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "11111011", 1 => "10100101", 2 => "00100110", 3 => "00101000", 
    4 => "11100101", 5 => "11100100", 6 => "11010111", 7 => "00001011", 
    8 => "11101111", 9 => "00000001", 10 => "11110011", 11 => "01110110", 
    12 => "00100000", 13 => "10111011", 14 => "00000111", 15 => "11101110", 
    16 => "10111101", 17 => "11110000", 18 => "00110111", 19 => "00111000", 
    20 => "11101111", 21 => "00001100", 22 => "00011100", 23 => "00100010", 
    24 => "00011011", 25 => "01011011", 26 => "11011110", 27 => "10111111", 
    28 => "00001111", 29 => "11101100", 30 => "11100001", 31 => "00110111", 
    32 => "00010111", 33 => "00000000", 34 => "00110011", 35 => "00000101", 
    36 => "00111111", 37 => "01111111", 38 => "11100001", 39 => "00010110", 
    40 => "00100000", 41 => "01101101", 42 => "10100110", 43 => "11111101", 
    44 => "01011001", 45 => "00100001", 46 => "01010010", 47 => "11001100", 
    48 => "11000010", 49 => "01010110", 50 => "11010000", 51 => "00000101", 
    52 => "00000011", 53 => "00100100", 54 => "11111000", 55 => "00010011", 
    56 => "00100100", 57 => "00100010", 58 => "11111110", 59 => "00000000", 
    60 => "01000011", 61 => "10100001", 62 => "01000101", 63 => "00000111", 
    64 => "00111110", 65 => "00110100", 66 => "11101101", 67 => "11001000", 
    68 => "11110101", 69 => "11010011", 70 => "11100001", 71 => "00110000", 
    72 => "01000100", 73 => "11110010", 74 => "00100011", 75 => "01001001", 
    76 => "01100110", 77 => "00000001", 78 => "11000010", 79 => "11110101", 
    80 => "01010111", 81 => "11011000", 82 => "00010011", 83 => "10111000");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

