-- ==============================================================
-- Generated by Vitis HLS v2025.1.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity lenet_hls_fc_f6_Pipeline_F6_Output_Loop_p_ZL10f6_weights_63_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 8; 
             AddressWidth     : integer := 7; 
             AddressRange    : integer := 84
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of lenet_hls_fc_f6_Pipeline_F6_Output_Loop_p_ZL10f6_weights_63_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "11100100", 1 => "11011101", 2 => "11000011", 3 => "00000001", 
    4 => "01000111", 5 => "00001010", 6 => "00111110", 7 => "00011110", 
    8 => "00100010", 9 => "11010110", 10 => "11000101", 11 => "01101110", 
    12 => "00111110", 13 => "11110000", 14 => "01010100", 15 => "11110110", 
    16 => "10111101", 17 => "01010000", 18 => "00011011", 19 => "11101110", 
    20 => "11011111", 21 => "00110001", 22 => "00010111", 23 => "00011110", 
    24 => "11100001", 25 => "00111111", 26 => "00011101", 27 => "11011101", 
    28 => "11111110", 29 => "00101100", 30 => "11110111", 31 => "00011011", 
    32 => "11100011", 33 => "11010100", 34 => "11000111", 35 => "00100100", 
    36 => "00011100", 37 => "00010110", 38 => "11110101", 39 => "01011101", 
    40 => "11011010", 41 => "01100110", 42 => "00010111", 43 => "00001001", 
    44 => "11110010", 45 => "11110101", 46 => "00000111", 47 => "01010001", 
    48 => "11010100", 49 => "00001001", 50 => "11010111", 51 => "11010000", 
    52 => "11001011", 53 => "11101010", 54 => "11000001", 55 => "10111100", 
    56 => "00101010", 57 => "11010111", 58 => "11100011", 59 => "11010101", 
    60 => "10011101", 61 => "11011110", 62 => "00100000", 63 => "11011010", 
    64 => "01010110", 65 => "11000000", 66 => "10110100", 67 => "10111010", 
    68 => "10011000", 69 => "11100000", 70 => "11001000", 71 => "00011101", 
    72 => "11010011", 73 => "11100001", 74 => "11111010", 75 => "01010101", 
    76 => "00001000", 77 => "00110100", 78 => "11010100", 79 => "00111010", 
    80 => "11011111", 81 => "11100010", 82 => "11011001", 83 => "00010001");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

