-- ==============================================================
-- Generated by Vitis HLS v2025.1.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity lenet_hls_fc_f6_Pipeline_F6_Output_Loop_p_ZL10f6_weights_3_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 8; 
             AddressWidth     : integer := 7; 
             AddressRange    : integer := 84
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of lenet_hls_fc_f6_Pipeline_F6_Output_Loop_p_ZL10f6_weights_3_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "11010110", 1 => "10101011", 2 => "11111100", 3 => "01011001", 
    4 => "10111100", 5 => "11101011", 6 => "11011001", 7 => "10111100", 
    8 => "00000010", 9 => "11110111", 10 => "11111100", 11 => "00010011", 
    12 => "11100001", 13 => "11101000", 14 => "11011010", 15 => "11110010", 
    16 => "00100011", 17 => "00110001", 18 => "00100001", 19 => "01010010", 
    20 => "00000101", 21 => "11010010", 22 => "10111100", 23 => "11100111", 
    24 => "11111101", 25 => "11010010", 26 => "00001010", 27 => "11011101", 
    28 => "01101011", 29 => "11000010", 30 => "00001010", 31 => "10110100", 
    32 => "11111101", 33 => "00111000", 34 => "00000010", 35 => "00001000", 
    36 => "00100001", 37 => "00111011", 38 => "11110100", 39 => "00001001", 
    40 => "11111101", 41 => "00110001", 42 => "10100000", 43 => "00110000", 
    44 => "00110111", 45 => "01010100", 46 => "01001010", 47 => "00100100", 
    48 => "11100110", 49 => "11010101", 50 => "10111111", 51 => "00101000", 
    52 => "01100101", 53 => "11110010", 54 => "00100100", 55 => "00100001", 
    56 => "01000001", 57 => "11010100", 58 => "00011111", 59 => "11101111", 
    60 => "11101010", 61 => "11010000", 62 => "11100000", 63 => "10101011", 
    64 => "00110100", 65 => "11110110", 66 => "00000100", 67 => "10111110", 
    68 => "00101010", 69 => "11110100", 70 => "11010000", 71 => "11110011", 
    72 => "00010110", 73 => "11000101", 74 => "01000000", 75 => "11110001", 
    76 => "01000010", 77 => "11001000", 78 => "00001100", 79 => "11111000", 
    80 => "11001110", 81 => "00001100", 82 => "11010110", 83 => "00100110");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

