-- ==============================================================
-- Generated by Vitis HLS v2025.1.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity lenet_hls_fc_f6_Pipeline_F6_Output_Loop_p_ZL10f6_weights_55_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 8; 
             AddressWidth     : integer := 7; 
             AddressRange    : integer := 84
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of lenet_hls_fc_f6_Pipeline_F6_Output_Loop_p_ZL10f6_weights_55_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "11000111", 1 => "00011011", 2 => "10011011", 3 => "00001110", 
    4 => "01011101", 5 => "11110100", 6 => "10000000", 7 => "11001000", 
    8 => "11111011", 9 => "11100111", 10 => "10111101", 11 => "10101110", 
    12 => "11111000", 13 => "01100011", 14 => "00101111", 15 => "11011011", 
    16 => "00101101", 17 => "11100001", 18 => "11100110", 19 => "11110100", 
    20 => "01000001", 21 => "00111100", 22 => "11001010", 23 => "01100100", 
    24 => "00011101", 25 => "00100010", 26 => "00000110", 27 => "11100101", 
    28 => "00100111", 29 => "00101110", 30 => "01010101", 31 => "11011110", 
    32 => "00100110", 33 => "00100000", 34 => "01000001", 35 => "11000010", 
    36 => "01111001", 37 => "10110001", 38 => "00100001", 39 => "01001110", 
    40 => "01011111", 41 => "01011011", 42 => "10111000", 43 => "01111111", 
    44 => "11001100", 45 => "01000101", 46 => "00111111", 47 => "11000111", 
    48 => "11100001", 49 => "11101001", 50 => "00100100", 51 => "00011000", 
    52 => "01011010", 53 => "00010001", 54 => "01111111", 55 => "00111101", 
    56 => "01011100", 57 => "00010111", 58 => "01111111", 59 => "11100001", 
    60 => "00100100", 61 => "11101010", 62 => "11000010", 63 => "00001110", 
    64 => "00010110", 65 => "00000000", 66 => "11001110", 67 => "00010001", 
    68 => "01000101", 69 => "11000000", 70 => "01111111", 71 => "11101101", 
    72 => "01001011", 73 => "11001110", 74 => "11110101", 75 => "01000001", 
    76 => "00001110", 77 => "00001011", 78 => "00011001", 79 => "11001011", 
    80 => "11111001", 81 => "11101110", 82 => "00000011", 83 => "01011010");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

