-- ==============================================================
-- Generated by Vitis HLS v2025.1.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity lenet_hls_fc_f6_Pipeline_F6_Output_Loop_p_ZL10f6_weights_34_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 8; 
             AddressWidth     : integer := 7; 
             AddressRange    : integer := 84
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of lenet_hls_fc_f6_Pipeline_F6_Output_Loop_p_ZL10f6_weights_34_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "11101111", 1 => "00111100", 2 => "00100101", 3 => "00000100", 
    4 => "00010111", 5 => "11011100", 6 => "11111010", 7 => "11111000", 
    8 => "11011011", 9 => "00000100", 10 => "11101101", 11 => "00010011", 
    12 => "00011010", 13 => "11001111", 14 => "00011110", 15 => "00011010", 
    16 => "01010001", 17 => "00101111", 18 => "00011101", 19 => "00000110", 
    20 => "00001011", 21 => "01011000", 22 => "11111001", 23 => "11110111", 
    24 => "00010011", 25 => "00111011", 26 => "00000100", 27 => "01001101", 
    28 => "11101010", 29 => "00001010", 30 => "00011001", 31 => "00001111", 
    32 => "11010000", 33 => "00101011", 34 => "00110000", 35 => "11101001", 
    36 => "00101100", 37 => "00100000", 38 => "11101110", 39 => "00001110", 
    40 => "11011111", 41 => "00001000", 42 => "11100011", 43 => "11000110", 
    44 => "00110011", 45 => "11101101", 46 => "11111001", 47 => "11011000", 
    48 => "00110100", 49 => "00011100", 50 => "11010001", 51 => "00101011", 
    52 => "10111100", 53 => "00010010", 54 => "11101110", 55 => "00001001", 
    56 => "11111001", 57 => "00111100", 58 => "00001101", 59 => "00010010", 
    60 => "00111001", 61 => "01000101", 62 => "10111111", 63 => "11010101", 
    64 => "00010110", 65 => "00000100", 66 => "00001100", 67 => "00000101", 
    68 => "00001111", 69 => "00101111", 70 => "00010010", 71 => "11100100", 
    72 => "00000010", 73 => "11111001", 74 => "00101101", 75 => "00010001", 
    76 => "11101010", 77 => "00010110", 78 => "00010011", 79 => "00001110", 
    80 => "11011110", 81 => "00000000", 82 => "00110001", 83 => "01001000");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

