-- ==============================================================
-- Generated by Vitis HLS v2025.1.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity lenet_hls_fc_f6_Pipeline_F6_Output_Loop_p_ZL10f6_weights_96_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 8; 
             AddressWidth     : integer := 7; 
             AddressRange    : integer := 84
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of lenet_hls_fc_f6_Pipeline_F6_Output_Loop_p_ZL10f6_weights_96_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00010010", 1 => "11101010", 2 => "00001110", 3 => "11010100", 
    4 => "00110111", 5 => "00010011", 6 => "00001011", 7 => "00111011", 
    8 => "00010100", 9 => "11111111", 10 => "00110110", 11 => "01001111", 
    12 => "00001011", 13 => "00010010", 14 => "00000100", 15 => "11110000", 
    16 => "00000100", 17 => "00011000", 18 => "11010111", 19 => "11110110", 
    20 => "11101010", 21 => "11100100", 22 => "00111111", 23 => "00011010", 
    24 => "00000010", 25 => "01000001", 26 => "11111001", 27 => "11111000", 
    28 => "00101100", 29 => "00101100", 30 => "00011010", 31 => "00011110", 
    32 => "00000100", 33 => "11110100", 34 => "11110111", 35 => "11100111", 
    36 => "11010111", 37 => "11100110", 38 => "00011111", 39 => "11101110", 
    40 => "00011110", 41 => "00110100", 42 => "01000101", 43 => "11111000", 
    44 => "01000001", 45 => "10110101", 46 => "11001101", 47 => "00101011", 
    48 => "11100110", 49 => "00010001", 50 => "11011100", 51 => "11010110", 
    52 => "10111001", 53 => "00011101", 54 => "00001101", 55 => "11011011", 
    56 => "00011110", 57 => "11000100", 58 => "11001110", 59 => "00100010", 
    60 => "11101111", 61 => "11110010", 62 => "00000110", 63 => "11100000", 
    64 => "11111100", 65 => "00100111", 66 => "11101010", 67 => "11101111", 
    68 => "11010111", 69 => "11000100", 70 => "11100010", 71 => "11011000", 
    72 => "11110011", 73 => "11100110", 74 => "00010011", 75 => "00010011", 
    76 => "11010100", 77 => "11111111", 78 => "11100101", 79 => "01000010", 
    80 => "10111101", 81 => "00010101", 82 => "00001100", 83 => "00011001");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

