-- ==============================================================
-- Generated by Vitis HLS v2025.1.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity lenet_hls_fc_f6_Pipeline_F6_Output_Loop_p_ZL10f6_weights_49_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 8; 
             AddressWidth     : integer := 7; 
             AddressRange    : integer := 84
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of lenet_hls_fc_f6_Pipeline_F6_Output_Loop_p_ZL10f6_weights_49_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00011010", 1 => "00010110", 2 => "10101111", 3 => "11010000", 
    4 => "11100010", 5 => "00100001", 6 => "00101011", 7 => "11111101", 
    8 => "11001110", 9 => "00100001", 10 => "11110101", 11 => "00111110", 
    12 => "00111100", 13 => "01000001", 14 => "11011110", 15 => "00101101", 
    16 => "11000100", 17 => "11111100", 18 => "00011001", 19 => "11101111", 
    20 => "11011010", 21 => "11100010", 22 => "11001000", 23 => "10111010", 
    24 => "11110100", 25 => "11110100", 26 => "11011000", 27 => "11101011", 
    28 => "10101001", 29 => "11100100", 30 => "11110101", 31 => "00001111", 
    32 => "11101110", 33 => "00100100", 34 => "00110100", 35 => "11001111", 
    36 => "11000101", 37 => "00111110", 38 => "11100011", 39 => "00000101", 
    40 => "11101110", 41 => "00011001", 42 => "00010001", 43 => "00110010", 
    44 => "00110011", 45 => "00011111", 46 => "01000010", 47 => "00000110", 
    48 => "00110100", 49 => "01111111", 50 => "11110001", 51 => "11100010", 
    52 => "00001111", 53 => "00010111", 54 => "00010000", 55 => "11011001", 
    56 => "00111111", 57 => "00100101", 58 => "10111010", 59 => "11100110", 
    60 => "00000110", 61 => "11111110", 62 => "00011100", 63 => "11001000", 
    64 => "00100101", 65 => "00111001", 66 => "00110110", 67 => "11100010", 
    68 => "00000010", 69 => "11110101", 70 => "11001000", 71 => "11010101", 
    72 => "10111100", 73 => "00000000", 74 => "00011001", 75 => "11101101", 
    76 => "11010010", 77 => "01011000", 78 => "11111011", 79 => "01000110", 
    80 => "10101010", 81 => "00001111", 82 => "10111101", 83 => "00101111");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

