-- ==============================================================
-- Generated by Vitis HLS v2025.1.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity lenet_hls is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    input_r_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    input_r_ce0 : OUT STD_LOGIC;
    input_r_we0 : OUT STD_LOGIC;
    input_r_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    input_r_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    input_r_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
    input_r_ce1 : OUT STD_LOGIC;
    input_r_we1 : OUT STD_LOGIC;
    input_r_d1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    input_r_q1 : IN STD_LOGIC_VECTOR (7 downto 0);
    output_r_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    output_r_ce0 : OUT STD_LOGIC;
    output_r_we0 : OUT STD_LOGIC;
    output_r_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    output_r_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    output_r_address1 : OUT STD_LOGIC_VECTOR (3 downto 0);
    output_r_ce1 : OUT STD_LOGIC;
    output_r_q1 : IN STD_LOGIC_VECTOR (7 downto 0) );
end;


architecture behav of lenet_hls is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "lenet_hls_lenet_hls,hls_ip_2025_1_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xa7z030-fbg484-1Q,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.073000,HLS_SYN_LAT=78,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=1017,HLS_SYN_LUT=1106,HLS_VERSION=2025_1_1}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (9 downto 0) := "0000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (9 downto 0) := "0000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (9 downto 0) := "0000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (9 downto 0) := "0000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (9 downto 0) := "0000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (9 downto 0) := "0000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (9 downto 0) := "0001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (9 downto 0) := "0010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (9 downto 0) := "0100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (9 downto 0) := "1000000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";

    signal ap_CS_fsm : STD_LOGIC_VECTOR (9 downto 0) := "0000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal max_val_reg_116 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal grp_lenet_hls_Pipeline_Output_Loop_fu_58_ap_start : STD_LOGIC;
    signal grp_lenet_hls_Pipeline_Output_Loop_fu_58_ap_done : STD_LOGIC;
    signal grp_lenet_hls_Pipeline_Output_Loop_fu_58_ap_idle : STD_LOGIC;
    signal grp_lenet_hls_Pipeline_Output_Loop_fu_58_ap_ready : STD_LOGIC;
    signal grp_lenet_hls_Pipeline_Output_Loop_fu_58_output_r_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_lenet_hls_Pipeline_Output_Loop_fu_58_output_r_ce0 : STD_LOGIC;
    signal grp_lenet_hls_Pipeline_Output_Loop_fu_58_output_r_we0 : STD_LOGIC;
    signal grp_lenet_hls_Pipeline_Output_Loop_fu_58_output_r_d0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_lenet_hls_Pipeline_Softmax_Max_Loop_fu_64_ap_start : STD_LOGIC;
    signal grp_lenet_hls_Pipeline_Softmax_Max_Loop_fu_64_ap_done : STD_LOGIC;
    signal grp_lenet_hls_Pipeline_Softmax_Max_Loop_fu_64_ap_idle : STD_LOGIC;
    signal grp_lenet_hls_Pipeline_Softmax_Max_Loop_fu_64_ap_ready : STD_LOGIC;
    signal grp_lenet_hls_Pipeline_Softmax_Max_Loop_fu_64_output_r_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_lenet_hls_Pipeline_Softmax_Max_Loop_fu_64_output_r_ce0 : STD_LOGIC;
    signal grp_lenet_hls_Pipeline_Softmax_Max_Loop_fu_64_max_val_1_out : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_lenet_hls_Pipeline_Softmax_Max_Loop_fu_64_max_val_1_out_ap_vld : STD_LOGIC;
    signal grp_lenet_hls_Pipeline_Softmax_Exp_Loop_fu_72_ap_start : STD_LOGIC;
    signal grp_lenet_hls_Pipeline_Softmax_Exp_Loop_fu_72_ap_done : STD_LOGIC;
    signal grp_lenet_hls_Pipeline_Softmax_Exp_Loop_fu_72_ap_idle : STD_LOGIC;
    signal grp_lenet_hls_Pipeline_Softmax_Exp_Loop_fu_72_ap_ready : STD_LOGIC;
    signal grp_lenet_hls_Pipeline_Softmax_Exp_Loop_fu_72_output_r_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_lenet_hls_Pipeline_Softmax_Exp_Loop_fu_72_output_r_ce0 : STD_LOGIC;
    signal grp_lenet_hls_Pipeline_Softmax_Exp_Loop_fu_72_output_r_we0 : STD_LOGIC;
    signal grp_lenet_hls_Pipeline_Softmax_Exp_Loop_fu_72_output_r_d0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_lenet_hls_Pipeline_Softmax_Exp_Loop_fu_72_output_r_address1 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_lenet_hls_Pipeline_Softmax_Exp_Loop_fu_72_output_r_ce1 : STD_LOGIC;
    signal grp_lenet_hls_Pipeline_Softmax_Exp_Loop_fu_72_sum_exp_out : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_lenet_hls_Pipeline_Softmax_Exp_Loop_fu_72_sum_exp_out_ap_vld : STD_LOGIC;
    signal grp_lenet_hls_Pipeline_Softmax_Norm_Loop_fu_84_ap_start : STD_LOGIC;
    signal grp_lenet_hls_Pipeline_Softmax_Norm_Loop_fu_84_ap_done : STD_LOGIC;
    signal grp_lenet_hls_Pipeline_Softmax_Norm_Loop_fu_84_ap_idle : STD_LOGIC;
    signal grp_lenet_hls_Pipeline_Softmax_Norm_Loop_fu_84_ap_ready : STD_LOGIC;
    signal grp_lenet_hls_Pipeline_Softmax_Norm_Loop_fu_84_output_r_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_lenet_hls_Pipeline_Softmax_Norm_Loop_fu_84_output_r_ce0 : STD_LOGIC;
    signal grp_lenet_hls_Pipeline_Softmax_Norm_Loop_fu_84_output_r_we0 : STD_LOGIC;
    signal grp_lenet_hls_Pipeline_Softmax_Norm_Loop_fu_84_output_r_d0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_lenet_hls_Pipeline_Softmax_Norm_Loop_fu_84_output_r_address1 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_lenet_hls_Pipeline_Softmax_Norm_Loop_fu_84_output_r_ce1 : STD_LOGIC;
    signal grp_lenet_hls_Pipeline_Output_Loop_fu_58_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal grp_lenet_hls_Pipeline_Softmax_Max_Loop_fu_64_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal grp_lenet_hls_Pipeline_Softmax_Exp_Loop_fu_72_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal grp_lenet_hls_Pipeline_Softmax_Norm_Loop_fu_84_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal ap_CS_fsm_state10 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state10 : signal is "none";
    signal output_r_ce0_local : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ST_fsm_state9_blk : STD_LOGIC;
    signal ap_ST_fsm_state10_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component lenet_hls_lenet_hls_Pipeline_Output_Loop IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        output_r_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        output_r_ce0 : OUT STD_LOGIC;
        output_r_we0 : OUT STD_LOGIC;
        output_r_d0 : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component lenet_hls_lenet_hls_Pipeline_Softmax_Max_Loop IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        max_val : IN STD_LOGIC_VECTOR (7 downto 0);
        output_r_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        output_r_ce0 : OUT STD_LOGIC;
        output_r_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        max_val_1_out : OUT STD_LOGIC_VECTOR (7 downto 0);
        max_val_1_out_ap_vld : OUT STD_LOGIC );
    end component;


    component lenet_hls_lenet_hls_Pipeline_Softmax_Exp_Loop IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        output_r_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        output_r_ce0 : OUT STD_LOGIC;
        output_r_we0 : OUT STD_LOGIC;
        output_r_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        output_r_address1 : OUT STD_LOGIC_VECTOR (3 downto 0);
        output_r_ce1 : OUT STD_LOGIC;
        output_r_q1 : IN STD_LOGIC_VECTOR (7 downto 0);
        conv_i_i16_i_i : IN STD_LOGIC_VECTOR (7 downto 0);
        sum_exp_out : OUT STD_LOGIC_VECTOR (7 downto 0);
        sum_exp_out_ap_vld : OUT STD_LOGIC );
    end component;


    component lenet_hls_lenet_hls_Pipeline_Softmax_Norm_Loop IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        output_r_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        output_r_ce0 : OUT STD_LOGIC;
        output_r_we0 : OUT STD_LOGIC;
        output_r_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        output_r_address1 : OUT STD_LOGIC_VECTOR (3 downto 0);
        output_r_ce1 : OUT STD_LOGIC;
        output_r_q1 : IN STD_LOGIC_VECTOR (7 downto 0);
        sext_ln163 : IN STD_LOGIC_VECTOR (7 downto 0) );
    end component;



begin
    grp_lenet_hls_Pipeline_Output_Loop_fu_58 : component lenet_hls_lenet_hls_Pipeline_Output_Loop
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_lenet_hls_Pipeline_Output_Loop_fu_58_ap_start,
        ap_done => grp_lenet_hls_Pipeline_Output_Loop_fu_58_ap_done,
        ap_idle => grp_lenet_hls_Pipeline_Output_Loop_fu_58_ap_idle,
        ap_ready => grp_lenet_hls_Pipeline_Output_Loop_fu_58_ap_ready,
        output_r_address0 => grp_lenet_hls_Pipeline_Output_Loop_fu_58_output_r_address0,
        output_r_ce0 => grp_lenet_hls_Pipeline_Output_Loop_fu_58_output_r_ce0,
        output_r_we0 => grp_lenet_hls_Pipeline_Output_Loop_fu_58_output_r_we0,
        output_r_d0 => grp_lenet_hls_Pipeline_Output_Loop_fu_58_output_r_d0);

    grp_lenet_hls_Pipeline_Softmax_Max_Loop_fu_64 : component lenet_hls_lenet_hls_Pipeline_Softmax_Max_Loop
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_lenet_hls_Pipeline_Softmax_Max_Loop_fu_64_ap_start,
        ap_done => grp_lenet_hls_Pipeline_Softmax_Max_Loop_fu_64_ap_done,
        ap_idle => grp_lenet_hls_Pipeline_Softmax_Max_Loop_fu_64_ap_idle,
        ap_ready => grp_lenet_hls_Pipeline_Softmax_Max_Loop_fu_64_ap_ready,
        max_val => max_val_reg_116,
        output_r_address0 => grp_lenet_hls_Pipeline_Softmax_Max_Loop_fu_64_output_r_address0,
        output_r_ce0 => grp_lenet_hls_Pipeline_Softmax_Max_Loop_fu_64_output_r_ce0,
        output_r_q0 => output_r_q0,
        max_val_1_out => grp_lenet_hls_Pipeline_Softmax_Max_Loop_fu_64_max_val_1_out,
        max_val_1_out_ap_vld => grp_lenet_hls_Pipeline_Softmax_Max_Loop_fu_64_max_val_1_out_ap_vld);

    grp_lenet_hls_Pipeline_Softmax_Exp_Loop_fu_72 : component lenet_hls_lenet_hls_Pipeline_Softmax_Exp_Loop
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_lenet_hls_Pipeline_Softmax_Exp_Loop_fu_72_ap_start,
        ap_done => grp_lenet_hls_Pipeline_Softmax_Exp_Loop_fu_72_ap_done,
        ap_idle => grp_lenet_hls_Pipeline_Softmax_Exp_Loop_fu_72_ap_idle,
        ap_ready => grp_lenet_hls_Pipeline_Softmax_Exp_Loop_fu_72_ap_ready,
        output_r_address0 => grp_lenet_hls_Pipeline_Softmax_Exp_Loop_fu_72_output_r_address0,
        output_r_ce0 => grp_lenet_hls_Pipeline_Softmax_Exp_Loop_fu_72_output_r_ce0,
        output_r_we0 => grp_lenet_hls_Pipeline_Softmax_Exp_Loop_fu_72_output_r_we0,
        output_r_d0 => grp_lenet_hls_Pipeline_Softmax_Exp_Loop_fu_72_output_r_d0,
        output_r_address1 => grp_lenet_hls_Pipeline_Softmax_Exp_Loop_fu_72_output_r_address1,
        output_r_ce1 => grp_lenet_hls_Pipeline_Softmax_Exp_Loop_fu_72_output_r_ce1,
        output_r_q1 => output_r_q1,
        conv_i_i16_i_i => grp_lenet_hls_Pipeline_Softmax_Max_Loop_fu_64_max_val_1_out,
        sum_exp_out => grp_lenet_hls_Pipeline_Softmax_Exp_Loop_fu_72_sum_exp_out,
        sum_exp_out_ap_vld => grp_lenet_hls_Pipeline_Softmax_Exp_Loop_fu_72_sum_exp_out_ap_vld);

    grp_lenet_hls_Pipeline_Softmax_Norm_Loop_fu_84 : component lenet_hls_lenet_hls_Pipeline_Softmax_Norm_Loop
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_lenet_hls_Pipeline_Softmax_Norm_Loop_fu_84_ap_start,
        ap_done => grp_lenet_hls_Pipeline_Softmax_Norm_Loop_fu_84_ap_done,
        ap_idle => grp_lenet_hls_Pipeline_Softmax_Norm_Loop_fu_84_ap_idle,
        ap_ready => grp_lenet_hls_Pipeline_Softmax_Norm_Loop_fu_84_ap_ready,
        output_r_address0 => grp_lenet_hls_Pipeline_Softmax_Norm_Loop_fu_84_output_r_address0,
        output_r_ce0 => grp_lenet_hls_Pipeline_Softmax_Norm_Loop_fu_84_output_r_ce0,
        output_r_we0 => grp_lenet_hls_Pipeline_Softmax_Norm_Loop_fu_84_output_r_we0,
        output_r_d0 => grp_lenet_hls_Pipeline_Softmax_Norm_Loop_fu_84_output_r_d0,
        output_r_address1 => grp_lenet_hls_Pipeline_Softmax_Norm_Loop_fu_84_output_r_address1,
        output_r_ce1 => grp_lenet_hls_Pipeline_Softmax_Norm_Loop_fu_84_output_r_ce1,
        output_r_q1 => output_r_q1,
        sext_ln163 => grp_lenet_hls_Pipeline_Softmax_Exp_Loop_fu_72_sum_exp_out);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_lenet_hls_Pipeline_Output_Loop_fu_58_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_lenet_hls_Pipeline_Output_Loop_fu_58_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                    grp_lenet_hls_Pipeline_Output_Loop_fu_58_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_lenet_hls_Pipeline_Output_Loop_fu_58_ap_ready = ap_const_logic_1)) then 
                    grp_lenet_hls_Pipeline_Output_Loop_fu_58_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_lenet_hls_Pipeline_Softmax_Exp_Loop_fu_72_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_lenet_hls_Pipeline_Softmax_Exp_Loop_fu_72_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
                    grp_lenet_hls_Pipeline_Softmax_Exp_Loop_fu_72_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_lenet_hls_Pipeline_Softmax_Exp_Loop_fu_72_ap_ready = ap_const_logic_1)) then 
                    grp_lenet_hls_Pipeline_Softmax_Exp_Loop_fu_72_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_lenet_hls_Pipeline_Softmax_Max_Loop_fu_64_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_lenet_hls_Pipeline_Softmax_Max_Loop_fu_64_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
                    grp_lenet_hls_Pipeline_Softmax_Max_Loop_fu_64_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_lenet_hls_Pipeline_Softmax_Max_Loop_fu_64_ap_ready = ap_const_logic_1)) then 
                    grp_lenet_hls_Pipeline_Softmax_Max_Loop_fu_64_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_lenet_hls_Pipeline_Softmax_Norm_Loop_fu_84_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_lenet_hls_Pipeline_Softmax_Norm_Loop_fu_84_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
                    grp_lenet_hls_Pipeline_Softmax_Norm_Loop_fu_84_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_lenet_hls_Pipeline_Softmax_Norm_Loop_fu_84_ap_ready = ap_const_logic_1)) then 
                    grp_lenet_hls_Pipeline_Softmax_Norm_Loop_fu_84_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                max_val_reg_116 <= output_r_q0;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, grp_lenet_hls_Pipeline_Output_Loop_fu_58_ap_done, grp_lenet_hls_Pipeline_Softmax_Max_Loop_fu_64_ap_done, grp_lenet_hls_Pipeline_Softmax_Exp_Loop_fu_72_ap_done, grp_lenet_hls_Pipeline_Softmax_Norm_Loop_fu_84_ap_done, ap_CS_fsm_state2, ap_CS_fsm_state6, ap_CS_fsm_state8, ap_CS_fsm_state10)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((grp_lenet_hls_Pipeline_Output_Loop_fu_58_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                if (((grp_lenet_hls_Pipeline_Softmax_Max_Loop_fu_64_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then
                    ap_NS_fsm <= ap_ST_fsm_state7;
                else
                    ap_NS_fsm <= ap_ST_fsm_state6;
                end if;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                if (((grp_lenet_hls_Pipeline_Softmax_Exp_Loop_fu_72_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state8))) then
                    ap_NS_fsm <= ap_ST_fsm_state9;
                else
                    ap_NS_fsm <= ap_ST_fsm_state8;
                end if;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state10;
            when ap_ST_fsm_state10 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state10) and (grp_lenet_hls_Pipeline_Softmax_Norm_Loop_fu_84_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state10;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state10 <= ap_CS_fsm(9);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);
    ap_CS_fsm_state9 <= ap_CS_fsm(8);

    ap_ST_fsm_state10_blk_assign_proc : process(grp_lenet_hls_Pipeline_Softmax_Norm_Loop_fu_84_ap_done)
    begin
        if ((grp_lenet_hls_Pipeline_Softmax_Norm_Loop_fu_84_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state10_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state10_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state2_blk_assign_proc : process(grp_lenet_hls_Pipeline_Output_Loop_fu_58_ap_done)
    begin
        if ((grp_lenet_hls_Pipeline_Output_Loop_fu_58_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state3_blk <= ap_const_logic_0;
    ap_ST_fsm_state4_blk <= ap_const_logic_0;
    ap_ST_fsm_state5_blk <= ap_const_logic_0;

    ap_ST_fsm_state6_blk_assign_proc : process(grp_lenet_hls_Pipeline_Softmax_Max_Loop_fu_64_ap_done)
    begin
        if ((grp_lenet_hls_Pipeline_Softmax_Max_Loop_fu_64_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state6_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state6_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state7_blk <= ap_const_logic_0;

    ap_ST_fsm_state8_blk_assign_proc : process(grp_lenet_hls_Pipeline_Softmax_Exp_Loop_fu_72_ap_done)
    begin
        if ((grp_lenet_hls_Pipeline_Softmax_Exp_Loop_fu_72_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state8_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state8_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state9_blk <= ap_const_logic_0;

    ap_done_assign_proc : process(grp_lenet_hls_Pipeline_Softmax_Norm_Loop_fu_84_ap_done, ap_CS_fsm_state10)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state10) and (grp_lenet_hls_Pipeline_Softmax_Norm_Loop_fu_84_ap_done = ap_const_logic_1))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(grp_lenet_hls_Pipeline_Softmax_Norm_Loop_fu_84_ap_done, ap_CS_fsm_state10)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state10) and (grp_lenet_hls_Pipeline_Softmax_Norm_Loop_fu_84_ap_done = ap_const_logic_1))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    grp_lenet_hls_Pipeline_Output_Loop_fu_58_ap_start <= grp_lenet_hls_Pipeline_Output_Loop_fu_58_ap_start_reg;
    grp_lenet_hls_Pipeline_Softmax_Exp_Loop_fu_72_ap_start <= grp_lenet_hls_Pipeline_Softmax_Exp_Loop_fu_72_ap_start_reg;
    grp_lenet_hls_Pipeline_Softmax_Max_Loop_fu_64_ap_start <= grp_lenet_hls_Pipeline_Softmax_Max_Loop_fu_64_ap_start_reg;
    grp_lenet_hls_Pipeline_Softmax_Norm_Loop_fu_84_ap_start <= grp_lenet_hls_Pipeline_Softmax_Norm_Loop_fu_84_ap_start_reg;
    input_r_address0 <= ap_const_lv10_0;
    input_r_address1 <= ap_const_lv10_0;
    input_r_ce0 <= ap_const_logic_0;
    input_r_ce1 <= ap_const_logic_0;
    input_r_d0 <= ap_const_lv8_0;
    input_r_d1 <= ap_const_lv8_0;
    input_r_we0 <= ap_const_logic_0;
    input_r_we1 <= ap_const_logic_0;

    output_r_address0_assign_proc : process(grp_lenet_hls_Pipeline_Output_Loop_fu_58_output_r_address0, grp_lenet_hls_Pipeline_Softmax_Max_Loop_fu_64_output_r_address0, grp_lenet_hls_Pipeline_Softmax_Exp_Loop_fu_72_output_r_address0, grp_lenet_hls_Pipeline_Softmax_Norm_Loop_fu_84_output_r_address0, ap_CS_fsm_state2, ap_CS_fsm_state6, ap_CS_fsm_state8, ap_CS_fsm_state10)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            output_r_address0 <= grp_lenet_hls_Pipeline_Softmax_Norm_Loop_fu_84_output_r_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            output_r_address0 <= grp_lenet_hls_Pipeline_Softmax_Exp_Loop_fu_72_output_r_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            output_r_address0 <= grp_lenet_hls_Pipeline_Softmax_Max_Loop_fu_64_output_r_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            output_r_address0 <= grp_lenet_hls_Pipeline_Output_Loop_fu_58_output_r_address0;
        else 
            output_r_address0 <= ap_const_lv64_0(4 - 1 downto 0);
        end if; 
    end process;


    output_r_address1_assign_proc : process(grp_lenet_hls_Pipeline_Softmax_Exp_Loop_fu_72_output_r_address1, grp_lenet_hls_Pipeline_Softmax_Norm_Loop_fu_84_output_r_address1, ap_CS_fsm_state8, ap_CS_fsm_state10)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            output_r_address1 <= grp_lenet_hls_Pipeline_Softmax_Norm_Loop_fu_84_output_r_address1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            output_r_address1 <= grp_lenet_hls_Pipeline_Softmax_Exp_Loop_fu_72_output_r_address1;
        else 
            output_r_address1 <= "XXXX";
        end if; 
    end process;


    output_r_ce0_assign_proc : process(grp_lenet_hls_Pipeline_Output_Loop_fu_58_output_r_ce0, grp_lenet_hls_Pipeline_Softmax_Max_Loop_fu_64_output_r_ce0, grp_lenet_hls_Pipeline_Softmax_Exp_Loop_fu_72_output_r_ce0, grp_lenet_hls_Pipeline_Softmax_Norm_Loop_fu_84_output_r_ce0, ap_CS_fsm_state2, ap_CS_fsm_state6, ap_CS_fsm_state8, ap_CS_fsm_state10, output_r_ce0_local)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            output_r_ce0 <= grp_lenet_hls_Pipeline_Softmax_Norm_Loop_fu_84_output_r_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            output_r_ce0 <= grp_lenet_hls_Pipeline_Softmax_Exp_Loop_fu_72_output_r_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            output_r_ce0 <= grp_lenet_hls_Pipeline_Softmax_Max_Loop_fu_64_output_r_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            output_r_ce0 <= grp_lenet_hls_Pipeline_Output_Loop_fu_58_output_r_ce0;
        else 
            output_r_ce0 <= output_r_ce0_local;
        end if; 
    end process;


    output_r_ce0_local_assign_proc : process(ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            output_r_ce0_local <= ap_const_logic_1;
        else 
            output_r_ce0_local <= ap_const_logic_0;
        end if; 
    end process;


    output_r_ce1_assign_proc : process(grp_lenet_hls_Pipeline_Softmax_Exp_Loop_fu_72_output_r_ce1, grp_lenet_hls_Pipeline_Softmax_Norm_Loop_fu_84_output_r_ce1, ap_CS_fsm_state8, ap_CS_fsm_state10)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            output_r_ce1 <= grp_lenet_hls_Pipeline_Softmax_Norm_Loop_fu_84_output_r_ce1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            output_r_ce1 <= grp_lenet_hls_Pipeline_Softmax_Exp_Loop_fu_72_output_r_ce1;
        else 
            output_r_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    output_r_d0_assign_proc : process(grp_lenet_hls_Pipeline_Output_Loop_fu_58_output_r_d0, grp_lenet_hls_Pipeline_Softmax_Exp_Loop_fu_72_output_r_d0, grp_lenet_hls_Pipeline_Softmax_Norm_Loop_fu_84_output_r_d0, ap_CS_fsm_state2, ap_CS_fsm_state8, ap_CS_fsm_state10)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            output_r_d0 <= grp_lenet_hls_Pipeline_Softmax_Norm_Loop_fu_84_output_r_d0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            output_r_d0 <= grp_lenet_hls_Pipeline_Softmax_Exp_Loop_fu_72_output_r_d0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            output_r_d0 <= grp_lenet_hls_Pipeline_Output_Loop_fu_58_output_r_d0;
        else 
            output_r_d0 <= "XXXXXXXX";
        end if; 
    end process;


    output_r_we0_assign_proc : process(grp_lenet_hls_Pipeline_Output_Loop_fu_58_output_r_we0, grp_lenet_hls_Pipeline_Softmax_Exp_Loop_fu_72_output_r_we0, grp_lenet_hls_Pipeline_Softmax_Norm_Loop_fu_84_output_r_we0, ap_CS_fsm_state2, ap_CS_fsm_state8, ap_CS_fsm_state10)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            output_r_we0 <= grp_lenet_hls_Pipeline_Softmax_Norm_Loop_fu_84_output_r_we0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            output_r_we0 <= grp_lenet_hls_Pipeline_Softmax_Exp_Loop_fu_72_output_r_we0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            output_r_we0 <= grp_lenet_hls_Pipeline_Output_Loop_fu_58_output_r_we0;
        else 
            output_r_we0 <= ap_const_logic_0;
        end if; 
    end process;

end behav;
