-- ==============================================================
-- Generated by Vitis HLS v2025.1.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity lenet_hls_fc_f6_Pipeline_F6_Output_Loop_p_ZL10f6_weights_61_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 8; 
             AddressWidth     : integer := 7; 
             AddressRange    : integer := 84
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of lenet_hls_fc_f6_Pipeline_F6_Output_Loop_p_ZL10f6_weights_61_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00001010", 1 => "01001001", 2 => "00100011", 3 => "00011110", 
    4 => "10111010", 5 => "11111011", 6 => "11111100", 7 => "00110001", 
    8 => "00010000", 9 => "00010010", 10 => "01010101", 11 => "00000100", 
    12 => "00001000", 13 => "01000010", 14 => "00001000", 15 => "11100111", 
    16 => "00011000", 17 => "11100011", 18 => "00100011", 19 => "00111110", 
    20 => "00011101", 21 => "00101001", 22 => "11101011", 23 => "00000101", 
    24 => "00100110", 25 => "11100100", 26 => "00001001", 27 => "00001001", 
    28 => "01000100", 29 => "11101100", 30 => "11010011", 31 => "11011011", 
    32 => "00001100", 33 => "00000111", 34 => "11111110", 35 => "01001110", 
    36 => "10110001", 37 => "11011010", 38 => "11101110", 39 => "11000000", 
    40 => "00011001", 41 => "11110000", 42 => "01000001", 43 => "00010111", 
    44 => "11010000", 45 => "00101111", 46 => "00001010", 47 => "11101010", 
    48 => "00010100", 49 => "11010001", 50 => "01001010", 51 => "11100001", 
    52 => "11000001", 53 => "11110100", 54 => "00111000", 55 => "11110100", 
    56 => "11010011", 57 => "11000101", 58 => "00100100", 59 => "11111111", 
    60 => "01010101", 61 => "01000111", 62 => "11110100", 63 => "00110111", 
    64 => "11100101", 65 => "11110111", 66 => "01001110", 67 => "00010111", 
    68 => "01010101", 69 => "00011110", 70 => "10101101", 71 => "11111010", 
    72 => "00011101", 73 => "00100101", 74 => "00110011", 75 => "11011000", 
    76 => "11110111", 77 => "11010100", 78 => "11100101", 79 => "11010100", 
    80 => "00111000", 81 => "00000100", 82 => "11101111", 83 => "11111100");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

