-- ==============================================================
-- Generated by Vitis HLS v2025.1.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity lenet_hls_fc_f6_Pipeline_F6_Output_Loop_p_ZL10f6_weights_110_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 8; 
             AddressWidth     : integer := 7; 
             AddressRange    : integer := 84
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of lenet_hls_fc_f6_Pipeline_F6_Output_Loop_p_ZL10f6_weights_110_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "11000111", 1 => "00111110", 2 => "00001110", 3 => "11110010", 
    4 => "01010001", 5 => "00101101", 6 => "11000000", 7 => "00111010", 
    8 => "00100100", 9 => "00010011", 10 => "11101110", 11 => "00011001", 
    12 => "00000010", 13 => "00100001", 14 => "11111110", 15 => "11010111", 
    16 => "11110000", 17 => "11110101", 18 => "10001111", 19 => "11001100", 
    20 => "10101111", 21 => "00101001", 22 => "00101101", 23 => "01010100", 
    24 => "11111001", 25 => "00101000", 26 => "11000110", 27 => "00101001", 
    28 => "11111100", 29 => "00100110", 30 => "00110101", 31 => "00011110", 
    32 => "00011110", 33 => "11010010", 34 => "11010101", 35 => "11110000", 
    36 => "11011110", 37 => "10111011", 38 => "10010011", 39 => "11100010", 
    40 => "00001100", 41 => "00010000", 42 => "11100110", 43 => "00011100", 
    44 => "11110110", 45 => "00001010", 46 => "00001111", 47 => "11001111", 
    48 => "11010101", 49 => "11010101", 50 => "01010101", 51 => "00101001", 
    52 => "00110101", 53 => "00010111", 54 => "00101010", 55 => "01010000", 
    56 => "00101001", 57 => "11011100", 58 => "00010100", 59 => "11001010", 
    60 => "00000001", 61 => "00000011", 62 => "10010101", 63 => "01001110", 
    64 => "00000100", 65 => "11010011", 66 => "11100111", 67 => "01010011", 
    68 => "11111101", 69 => "10111010", 70 => "00101001", 71 => "01111111", 
    72 => "00110001", 73 => "00011000", 74 => "11011010", 75 => "11101101", 
    76 => "11111010", 77 => "10101100", 78 => "10110100", 79 => "11101100", 
    80 => "10111011", 81 => "00100000", 82 => "11001011", 83 => "01011110");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

