-- ==============================================================
-- Generated by Vitis HLS v2025.1.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity lenet_hls_fc_f6_Pipeline_F6_Output_Loop_p_ZL10f6_weights_71_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 8; 
             AddressWidth     : integer := 7; 
             AddressRange    : integer := 84
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of lenet_hls_fc_f6_Pipeline_F6_Output_Loop_p_ZL10f6_weights_71_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00110010", 1 => "00101100", 2 => "01001101", 3 => "01010100", 
    4 => "10110110", 5 => "11100010", 6 => "10111011", 7 => "00000001", 
    8 => "00011100", 9 => "11100100", 10 => "11001101", 11 => "00001110", 
    12 => "11101101", 13 => "00011000", 14 => "00001111", 15 => "01010101", 
    16 => "00110110", 17 => "11111111", 18 => "00001011", 19 => "11000010", 
    20 => "00111010", 21 => "11111111", 22 => "01101111", 23 => "00011100", 
    24 => "11101001", 25 => "01001001", 26 => "00000010", 27 => "00001011", 
    28 => "00011010", 29 => "11010011", 30 => "01010110", 31 => "01011010", 
    32 => "00100101", 33 => "10110000", 34 => "11010100", 35 => "11101001", 
    36 => "11010010", 37 => "00011000", 38 => "01000010", 39 => "00101100", 
    40 => "00110110", 41 => "11000001", 42 => "00010100", 43 => "00000011", 
    44 => "10101111", 45 => "11001000", 46 => "00111111", 47 => "11000100", 
    48 => "01101010", 49 => "00001000", 50 => "10110100", 51 => "00101100", 
    52 => "11101010", 53 => "00100011", 54 => "11001000", 55 => "01000110", 
    56 => "11000111", 57 => "00100011", 58 => "11111010", 59 => "01011100", 
    60 => "11000011", 61 => "01010101", 62 => "00110000", 63 => "00100011", 
    64 => "00001111", 65 => "00001000", 66 => "00101101", 67 => "00011101", 
    68 => "11101010", 69 => "00101011", 70 => "00010100", 71 => "00000111", 
    72 => "11111010", 73 => "00000011", 74 => "11000101", 75 => "00110001", 
    76 => "01010011", 77 => "11111010", 78 => "00001100", 79 => "11001111", 
    80 => "01001110", 81 => "00101110", 82 => "00010011", 83 => "10111100");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

