-- ==============================================================
-- Generated by Vitis HLS v2025.1.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity lenet_hls_fc_f6_Pipeline_F6_Output_Loop_p_ZL10f6_weights_36_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 8; 
             AddressWidth     : integer := 7; 
             AddressRange    : integer := 84
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of lenet_hls_fc_f6_Pipeline_F6_Output_Loop_p_ZL10f6_weights_36_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00001011", 1 => "00111010", 2 => "10110101", 3 => "00001011", 
    4 => "01010100", 5 => "00001101", 6 => "11100010", 7 => "11100101", 
    8 => "11100111", 9 => "00000100", 10 => "11110101", 11 => "00000001", 
    12 => "00111011", 13 => "00101101", 14 => "00111110", 15 => "11100011", 
    16 => "00011010", 17 => "11101000", 18 => "11010100", 19 => "00010110", 
    20 => "11001000", 21 => "10101101", 22 => "00100111", 23 => "10101111", 
    24 => "01101001", 25 => "00000100", 26 => "10111111", 27 => "11100101", 
    28 => "11001011", 29 => "00111001", 30 => "00001010", 31 => "01011010", 
    32 => "11011111", 33 => "00000101", 34 => "10100100", 35 => "11000100", 
    36 => "11011110", 37 => "00110111", 38 => "01010010", 39 => "11101000", 
    40 => "11101111", 41 => "00101010", 42 => "00100000", 43 => "11110100", 
    44 => "11110100", 45 => "00010010", 46 => "00011111", 47 => "10111101", 
    48 => "11101111", 49 => "00111110", 50 => "11010111", 51 => "00001100", 
    52 => "11101000", 53 => "00011110", 54 => "11001101", 55 => "11010111", 
    56 => "00010110", 57 => "11010100", 58 => "11110000", 59 => "01100011", 
    60 => "11111000", 61 => "11110111", 62 => "01001010", 63 => "11110100", 
    64 => "01000101", 65 => "00000110", 66 => "00100110", 67 => "11011110", 
    68 => "11101000", 69 => "00101010", 70 => "11100101", 71 => "01001010", 
    72 => "11100101", 73 => "00011101", 74 => "00011100", 75 => "11111110", 
    76 => "11111000", 77 => "01011100", 78 => "11010111", 79 => "00101000", 
    80 => "11110111", 81 => "11001010", 82 => "10111100", 83 => "11011111");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

