-- ==============================================================
-- Generated by Vitis HLS v2025.1.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity lenet_hls_fc_f6_Pipeline_F6_Output_Loop_p_ZL10f6_weights_95_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 8; 
             AddressWidth     : integer := 7; 
             AddressRange    : integer := 84
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of lenet_hls_fc_f6_Pipeline_F6_Output_Loop_p_ZL10f6_weights_95_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "10110010", 1 => "00100110", 2 => "11011111", 3 => "10111010", 
    4 => "01010110", 5 => "11000011", 6 => "10101000", 7 => "11011101", 
    8 => "00000000", 9 => "11111101", 10 => "11000000", 11 => "11001010", 
    12 => "00011101", 13 => "00001111", 14 => "01111111", 15 => "00101111", 
    16 => "11110100", 17 => "00011101", 18 => "11101000", 19 => "00001111", 
    20 => "00011000", 21 => "11111101", 22 => "10111000", 23 => "00110010", 
    24 => "00100101", 25 => "00100111", 26 => "11101010", 27 => "00011001", 
    28 => "00001010", 29 => "11010000", 30 => "01001001", 31 => "00010110", 
    32 => "11110101", 33 => "11110000", 34 => "11010000", 35 => "10011111", 
    36 => "01000101", 37 => "11111011", 38 => "01000110", 39 => "00110001", 
    40 => "00110110", 41 => "01000101", 42 => "11001010", 43 => "00110111", 
    44 => "10111011", 45 => "00101010", 46 => "00001110", 47 => "00011100", 
    48 => "00101110", 49 => "01001111", 50 => "00000010", 51 => "11111000", 
    52 => "01001001", 53 => "00001111", 54 => "01000011", 55 => "00101110", 
    56 => "01011010", 57 => "11100011", 58 => "00010000", 59 => "00000110", 
    60 => "00101110", 61 => "11110010", 62 => "00000111", 63 => "11111011", 
    64 => "11011110", 65 => "00111000", 66 => "00010011", 67 => "11101100", 
    68 => "11100111", 69 => "11010000", 70 => "01110001", 71 => "11011000", 
    72 => "00000011", 73 => "10110000", 74 => "10101110", 75 => "00100011", 
    76 => "00100011", 77 => "00010101", 78 => "11001010", 79 => "11100111", 
    80 => "10110110", 81 => "11110110", 82 => "10111000", 83 => "00111010");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

