-- ==============================================================
-- Generated by Vitis HLS v2025.1.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity lenet_hls_fc_f6_Pipeline_F6_Output_Loop_p_ZL10f6_weights_99_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 8; 
             AddressWidth     : integer := 7; 
             AddressRange    : integer := 84
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of lenet_hls_fc_f6_Pipeline_F6_Output_Loop_p_ZL10f6_weights_99_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00100001", 1 => "10101110", 2 => "00011111", 3 => "01000100", 
    4 => "11001010", 5 => "11010001", 6 => "11010011", 7 => "11000111", 
    8 => "11011011", 9 => "11111011", 10 => "10101111", 11 => "10111000", 
    12 => "11111110", 13 => "11111010", 14 => "11111111", 15 => "01010110", 
    16 => "11001001", 17 => "01011011", 18 => "00000111", 19 => "10101001", 
    20 => "00001011", 21 => "11101101", 22 => "01101100", 23 => "01001010", 
    24 => "11000101", 25 => "01100001", 26 => "00011110", 27 => "10011000", 
    28 => "00011001", 29 => "10010110", 30 => "01001110", 31 => "01011001", 
    32 => "11101000", 33 => "11001100", 34 => "11111111", 35 => "00101101", 
    36 => "00011101", 37 => "00111101", 38 => "00010001", 39 => "00110110", 
    40 => "00000111", 41 => "00011011", 42 => "11101101", 43 => "00001111", 
    44 => "10110001", 45 => "00001010", 46 => "11011111", 47 => "11110001", 
    48 => "00101100", 49 => "00011000", 50 => "11100011", 51 => "11110010", 
    52 => "00010101", 53 => "11001101", 54 => "11110110", 55 => "00010111", 
    56 => "11000001", 57 => "01101101", 58 => "11110101", 59 => "11011100", 
    60 => "11110000", 61 => "11100100", 62 => "01011010", 63 => "11001111", 
    64 => "00111010", 65 => "01010010", 66 => "10101101", 67 => "00001111", 
    68 => "10101001", 69 => "00010010", 70 => "00011100", 71 => "01110011", 
    72 => "10101010", 73 => "10110011", 74 => "10100010", 75 => "00111100", 
    76 => "00101010", 77 => "00011110", 78 => "11100001", 79 => "11101000", 
    80 => "00001101", 81 => "11111111", 82 => "00111001", 83 => "10101011");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

