-- ==============================================================
-- Generated by Vitis HLS v2025.1.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity lenet_hls_fc_f6_Pipeline_F6_Output_Loop_p_ZL10f6_weights_18_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 8; 
             AddressWidth     : integer := 7; 
             AddressRange    : integer := 84
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of lenet_hls_fc_f6_Pipeline_F6_Output_Loop_p_ZL10f6_weights_18_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "11110111", 1 => "00100000", 2 => "11101111", 3 => "00010100", 
    4 => "11101001", 5 => "11101110", 6 => "00011001", 7 => "11000010", 
    8 => "11110100", 9 => "11110111", 10 => "11010111", 11 => "11011000", 
    12 => "11101110", 13 => "00111000", 14 => "00001111", 15 => "00011000", 
    16 => "00110000", 17 => "11011100", 18 => "00100111", 19 => "11100101", 
    20 => "00011011", 21 => "00001010", 22 => "11110001", 23 => "11101001", 
    24 => "00101111", 25 => "11111100", 26 => "00000011", 27 => "11011110", 
    28 => "11100001", 29 => "11101101", 30 => "11100000", 31 => "00011100", 
    32 => "00000100", 33 => "00110010", 34 => "00101101", 35 => "11110100", 
    36 => "00110100", 37 => "11110010", 38 => "00101101", 39 => "00100010", 
    40 => "00100111", 41 => "11010111", 42 => "00011000", 43 => "00100011", 
    44 => "11011011", 45 => "11110010", 46 => "11100101", 47 => "00011011", 
    48 => "00101010", 49 => "00110101", 50 => "11101100", 51 => "00011110", 
    52 => "00110010", 53 => "00011100", 54 => "00101110", 55 => "11011110", 
    56 => "11110111", 57 => "11010101", 58 => "01001001", 59 => "11011011", 
    60 => "11111010", 61 => "11101000", 62 => "11111011", 63 => "11101101", 
    64 => "00011111", 65 => "00110110", 66 => "11101101", 67 => "00010111", 
    68 => "00110111", 69 => "00100010", 70 => "00101101", 71 => "11100100", 
    72 => "11111100", 73 => "00001111", 74 => "11010110", 75 => "00011010", 
    76 => "00000110", 77 => "11011011", 78 => "00010010", 79 => "10111001", 
    80 => "11101010", 81 => "00010011", 82 => "00010100", 83 => "00001011");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

