-- ==============================================================
-- Generated by Vitis HLS v2025.1.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity lenet_hls_fc_f6_Pipeline_F6_Output_Loop_p_ZL10f6_weights_33_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 8; 
             AddressWidth     : integer := 7; 
             AddressRange    : integer := 84
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of lenet_hls_fc_f6_Pipeline_F6_Output_Loop_p_ZL10f6_weights_33_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00010100", 1 => "11010010", 2 => "00001011", 3 => "11100111", 
    4 => "11100111", 5 => "11011010", 6 => "00001001", 7 => "11010110", 
    8 => "11010010", 9 => "11010001", 10 => "11100001", 11 => "00011110", 
    12 => "00100001", 13 => "11101111", 14 => "00000000", 15 => "01001000", 
    16 => "01001001", 17 => "00111010", 18 => "00110000", 19 => "00011110", 
    20 => "01010000", 21 => "11010110", 22 => "11000110", 23 => "11100010", 
    24 => "00100001", 25 => "00011001", 26 => "11000101", 27 => "11101010", 
    28 => "11010011", 29 => "00100011", 30 => "00000010", 31 => "00100100", 
    32 => "00100100", 33 => "01010100", 34 => "00101001", 35 => "00011011", 
    36 => "11110011", 37 => "11100101", 38 => "01001110", 39 => "01000101", 
    40 => "01000110", 41 => "11111010", 42 => "11100000", 43 => "01000110", 
    44 => "00000011", 45 => "00110110", 46 => "00101011", 47 => "11000001", 
    48 => "01010100", 49 => "01011011", 50 => "11110100", 51 => "11011001", 
    52 => "00001100", 53 => "11110010", 54 => "11101101", 55 => "10110000", 
    56 => "00100010", 57 => "11100101", 58 => "00001001", 59 => "00010111", 
    60 => "00111101", 61 => "11100010", 62 => "01101011", 63 => "11111111", 
    64 => "01001011", 65 => "00010000", 66 => "11110101", 67 => "11001000", 
    68 => "00000111", 69 => "11100000", 70 => "00101000", 71 => "10111010", 
    72 => "10111111", 73 => "10111101", 74 => "00100110", 75 => "00000000", 
    76 => "11010101", 77 => "11101001", 78 => "00100100", 79 => "11101110", 
    80 => "00001000", 81 => "00101111", 82 => "00011000", 83 => "11100100");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

