-- ==============================================================
-- Generated by Vitis HLS v2025.1.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity lenet_hls_fc_f6_Pipeline_F6_Output_Loop_p_ZL10f6_weights_116_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 8; 
             AddressWidth     : integer := 7; 
             AddressRange    : integer := 84
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of lenet_hls_fc_f6_Pipeline_F6_Output_Loop_p_ZL10f6_weights_116_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "11011011", 1 => "10111101", 2 => "00101111", 3 => "01001000", 
    4 => "00011000", 5 => "10111000", 6 => "00111110", 7 => "11110100", 
    8 => "11111010", 9 => "00101000", 10 => "00000110", 11 => "01000010", 
    12 => "00010101", 13 => "11100111", 14 => "11101010", 15 => "11001101", 
    16 => "00101110", 17 => "00101111", 18 => "01010010", 19 => "11111011", 
    20 => "00101111", 21 => "01011000", 22 => "11100100", 23 => "11110010", 
    24 => "00000100", 25 => "11100010", 26 => "11000011", 27 => "00111010", 
    28 => "00100110", 29 => "00100011", 30 => "10110111", 31 => "11000010", 
    32 => "11011110", 33 => "01010111", 34 => "11110010", 35 => "00111011", 
    36 => "10111011", 37 => "00011111", 38 => "00001000", 39 => "00000001", 
    40 => "00011110", 41 => "11001010", 42 => "01000010", 43 => "11001100", 
    44 => "00111101", 45 => "00100111", 46 => "11000010", 47 => "11111110", 
    48 => "10111111", 49 => "11001010", 50 => "11101100", 51 => "11010100", 
    52 => "00101000", 53 => "11110100", 54 => "11011011", 55 => "11011011", 
    56 => "11010101", 57 => "11100111", 58 => "11011001", 59 => "11111000", 
    60 => "00100110", 61 => "11010100", 62 => "00010010", 63 => "00011001", 
    64 => "01000101", 65 => "10110000", 66 => "11001111", 67 => "11001100", 
    68 => "01000001", 69 => "10110111", 70 => "11101011", 71 => "11010110", 
    72 => "01001001", 73 => "11101001", 74 => "01010101", 75 => "11101101", 
    76 => "11001010", 77 => "11100101", 78 => "00000000", 79 => "00010110", 
    80 => "00101111", 81 => "00100011", 82 => "10111010", 83 => "00011010");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

