-- ==============================================================
-- Generated by Vitis HLS v2025.1.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity lenet_hls_fc_f6_Pipeline_F6_Output_Loop_p_ZL10f6_weights_52_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 8; 
             AddressWidth     : integer := 7; 
             AddressRange    : integer := 84
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of lenet_hls_fc_f6_Pipeline_F6_Output_Loop_p_ZL10f6_weights_52_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "11101110", 1 => "11100111", 2 => "11010111", 3 => "11010011", 
    4 => "00000011", 5 => "10110110", 6 => "11100000", 7 => "00111110", 
    8 => "11000001", 9 => "00010100", 10 => "00011110", 11 => "00101010", 
    12 => "11101010", 13 => "11100001", 14 => "00001001", 15 => "00010110", 
    16 => "11001110", 17 => "00000001", 18 => "00010111", 19 => "11101011", 
    20 => "11000101", 21 => "00000110", 22 => "10110111", 23 => "01000011", 
    24 => "11110000", 25 => "11111111", 26 => "00010011", 27 => "11110111", 
    28 => "11101011", 29 => "11010110", 30 => "11001111", 31 => "00100001", 
    32 => "00011100", 33 => "11111110", 34 => "11001111", 35 => "11110111", 
    36 => "11101011", 37 => "11000100", 38 => "00001100", 39 => "00000110", 
    40 => "11011101", 41 => "00100010", 42 => "00100001", 43 => "11101000", 
    44 => "00001011", 45 => "00110100", 46 => "00000001", 47 => "00000110", 
    48 => "10101010", 49 => "11010010", 50 => "01001011", 51 => "11111111", 
    52 => "01001011", 53 => "11110111", 54 => "00110011", 55 => "00100101", 
    56 => "01011111", 57 => "11001100", 58 => "00101001", 59 => "11111110", 
    60 => "00100000", 61 => "00000000", 62 => "11100110", 63 => "01000010", 
    64 => "00001010", 65 => "11101100", 66 => "00101111", 67 => "11111001", 
    68 => "11110111", 69 => "11000100", 70 => "00111110", 71 => "00011100", 
    72 => "01011000", 73 => "00110010", 74 => "00111110", 75 => "00010111", 
    76 => "11100011", 77 => "10110010", 78 => "11010101", 79 => "11100010", 
    80 => "10111101", 81 => "11101011", 82 => "11110000", 83 => "01010100");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

