-- ==============================================================
-- Generated by Vitis HLS v2025.1.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity lenet_hls_fc_f6_Pipeline_F6_Output_Loop_p_ZL10f6_weights_25_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 8; 
             AddressWidth     : integer := 7; 
             AddressRange    : integer := 84
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of lenet_hls_fc_f6_Pipeline_F6_Output_Loop_p_ZL10f6_weights_25_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00000100", 1 => "10100111", 2 => "11100110", 3 => "00010111", 
    4 => "11011000", 5 => "00010001", 6 => "01010000", 7 => "00011001", 
    8 => "00001001", 9 => "00000101", 10 => "00001000", 11 => "00110001", 
    12 => "00111101", 13 => "10111111", 14 => "11100110", 15 => "11011000", 
    16 => "01001000", 17 => "00000001", 18 => "01101101", 19 => "01010101", 
    20 => "00000010", 21 => "11011010", 22 => "11001011", 23 => "10100001", 
    24 => "00001011", 25 => "00000110", 26 => "11100110", 27 => "10101100", 
    28 => "11110100", 29 => "11011100", 30 => "10110111", 31 => "10110101", 
    32 => "11111101", 33 => "00111000", 34 => "00110111", 35 => "01010100", 
    36 => "11001000", 37 => "01010010", 38 => "00010011", 39 => "00101000", 
    40 => "11010100", 41 => "11100100", 42 => "10100000", 43 => "01001111", 
    44 => "00111010", 45 => "01010101", 46 => "00111100", 47 => "11001110", 
    48 => "11100010", 49 => "00101011", 50 => "00010011", 51 => "00001101", 
    52 => "01010001", 53 => "11110101", 54 => "11101100", 55 => "10111100", 
    56 => "00111011", 57 => "11111100", 58 => "11001001", 59 => "11010000", 
    60 => "01011101", 61 => "11000000", 62 => "00000100", 63 => "11000110", 
    64 => "01000010", 65 => "10110011", 66 => "01000110", 67 => "11111110", 
    68 => "00100000", 69 => "00001000", 70 => "00000000", 71 => "00111011", 
    72 => "11100010", 73 => "11100011", 74 => "11110011", 75 => "11110011", 
    76 => "00100110", 77 => "11001001", 78 => "11100110", 79 => "00000101", 
    80 => "00010000", 81 => "00010000", 82 => "11100010", 83 => "11101001");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

