-- ==============================================================
-- Generated by Vitis HLS v2025.1.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity lenet_hls_fc_f6_Pipeline_F6_Output_Loop_p_ZL10f6_weights_2_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 8; 
             AddressWidth     : integer := 7; 
             AddressRange    : integer := 84
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of lenet_hls_fc_f6_Pipeline_F6_Output_Loop_p_ZL10f6_weights_2_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00100011", 1 => "00000001", 2 => "00100010", 3 => "00010110", 
    4 => "10000011", 5 => "11100011", 6 => "00011010", 7 => "11101100", 
    8 => "00101001", 9 => "01100000", 10 => "11010010", 11 => "11110000", 
    12 => "00011000", 13 => "00001000", 14 => "11011101", 15 => "00011001", 
    16 => "00101110", 17 => "00110110", 18 => "00000000", 19 => "11111111", 
    20 => "00110010", 21 => "11100111", 22 => "01100001", 23 => "00001110", 
    24 => "11010010", 25 => "11110101", 26 => "11011011", 27 => "00100011", 
    28 => "01010100", 29 => "10010101", 30 => "11111000", 31 => "11111101", 
    32 => "11100010", 33 => "00101010", 34 => "01001011", 35 => "00100010", 
    36 => "10010000", 37 => "11011011", 38 => "11011010", 39 => "00011010", 
    40 => "00010110", 41 => "11000011", 42 => "11010100", 43 => "11001001", 
    44 => "00001001", 45 => "00000001", 46 => "01001001", 47 => "10111001", 
    48 => "01001011", 49 => "11000110", 50 => "00011110", 51 => "00101100", 
    52 => "00001000", 53 => "11110101", 54 => "11010001", 55 => "00001100", 
    56 => "11111101", 57 => "00110010", 58 => "00000110", 59 => "11111110", 
    60 => "00010111", 61 => "00011100", 62 => "01000010", 63 => "11110011", 
    64 => "10011111", 65 => "00110111", 66 => "00011111", 67 => "00010011", 
    68 => "11110101", 69 => "00001001", 70 => "10110010", 71 => "01010010", 
    72 => "11001000", 73 => "11110100", 74 => "11111111", 75 => "00100010", 
    76 => "11111000", 77 => "11001101", 78 => "11100000", 79 => "11011111", 
    80 => "00011100", 81 => "11110100", 82 => "00010010", 83 => "11100011");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

