-- ==============================================================
-- Generated by Vitis HLS v2025.1.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity lenet_hls_fc_f6_Pipeline_F6_Output_Loop_p_ZL10f6_weights_103_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 8; 
             AddressWidth     : integer := 7; 
             AddressRange    : integer := 84
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of lenet_hls_fc_f6_Pipeline_F6_Output_Loop_p_ZL10f6_weights_103_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "11101100", 1 => "00000001", 2 => "11011101", 3 => "00001001", 
    4 => "00110001", 5 => "11001000", 6 => "00011001", 7 => "10111101", 
    8 => "11101110", 9 => "00011011", 10 => "00001001", 11 => "00001101", 
    12 => "11011000", 13 => "00010011", 14 => "00011001", 15 => "11100000", 
    16 => "11100110", 17 => "00111010", 18 => "00010100", 19 => "00111000", 
    20 => "11111101", 21 => "00000011", 22 => "11011001", 23 => "01000000", 
    24 => "00111000", 25 => "00010001", 26 => "11011110", 27 => "11110010", 
    28 => "11001001", 29 => "00001111", 30 => "00110000", 31 => "00011000", 
    32 => "11011110", 33 => "00010011", 34 => "00010111", 35 => "11111100", 
    36 => "11111101", 37 => "11110001", 38 => "11111100", 39 => "00110011", 
    40 => "00010111", 41 => "00101010", 42 => "00100101", 43 => "11110111", 
    44 => "11111001", 45 => "11001110", 46 => "11011110", 47 => "11100001", 
    48 => "11100111", 49 => "11101100", 50 => "11100011", 51 => "11110001", 
    52 => "11010000", 53 => "11110010", 54 => "11011000", 55 => "11011010", 
    56 => "11100000", 57 => "00000001", 58 => "00101010", 59 => "00110100", 
    60 => "11010000", 61 => "00101000", 62 => "11110000", 63 => "11100000", 
    64 => "11010010", 65 => "00101011", 66 => "00011101", 67 => "00001010", 
    68 => "00001001", 69 => "11110001", 70 => "00000000", 71 => "00011011", 
    72 => "00101000", 73 => "00001011", 74 => "00000011", 75 => "00010000", 
    76 => "11010000", 77 => "11001111", 78 => "00101001", 79 => "00101001", 
    80 => "11111011", 81 => "11001110", 82 => "00001000", 83 => "11111110");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

