-- ==============================================================
-- Generated by Vitis HLS v2025.1.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity lenet_hls_fc_f6_Pipeline_F6_Output_Loop_p_ZL10f6_weights_90_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 7; 
             AddressWidth     : integer := 7; 
             AddressRange    : integer := 84
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of lenet_hls_fc_f6_Pipeline_F6_Output_Loop_p_ZL10f6_weights_90_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "0111010", 1 => "1001110", 2 => "0001101", 3 => "0101111", 
    4 => "1011001", 5 => "1110001", 6 => "1101001", 7 => "0001110", 
    8 => "0001110", 9 => "0000000", 10 => "1000101", 11 => "0101100", 
    12 => "1011011", 13 => "0011101", 14 => "1101110", 15 => "1010001", 
    16 => "1110011", 17 => "0000010", 18 => "0000010", 19 => "0001110", 
    20 => "1110111", 21 => "0000101", 22 => "0001010", 23 => "1010001", 
    24 => "1110110", 25 => "1110000", 26 => "0000100", 27 => "1100000", 
    28 => "1011000", 29 => "0110101", 30 => "0010101", 31 => "0000110", 
    32 => "1010100", 33 => "0011011", 34 => "1001000", 35 => "0010000", 
    36 => "1101000", 37 => "0100101", 38 => "0101011", 39 => "1000110", 
    40 => "0111110", 41 => "1101110", 42 => "0101010", 43 => "1111100", 
    44 => "1001111", 45 => "1111100", 46 => "0010011", 47 => "0010010", 
    48 => "0000011", 49 => "0011000", 50 => "0101000", 51 => "1110100", 
    52 => "1011100", 53 => "1111111", 54 => "1101010", 55 => "0100110", 
    56 => "1101010", 57 => "1101111", 58 => "0101001", 59 => "1101010", 
    60 => "0011011", 61 => "0001011", 62 => "0101110", 63 => "1101111", 
    64 => "0010000", 65 => "1111010", 66 => "1110100", 67 => "0101111", 
    68 => "0000110", 69 => "1011000", 70 => "0011101", 71 => "1101100", 
    72 => "1110011", 73 => "0010101", 74 => "1011010", 75 => "0011101", 
    76 => "0011111", 77 => "0110010", 78 => "0111100", 79 => "1001000", 
    80 => "0100101", 81 => "1101110", 82 => "0101001", 83 => "0101011");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

