-- ==============================================================
-- Generated by Vitis HLS v2025.1.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity lenet_hls_fc_f6_Pipeline_F6_Output_Loop_p_ZL10f6_weights_86_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 8; 
             AddressWidth     : integer := 7; 
             AddressRange    : integer := 84
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of lenet_hls_fc_f6_Pipeline_F6_Output_Loop_p_ZL10f6_weights_86_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "11011111", 1 => "11111000", 2 => "00011001", 3 => "00010110", 
    4 => "11110111", 5 => "11011101", 6 => "11111101", 7 => "11011100", 
    8 => "00100010", 9 => "11011100", 10 => "00111000", 11 => "00001011", 
    12 => "11010001", 13 => "11100110", 14 => "11110011", 15 => "11110011", 
    16 => "00010111", 17 => "11101111", 18 => "00110110", 19 => "11111110", 
    20 => "00100010", 21 => "00011110", 22 => "00001111", 23 => "11011111", 
    24 => "11101110", 25 => "00010101", 26 => "11010111", 27 => "00100000", 
    28 => "00011000", 29 => "11010111", 30 => "11111000", 31 => "00100111", 
    32 => "11000011", 33 => "11110001", 34 => "00000000", 35 => "00010010", 
    36 => "11111011", 37 => "00001010", 38 => "11101111", 39 => "11011101", 
    40 => "11001010", 41 => "00000101", 42 => "00101111", 43 => "11000110", 
    44 => "00000011", 45 => "10110101", 46 => "00100100", 47 => "00100001", 
    48 => "00110111", 49 => "11110100", 50 => "00110111", 51 => "11010110", 
    52 => "11111000", 53 => "11101000", 54 => "11110110", 55 => "11110101", 
    56 => "11011110", 57 => "00110011", 58 => "11001001", 59 => "11101011", 
    60 => "10111110", 61 => "00101101", 62 => "11111000", 63 => "11101010", 
    64 => "11001000", 65 => "00110100", 66 => "11111111", 67 => "11000011", 
    68 => "11100011", 69 => "00101101", 70 => "11000110", 71 => "01010011", 
    72 => "00111011", 73 => "01000000", 74 => "01000001", 75 => "11001111", 
    76 => "00101001", 77 => "11110110", 78 => "11010100", 79 => "00000011", 
    80 => "00100010", 81 => "10111110", 82 => "11001111", 83 => "11011000");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

