-- ==============================================================
-- Generated by Vitis HLS v2025.1.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity lenet_hls_fc_f6_Pipeline_F6_Output_Loop_p_ZL10f6_weights_118_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 8; 
             AddressWidth     : integer := 7; 
             AddressRange    : integer := 84
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of lenet_hls_fc_f6_Pipeline_F6_Output_Loop_p_ZL10f6_weights_118_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00111100", 1 => "00000000", 2 => "10001011", 3 => "11101010", 
    4 => "01000111", 5 => "11111001", 6 => "00010011", 7 => "00000011", 
    8 => "11101011", 9 => "11111011", 10 => "00111101", 11 => "00000010", 
    12 => "00100011", 13 => "00010100", 14 => "11110111", 15 => "11101111", 
    16 => "00110100", 17 => "11001110", 18 => "11001100", 19 => "00101101", 
    20 => "01001101", 21 => "11011001", 22 => "10110010", 23 => "11000011", 
    24 => "01000110", 25 => "00101010", 26 => "00100010", 27 => "11110011", 
    28 => "10100111", 29 => "00000111", 30 => "11110001", 31 => "00111000", 
    32 => "11001111", 33 => "00000100", 34 => "00110111", 35 => "11110110", 
    36 => "11111011", 37 => "00001100", 38 => "00111111", 39 => "11100100", 
    40 => "00100100", 41 => "11110010", 42 => "00110110", 43 => "00100101", 
    44 => "01000001", 45 => "11101011", 46 => "00101110", 47 => "11010010", 
    48 => "00010000", 49 => "00010100", 50 => "00001010", 51 => "11001011", 
    52 => "11011000", 53 => "11111111", 54 => "01000001", 55 => "10110101", 
    56 => "00011011", 57 => "11110101", 58 => "11111001", 59 => "00101110", 
    60 => "11111101", 61 => "00000010", 62 => "11011111", 63 => "11101011", 
    64 => "11011000", 65 => "11101011", 66 => "11111000", 67 => "00011100", 
    68 => "00011101", 69 => "11010001", 70 => "00011001", 71 => "11000001", 
    72 => "00100100", 73 => "11010111", 74 => "00101111", 75 => "11011101", 
    76 => "00100101", 77 => "01101111", 78 => "00001010", 79 => "11011110", 
    80 => "11010101", 81 => "11011011", 82 => "10111101", 83 => "00101100");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

