-- ==============================================================
-- Generated by Vitis HLS v2025.1.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity lenet_hls_fc_f6_Pipeline_F6_Output_Loop_p_ZL10f6_weights_48_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 8; 
             AddressWidth     : integer := 7; 
             AddressRange    : integer := 84
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of lenet_hls_fc_f6_Pipeline_F6_Output_Loop_p_ZL10f6_weights_48_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "11010100", 1 => "00010101", 2 => "00111100", 3 => "00100010", 
    4 => "10111100", 5 => "11100000", 6 => "11110000", 7 => "00011111", 
    8 => "11001001", 9 => "00110000", 10 => "11001111", 11 => "10111000", 
    12 => "01000010", 13 => "11110101", 14 => "10110100", 15 => "00111011", 
    16 => "01001010", 17 => "11100001", 18 => "01100100", 19 => "11100001", 
    20 => "00001011", 21 => "00010100", 22 => "00001111", 23 => "00111011", 
    24 => "10111110", 25 => "11111101", 26 => "00101010", 27 => "11110001", 
    28 => "01010011", 29 => "10001011", 30 => "11100001", 31 => "11000101", 
    32 => "00010011", 33 => "00011110", 34 => "00101011", 35 => "01100101", 
    36 => "11110011", 37 => "00100010", 38 => "10101011", 39 => "00011010", 
    40 => "00101001", 41 => "00001110", 42 => "11100010", 43 => "11100011", 
    44 => "11000001", 45 => "01000110", 46 => "01111111", 47 => "11100011", 
    48 => "00011001", 49 => "11000001", 50 => "00001101", 51 => "11011100", 
    52 => "01100001", 53 => "11100110", 54 => "00001001", 55 => "00010101", 
    56 => "01001110", 57 => "00010110", 58 => "00111000", 59 => "11011110", 
    60 => "01000100", 61 => "11111100", 62 => "01010001", 63 => "11111100", 
    64 => "10100010", 65 => "11110001", 66 => "11110011", 67 => "11110111", 
    68 => "01000010", 69 => "10101110", 70 => "00000111", 71 => "11111111", 
    72 => "11010011", 73 => "11101111", 74 => "11000011", 75 => "00001010", 
    76 => "00000111", 77 => "10011101", 78 => "11110000", 79 => "11100001", 
    80 => "00111011", 81 => "11010100", 82 => "00111110", 83 => "00100100");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

