-- ==============================================================
-- Generated by Vitis HLS v2025.1.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity lenet_hls_fc_f6_Pipeline_F6_Output_Loop_p_ZL10f6_weights_98_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 8; 
             AddressWidth     : integer := 7; 
             AddressRange    : integer := 84
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of lenet_hls_fc_f6_Pipeline_F6_Output_Loop_p_ZL10f6_weights_98_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "11110000", 1 => "11001001", 2 => "11111101", 3 => "11000010", 
    4 => "00000101", 5 => "00110000", 6 => "00111001", 7 => "11100000", 
    8 => "00001111", 9 => "11100111", 10 => "00111001", 11 => "01000010", 
    12 => "01001101", 13 => "00100011", 14 => "10010010", 15 => "00111000", 
    16 => "00111110", 17 => "00011111", 18 => "00010111", 19 => "00110100", 
    20 => "01101111", 21 => "01001101", 22 => "10100000", 23 => "00110001", 
    24 => "11011111", 25 => "00010010", 26 => "00010111", 27 => "00011010", 
    28 => "00010011", 29 => "11100000", 30 => "10001101", 31 => "01000101", 
    32 => "00110111", 33 => "01011010", 34 => "00001010", 35 => "00110011", 
    36 => "11001101", 37 => "11001000", 38 => "00011110", 39 => "00011111", 
    40 => "00011100", 41 => "10011010", 42 => "10110001", 43 => "11001010", 
    44 => "01000001", 45 => "00101100", 46 => "00000010", 47 => "11110011", 
    48 => "10011110", 49 => "01001011", 50 => "00001111", 51 => "00001011", 
    52 => "00110100", 53 => "00100110", 54 => "00000011", 55 => "10101101", 
    56 => "00010100", 57 => "00110100", 58 => "00110001", 59 => "10111011", 
    60 => "11110111", 61 => "11000011", 62 => "01010100", 63 => "10111010", 
    64 => "00111111", 65 => "11110001", 66 => "10101011", 67 => "11000110", 
    68 => "00100101", 69 => "11100011", 70 => "11110100", 71 => "11100011", 
    72 => "11111101", 73 => "11111100", 74 => "01000111", 75 => "00110011", 
    76 => "11110010", 77 => "01010000", 78 => "01010001", 79 => "11110010", 
    80 => "11011011", 81 => "00001110", 82 => "00010011", 83 => "00001010");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

