-- ==============================================================
-- Generated by Vitis HLS v2025.1.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity lenet_hls_fc_f6_Pipeline_F6_Output_Loop_p_ZL10f6_weights_42_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 8; 
             AddressWidth     : integer := 7; 
             AddressRange    : integer := 84
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of lenet_hls_fc_f6_Pipeline_F6_Output_Loop_p_ZL10f6_weights_42_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "11110110", 1 => "11100110", 2 => "11011001", 3 => "01111111", 
    4 => "00111000", 5 => "00000011", 6 => "00010110", 7 => "11111000", 
    8 => "00011010", 9 => "00000011", 10 => "11110001", 11 => "10110010", 
    12 => "11010101", 13 => "00001110", 14 => "00000001", 15 => "11110011", 
    16 => "01011101", 17 => "00000101", 18 => "00110010", 19 => "11110110", 
    20 => "01101000", 21 => "00000111", 22 => "11000000", 23 => "01001101", 
    24 => "10010110", 25 => "00101010", 26 => "11000111", 27 => "11111110", 
    28 => "00001111", 29 => "00101111", 30 => "00010011", 31 => "00001110", 
    32 => "11000101", 33 => "00110110", 34 => "00110111", 35 => "11011010", 
    36 => "01110011", 37 => "11100010", 38 => "11101101", 39 => "00011101", 
    40 => "01000001", 41 => "11011000", 42 => "00010101", 43 => "11110111", 
    44 => "00000000", 45 => "00110110", 46 => "00011110", 47 => "11010111", 
    48 => "11011011", 49 => "00110101", 50 => "11011111", 51 => "11011110", 
    52 => "01111111", 53 => "00101001", 54 => "11110011", 55 => "00110100", 
    56 => "11010110", 57 => "11111011", 58 => "00011010", 59 => "11011010", 
    60 => "00001100", 61 => "00000111", 62 => "01000001", 63 => "11100101", 
    64 => "01000101", 65 => "00100010", 66 => "00010010", 67 => "00000101", 
    68 => "00100011", 69 => "11001111", 70 => "00101101", 71 => "10111001", 
    72 => "11111110", 73 => "10111100", 74 => "11111010", 75 => "00001001", 
    76 => "00000011", 77 => "11001111", 78 => "01000111", 79 => "10101110", 
    80 => "11101101", 81 => "10111010", 82 => "11000111", 83 => "00111100");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

