-- ==============================================================
-- Generated by Vitis HLS v2025.1.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity lenet_hls_fc_f6_Pipeline_F6_Output_Loop_p_ZL10f6_weights_45_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 8; 
             AddressWidth     : integer := 7; 
             AddressRange    : integer := 84
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of lenet_hls_fc_f6_Pipeline_F6_Output_Loop_p_ZL10f6_weights_45_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00010010", 1 => "00001100", 2 => "00010110", 3 => "00001000", 
    4 => "11011010", 5 => "11111001", 6 => "11010101", 7 => "11000101", 
    8 => "00101011", 9 => "11111000", 10 => "11001111", 11 => "11010101", 
    12 => "11001000", 13 => "01000011", 14 => "11110101", 15 => "00010101", 
    16 => "11011011", 17 => "11011000", 18 => "11100110", 19 => "00000101", 
    20 => "00110000", 21 => "00001011", 22 => "11111001", 23 => "00110100", 
    24 => "11001001", 25 => "00010010", 26 => "00001100", 27 => "11101100", 
    28 => "00111111", 29 => "11011011", 30 => "00111000", 31 => "11110101", 
    32 => "00011011", 33 => "11011110", 34 => "11111101", 35 => "00101010", 
    36 => "11111010", 37 => "11101000", 38 => "00000000", 39 => "00101011", 
    40 => "01100010", 41 => "00000111", 42 => "00100011", 43 => "00001110", 
    44 => "11111100", 45 => "11010010", 46 => "11101011", 47 => "11010001", 
    48 => "00001001", 49 => "00001010", 50 => "11100010", 51 => "00110001", 
    52 => "11101001", 53 => "11001011", 54 => "00101011", 55 => "00100011", 
    56 => "11111011", 57 => "11100101", 58 => "11110001", 59 => "01000111", 
    60 => "11010100", 61 => "00110000", 62 => "11111111", 63 => "11101000", 
    64 => "11111000", 65 => "00110100", 66 => "00011110", 67 => "00000100", 
    68 => "00110111", 69 => "00010000", 70 => "11110100", 71 => "00111001", 
    72 => "00001101", 73 => "11100000", 74 => "00001100", 75 => "11100111", 
    76 => "00000001", 77 => "00101010", 78 => "11010010", 79 => "11101000", 
    80 => "00011011", 81 => "11111001", 82 => "00110000", 83 => "11001110");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

