-- ==============================================================
-- Generated by Vitis HLS v2025.1.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity lenet_hls_fc_f6_Pipeline_F6_Output_Loop_p_ZL10f6_weights_92_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 8; 
             AddressWidth     : integer := 7; 
             AddressRange    : integer := 84
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of lenet_hls_fc_f6_Pipeline_F6_Output_Loop_p_ZL10f6_weights_92_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00001101", 1 => "00110101", 2 => "11100010", 3 => "00011000", 
    4 => "11010110", 5 => "11111011", 6 => "00000011", 7 => "11111110", 
    8 => "11111010", 9 => "11100000", 10 => "11110000", 11 => "00001101", 
    12 => "00011101", 13 => "11111001", 14 => "00010101", 15 => "00101101", 
    16 => "00011010", 17 => "11001010", 18 => "00000011", 19 => "00010010", 
    20 => "11001101", 21 => "01001010", 22 => "00011100", 23 => "11101110", 
    24 => "00101110", 25 => "11001111", 26 => "00011110", 27 => "00001000", 
    28 => "00101100", 29 => "11100001", 30 => "11000110", 31 => "00001100", 
    32 => "00001011", 33 => "11110111", 34 => "11100010", 35 => "00110111", 
    36 => "11110110", 37 => "11100111", 38 => "00000011", 39 => "11010001", 
    40 => "00100110", 41 => "00011011", 42 => "11111000", 43 => "10111010", 
    44 => "11100001", 45 => "11010011", 46 => "10111000", 47 => "00011010", 
    48 => "10110110", 49 => "00001010", 50 => "00111110", 51 => "00001001", 
    52 => "00001010", 53 => "11010001", 54 => "11101111", 55 => "11011111", 
    56 => "00110011", 57 => "00001100", 58 => "00000001", 59 => "11110001", 
    60 => "11101011", 61 => "11100101", 62 => "00010101", 63 => "01000001", 
    64 => "00101011", 65 => "00010001", 66 => "11100010", 67 => "11101100", 
    68 => "00111111", 69 => "00001011", 70 => "00001000", 71 => "11100001", 
    72 => "00010111", 73 => "00000010", 74 => "11011110", 75 => "00110000", 
    76 => "00101011", 77 => "00000010", 78 => "00110101", 79 => "11010100", 
    80 => "11001000", 81 => "00110001", 82 => "11101000", 83 => "00000001");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

