-- ==============================================================
-- Generated by Vitis HLS v2025.1.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity lenet_hls_fc_f6_Pipeline_F6_Output_Loop_p_ZL10f6_weights_81_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 8; 
             AddressWidth     : integer := 7; 
             AddressRange    : integer := 84
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of lenet_hls_fc_f6_Pipeline_F6_Output_Loop_p_ZL10f6_weights_81_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00100101", 1 => "00110010", 2 => "00111101", 3 => "11010101", 
    4 => "00100111", 5 => "11100111", 6 => "00000001", 7 => "00110100", 
    8 => "00011010", 9 => "00010001", 10 => "01000110", 11 => "11010101", 
    12 => "00111110", 13 => "11010110", 14 => "00001101", 15 => "01010100", 
    16 => "00101100", 17 => "11010010", 18 => "00101110", 19 => "11101110", 
    20 => "11111000", 21 => "00011001", 22 => "11001011", 23 => "00000010", 
    24 => "00011010", 25 => "11101011", 26 => "00101011", 27 => "11100011", 
    28 => "00101100", 29 => "11011011", 30 => "01000011", 31 => "11101100", 
    32 => "10111001", 33 => "01001101", 34 => "00010100", 35 => "00010100", 
    36 => "10011111", 37 => "11110110", 38 => "00011100", 39 => "00011010", 
    40 => "11000000", 41 => "00110000", 42 => "11000111", 43 => "00100000", 
    44 => "11011000", 45 => "11011101", 46 => "01010000", 47 => "11000000", 
    48 => "00001100", 49 => "11111011", 50 => "00001111", 51 => "00101101", 
    52 => "11110000", 53 => "11001111", 54 => "01000010", 55 => "11010111", 
    56 => "01100000", 57 => "00001011", 58 => "00011100", 59 => "01001110", 
    60 => "00001111", 61 => "00101110", 62 => "11001111", 63 => "00010000", 
    64 => "11010110", 65 => "11010111", 66 => "01010001", 67 => "01010101", 
    68 => "01000100", 69 => "11010001", 70 => "00000111", 71 => "00010100", 
    72 => "11110001", 73 => "00100011", 74 => "00111000", 75 => "00000000", 
    76 => "01000010", 77 => "11011100", 78 => "00011100", 79 => "10101111", 
    80 => "01010101", 81 => "10111111", 82 => "11111011", 83 => "11111111");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

