-- ==============================================================
-- Generated by Vitis HLS v2025.1.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity lenet_hls_fc_f6_Pipeline_F6_Output_Loop_p_ZL10f6_weights_101_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 8; 
             AddressWidth     : integer := 7; 
             AddressRange    : integer := 84
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of lenet_hls_fc_f6_Pipeline_F6_Output_Loop_p_ZL10f6_weights_101_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00100101", 1 => "10100110", 2 => "10010110", 3 => "10011001", 
    4 => "00001101", 5 => "00001010", 6 => "01001100", 7 => "00001111", 
    8 => "11110001", 9 => "00100111", 10 => "00011111", 11 => "01010011", 
    12 => "01001100", 13 => "10110111", 14 => "11001011", 15 => "01011010", 
    16 => "11111011", 17 => "00100011", 18 => "11011000", 19 => "00100001", 
    20 => "00000000", 21 => "00110010", 22 => "11111010", 23 => "11100110", 
    24 => "00101010", 25 => "00000010", 26 => "00000110", 27 => "11001010", 
    28 => "11001001", 29 => "00101001", 30 => "00001101", 31 => "00111001", 
    32 => "00101010", 33 => "01011111", 34 => "00011000", 35 => "11011011", 
    36 => "11001000", 37 => "11100001", 38 => "11110010", 39 => "00000011", 
    40 => "00011110", 41 => "00000001", 42 => "11111110", 43 => "00000110", 
    44 => "01011010", 45 => "11010011", 46 => "00110100", 47 => "00010011", 
    48 => "10011000", 49 => "00010111", 50 => "11010100", 51 => "00101001", 
    52 => "01000101", 53 => "00011000", 54 => "11110001", 55 => "11111101", 
    56 => "01100100", 57 => "00110111", 58 => "11100111", 59 => "10100100", 
    60 => "00000111", 61 => "11110100", 62 => "01000000", 63 => "11100000", 
    64 => "00110001", 65 => "10110111", 66 => "00000100", 67 => "11111100", 
    68 => "11111000", 69 => "11010001", 70 => "00000001", 71 => "11011010", 
    72 => "10111101", 73 => "11001101", 74 => "11001010", 75 => "00010101", 
    76 => "11011110", 77 => "11101011", 78 => "00001101", 79 => "00001001", 
    80 => "11001000", 81 => "11000001", 82 => "11011110", 83 => "01010010");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

