-- ==============================================================
-- Generated by Vitis HLS v2025.1.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity lenet_hls_fc_f6_Pipeline_F6_Output_Loop_p_ZL10f6_weights_73_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 8; 
             AddressWidth     : integer := 7; 
             AddressRange    : integer := 84
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of lenet_hls_fc_f6_Pipeline_F6_Output_Loop_p_ZL10f6_weights_73_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "11011110", 1 => "00000010", 2 => "11110110", 3 => "00111001", 
    4 => "00100100", 5 => "11111100", 6 => "11111100", 7 => "00111000", 
    8 => "00101000", 9 => "01001101", 10 => "00010011", 11 => "00001101", 
    12 => "00101000", 13 => "00011100", 14 => "11000100", 15 => "01000111", 
    16 => "11110001", 17 => "11001001", 18 => "11011100", 19 => "00110010", 
    20 => "00111010", 21 => "00001000", 22 => "00000010", 23 => "11101011", 
    24 => "11110001", 25 => "11101010", 26 => "10111110", 27 => "00000110", 
    28 => "01000011", 29 => "11100100", 30 => "00010100", 31 => "00000001", 
    32 => "11110001", 33 => "11001111", 34 => "11001111", 35 => "01111001", 
    36 => "00001100", 37 => "11111000", 38 => "00000111", 39 => "00011001", 
    40 => "11110111", 41 => "00010001", 42 => "01010001", 43 => "11111001", 
    44 => "00000111", 45 => "11111001", 46 => "11110110", 47 => "11010010", 
    48 => "00110101", 49 => "10110111", 50 => "01011100", 51 => "00011101", 
    52 => "00001111", 53 => "11011111", 54 => "11111000", 55 => "11101000", 
    56 => "11011011", 57 => "11011010", 58 => "00010110", 59 => "01100000", 
    60 => "11111001", 61 => "00001010", 62 => "00001000", 63 => "11110001", 
    64 => "11010010", 65 => "11111101", 66 => "01000101", 67 => "11101101", 
    68 => "11111011", 69 => "00001111", 70 => "11010001", 71 => "11010011", 
    72 => "01001100", 73 => "00000101", 74 => "11101101", 75 => "00011101", 
    76 => "00111000", 77 => "11110011", 78 => "00101011", 79 => "11010000", 
    80 => "11011100", 81 => "11011011", 82 => "11001000", 83 => "01000100");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

