-- ==============================================================
-- Generated by Vitis HLS v2025.1.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity lenet_hls_fc_f6_Pipeline_F6_Output_Loop_p_ZL10f6_weights_44_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 7; 
             AddressWidth     : integer := 7; 
             AddressRange    : integer := 84
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of lenet_hls_fc_f6_Pipeline_F6_Output_Loop_p_ZL10f6_weights_44_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "1010010", 1 => "0101010", 2 => "1010110", 3 => "1011111", 
    4 => "1000100", 5 => "0100111", 6 => "1001010", 7 => "0001000", 
    8 => "1001010", 9 => "1100110", 10 => "1111011", 11 => "1010000", 
    12 => "1011010", 13 => "0110000", 14 => "1011011", 15 => "1010011", 
    16 => "1011101", 17 => "1110101", 18 => "0100100", 19 => "0000111", 
    20 => "1101001", 21 => "0000111", 22 => "1010110", 23 => "0001110", 
    24 => "1011010", 25 => "0101111", 26 => "1001111", 27 => "0000010", 
    28 => "0010010", 29 => "1011101", 30 => "1101011", 31 => "1111110", 
    32 => "1011110", 33 => "0010101", 34 => "1010010", 35 => "0101000", 
    36 => "1000111", 37 => "0001111", 38 => "0001100", 39 => "0111000", 
    40 => "0110101", 41 => "1101000", 42 => "1010101", 43 => "1001010", 
    44 => "0001010", 45 => "1001110", 46 => "1011010", 47 => "1100111", 
    48 => "1110110", 49 => "1111011", 50 => "0100101", 51 => "0100011", 
    52 => "0100100", 53 => "1011101", 54 => "1110010", 55 => "0001010", 
    56 => "1011000", 57 => "1101111", 58 => "1011000", 59 => "0110011", 
    60 => "1111011", 61 => "0011110", 62 => "0010110", 63 => "1111100", 
    64 => "0001010", 65 => "0110100", 66 => "0000111", 67 => "0000111", 
    68 => "0111000", 69 => "0000001", 70 => "1101011", 71 => "1110010", 
    72 => "1100101", 73 => "0010011", 74 => "1101001", 75 => "0100100", 
    76 => "1011111", 77 => "1111110", 78 => "0101100", 79 => "1101010", 
    80 => "1110011", 81 => "0001011", 82 => "1001011", 83 => "0100000");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

