-- ==============================================================
-- Generated by Vitis HLS v2025.1.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity lenet_hls_fc_f6_Pipeline_F6_Output_Loop_p_ZL10f6_weights_80_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 8; 
             AddressWidth     : integer := 7; 
             AddressRange    : integer := 84
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of lenet_hls_fc_f6_Pipeline_F6_Output_Loop_p_ZL10f6_weights_80_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "11001010", 1 => "01000010", 2 => "01001110", 3 => "11111000", 
    4 => "00011010", 5 => "10110101", 6 => "01000011", 7 => "00101111", 
    8 => "11101101", 9 => "11111100", 10 => "01011001", 11 => "00011000", 
    12 => "00101110", 13 => "11011110", 14 => "11100000", 15 => "00011010", 
    16 => "11101100", 17 => "00010100", 18 => "11110101", 19 => "00001010", 
    20 => "11110100", 21 => "00100111", 22 => "00000000", 23 => "11111000", 
    24 => "00110100", 25 => "00100011", 26 => "00001001", 27 => "00001011", 
    28 => "00011111", 29 => "11001011", 30 => "10110010", 31 => "00100001", 
    32 => "11100011", 33 => "00101010", 34 => "01011101", 35 => "00000000", 
    36 => "10100011", 37 => "10111011", 38 => "10110001", 39 => "00000111", 
    40 => "10100000", 41 => "11100010", 42 => "01001001", 43 => "11101100", 
    44 => "11011001", 45 => "00101001", 46 => "00001001", 47 => "10111001", 
    48 => "11101010", 49 => "00010000", 50 => "01011000", 51 => "11110101", 
    52 => "11100000", 53 => "11100001", 54 => "00000100", 55 => "00000001", 
    56 => "00110000", 57 => "11101011", 58 => "10100011", 59 => "11110001", 
    60 => "00011111", 61 => "11111100", 62 => "11101000", 63 => "00100001", 
    64 => "10111011", 65 => "11010011", 66 => "01010111", 67 => "01000110", 
    68 => "01000110", 69 => "00001011", 70 => "11010100", 71 => "00101010", 
    72 => "11010100", 73 => "11111111", 74 => "00110011", 75 => "11001101", 
    76 => "11110011", 77 => "11100000", 78 => "00110000", 79 => "00011111", 
    80 => "00100000", 81 => "11011010", 82 => "01001110", 83 => "00101100");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

