-- ==============================================================
-- Generated by Vitis HLS v2025.1.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity lenet_hls_lenet_hls_Pipeline_S4_Filter_Loop_S4_Row_Loop_S4_Col_Loop is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    p_ZL9c3_output_0_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    p_ZL9c3_output_0_ce0 : OUT STD_LOGIC;
    p_ZL9c3_output_0_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_ZL9c3_output_0_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
    p_ZL9c3_output_0_ce1 : OUT STD_LOGIC;
    p_ZL9c3_output_0_q1 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_ZL9c3_output_1_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    p_ZL9c3_output_1_ce0 : OUT STD_LOGIC;
    p_ZL9c3_output_1_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_ZL9c3_output_1_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
    p_ZL9c3_output_1_ce1 : OUT STD_LOGIC;
    p_ZL9c3_output_1_q1 : IN STD_LOGIC_VECTOR (7 downto 0);
    s4_output_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    s4_output_ce0 : OUT STD_LOGIC;
    s4_output_we0 : OUT STD_LOGIC;
    s4_output_d0 : OUT STD_LOGIC_VECTOR (5 downto 0) );
end;


architecture behav of lenet_hls_lenet_hls_Pipeline_S4_Filter_Loop_S4_Row_Loop_S4_Col_Loop is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    constant ap_const_lv9_190 : STD_LOGIC_VECTOR (8 downto 0) := "110010000";
    constant ap_const_lv9_1 : STD_LOGIC_VECTOR (8 downto 0) := "000000001";
    constant ap_const_lv6_19 : STD_LOGIC_VECTOR (5 downto 0) := "011001";
    constant ap_const_lv6_1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_const_lv3_5 : STD_LOGIC_VECTOR (2 downto 0) := "101";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln66_fu_187_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln67_fu_202_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln67_reg_628 : STD_LOGIC_VECTOR (0 downto 0);
    signal c_1_mid2_fu_289_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal c_1_mid2_reg_636 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln76_fu_361_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln76_reg_642 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln76_fu_367_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln76_reg_647 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln73_2_fu_383_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln73_2_reg_652 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln73_fu_389_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln73_reg_657 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln73_3_fu_405_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln73_3_reg_662 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln73_1_fu_411_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln73_1_reg_667 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln76_1_fu_514_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln76_1_reg_692 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln76_1_reg_692_pp0_iter3_reg : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln76_1_reg_692_pp0_iter4_reg : STD_LOGIC_VECTOR (8 downto 0);
    signal sum_reg_697 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_ZL9c3_output_0_load_reg_702 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln73_1_fu_520_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln73_1_reg_707 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_5_reg_712 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_5_cast_reg_717 : STD_LOGIC_VECTOR (5 downto 0);
    signal zext_ln_reg_722 : STD_LOGIC_VECTOR (5 downto 0);
    signal zext_ln73_7_fu_496_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln73_8_fu_508_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln76_3_fu_573_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal c_fu_76 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    signal add_ln68_fu_415_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal r_fu_80 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    signal select_ln67_fu_297_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal indvar_flatten22_fu_84 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    signal select_ln67_1_fu_214_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_sig_allocacmp_indvar_flatten22_load : STD_LOGIC_VECTOR (5 downto 0);
    signal f_fu_88 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    signal select_ln66_1_fu_271_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal indvar_flatten35_fu_92 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    signal add_ln66_1_fu_193_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_sig_allocacmp_indvar_flatten35_load : STD_LOGIC_VECTOR (8 downto 0);
    signal p_ZL9c3_output_0_ce1_local : STD_LOGIC;
    signal p_ZL9c3_output_0_ce0_local : STD_LOGIC;
    signal p_ZL9c3_output_1_ce1_local : STD_LOGIC;
    signal p_ZL9c3_output_1_ce0_local : STD_LOGIC;
    signal s4_output_we0_local : STD_LOGIC;
    signal select_ln76_fu_582_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal s4_output_ce0_local : STD_LOGIC;
    signal add_ln67_1_fu_208_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal icmp_ln68_fu_259_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln66_fu_254_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln66_fu_241_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal select_ln66_fu_247_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal and_ln66_fu_265_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_fu_284_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln67_fu_278_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_fu_309_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_1_fu_321_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal zext_ln73_1_fu_317_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln73_2_fu_329_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_2_fu_339_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal zext_ln76_1_fu_347_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln73_fu_305_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln76_2_fu_351_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln76_2_fu_357_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_3_fu_371_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln73_6_fu_333_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln73_3_fu_379_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_4_fu_393_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln73_4_fu_401_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal p_shl1_fu_439_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln76_cast_fu_436_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal p_shl2_fu_455_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln73_2_cast_fu_452_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_shl_fu_471_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln68_fu_468_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal mul_ln73_1_fu_462_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln73_6_fu_487_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln73_4_fu_490_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln68_1_fu_478_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln73_5_fu_502_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal mul_ln76_1_fu_446_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln73_5_fu_484_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln73_fu_526_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal sum_1_fu_530_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal sext_ln76_fu_535_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal sub_ln76_fu_547_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal sub_ln76_1_fu_577_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component lenet_hls_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component lenet_hls_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready_pp0_iter4_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    c_fu_76_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    c_fu_76 <= ap_const_lv3_0;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    c_fu_76 <= add_ln68_fu_415_p2;
                end if;
            end if; 
        end if;
    end process;

    f_fu_88_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    f_fu_88 <= ap_const_lv5_0;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    f_fu_88 <= select_ln66_1_fu_271_p3;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten22_fu_84_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln66_fu_187_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    indvar_flatten22_fu_84 <= select_ln67_1_fu_214_p3;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten22_fu_84 <= ap_const_lv6_0;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten35_fu_92_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln66_fu_187_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    indvar_flatten35_fu_92 <= add_ln66_1_fu_193_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten35_fu_92 <= ap_const_lv9_0;
                end if;
            end if; 
        end if;
    end process;

    r_fu_80_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    r_fu_80 <= ap_const_lv3_0;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    r_fu_80 <= select_ln67_fu_297_p3;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                add_ln73_1_reg_707 <= add_ln73_1_fu_520_p2;
                add_ln76_1_reg_692 <= add_ln76_1_fu_514_p2;
                add_ln76_1_reg_692_pp0_iter3_reg <= add_ln76_1_reg_692;
                add_ln76_1_reg_692_pp0_iter4_reg <= add_ln76_1_reg_692_pp0_iter3_reg;
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                tmp_5_cast_reg_717 <= sub_ln76_fu_547_p2(7 downto 2);
                tmp_5_reg_712 <= sum_1_fu_530_p2(7 downto 7);
                zext_ln_reg_722 <= sum_1_fu_530_p2(7 downto 2);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                    add_ln73_2_reg_652(8 downto 1) <= add_ln73_2_fu_383_p2(8 downto 1);
                    add_ln73_3_reg_662(8 downto 1) <= add_ln73_3_fu_405_p2(8 downto 1);
                add_ln76_reg_642 <= add_ln76_fu_361_p2;
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                c_1_mid2_reg_636 <= c_1_mid2_fu_289_p3;
                icmp_ln67_reg_628 <= icmp_ln67_fu_202_p2;
                    trunc_ln73_1_reg_667(7 downto 1) <= trunc_ln73_1_fu_411_p1(7 downto 1);
                    trunc_ln73_reg_657(7 downto 1) <= trunc_ln73_fu_389_p1(7 downto 1);
                trunc_ln76_reg_647 <= trunc_ln76_fu_367_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then
                p_ZL9c3_output_0_load_reg_702 <= p_ZL9c3_output_0_q0;
                sum_reg_697 <= p_ZL9c3_output_0_q1;
            end if;
        end if;
    end process;
    add_ln73_2_reg_652(0) <= '0';
    trunc_ln73_reg_657(0) <= '0';
    add_ln73_3_reg_662(0) <= '1';
    trunc_ln73_1_reg_667(0) <= '1';

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln66_1_fu_193_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten35_load) + unsigned(ap_const_lv9_1));
    add_ln66_fu_241_p2 <= std_logic_vector(unsigned(f_fu_88) + unsigned(ap_const_lv5_1));
    add_ln67_1_fu_208_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten22_load) + unsigned(ap_const_lv6_1));
    add_ln67_fu_278_p2 <= std_logic_vector(unsigned(select_ln66_fu_247_p3) + unsigned(ap_const_lv3_1));
    add_ln68_1_fu_478_p2 <= std_logic_vector(unsigned(p_shl_fu_471_p3) + unsigned(zext_ln68_fu_468_p1));
    add_ln68_fu_415_p2 <= std_logic_vector(unsigned(c_1_mid2_fu_289_p3) + unsigned(ap_const_lv3_1));
    add_ln73_1_fu_520_p2 <= std_logic_vector(unsigned(p_ZL9c3_output_1_q1) + unsigned(p_ZL9c3_output_1_q0));
    add_ln73_2_cast_fu_452_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln73_2_reg_652),10));
    add_ln73_2_fu_383_p2 <= std_logic_vector(unsigned(add_ln73_6_fu_333_p2) + unsigned(zext_ln73_3_fu_379_p1));
    add_ln73_3_fu_405_p2 <= std_logic_vector(unsigned(add_ln73_6_fu_333_p2) + unsigned(zext_ln73_4_fu_401_p1));
    add_ln73_4_fu_490_p2 <= std_logic_vector(unsigned(mul_ln73_1_fu_462_p2) + unsigned(zext_ln73_6_fu_487_p1));
    add_ln73_5_fu_502_p2 <= std_logic_vector(unsigned(add_ln68_1_fu_478_p2) + unsigned(zext_ln73_6_fu_487_p1));
    add_ln73_6_fu_333_p2 <= std_logic_vector(unsigned(zext_ln73_1_fu_317_p1) + unsigned(zext_ln73_2_fu_329_p1));
    add_ln73_fu_526_p2 <= std_logic_vector(unsigned(sum_reg_697) + unsigned(p_ZL9c3_output_0_load_reg_702));
    add_ln76_1_fu_514_p2 <= std_logic_vector(unsigned(mul_ln76_1_fu_446_p2) + unsigned(zext_ln73_5_fu_484_p1));
    add_ln76_2_fu_351_p2 <= std_logic_vector(unsigned(zext_ln76_1_fu_347_p1) + unsigned(zext_ln73_fu_305_p1));
    add_ln76_cast_fu_436_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln76_reg_642),9));
    add_ln76_fu_361_p2 <= std_logic_vector(unsigned(add_ln76_2_fu_351_p2) + unsigned(zext_ln76_2_fu_357_p1));
    and_ln66_fu_265_p2 <= (xor_ln66_fu_254_p2 and icmp_ln68_fu_259_p2);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln66_fu_187_p2)
    begin
        if (((icmp_ln66_fu_187_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter4_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter4_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5)
    begin
        if (((ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten22_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, indvar_flatten22_fu_84)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_indvar_flatten22_load <= ap_const_lv6_0;
        else 
            ap_sig_allocacmp_indvar_flatten22_load <= indvar_flatten22_fu_84;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten35_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, indvar_flatten35_fu_92)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_indvar_flatten35_load <= ap_const_lv9_0;
        else 
            ap_sig_allocacmp_indvar_flatten35_load <= indvar_flatten35_fu_92;
        end if; 
    end process;

    c_1_mid2_fu_289_p3 <= 
        ap_const_lv3_0 when (empty_fu_284_p2(0) = '1') else 
        c_fu_76;
    empty_fu_284_p2 <= (icmp_ln67_reg_628 or and_ln66_fu_265_p2);
    icmp_ln66_fu_187_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten35_load = ap_const_lv9_190) else "0";
    icmp_ln67_fu_202_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten22_load = ap_const_lv6_19) else "0";
    icmp_ln68_fu_259_p2 <= "1" when (c_fu_76 = ap_const_lv3_5) else "0";
    mul_ln73_1_fu_462_p2 <= std_logic_vector(unsigned(p_shl2_fu_455_p3) + unsigned(add_ln73_2_cast_fu_452_p1));
    mul_ln76_1_fu_446_p2 <= std_logic_vector(unsigned(p_shl1_fu_439_p3) + unsigned(add_ln76_cast_fu_436_p1));
    p_ZL9c3_output_0_address0 <= zext_ln73_8_fu_508_p1(10 - 1 downto 0);
    p_ZL9c3_output_0_address1 <= zext_ln73_7_fu_496_p1(10 - 1 downto 0);
    p_ZL9c3_output_0_ce0 <= p_ZL9c3_output_0_ce0_local;

    p_ZL9c3_output_0_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            p_ZL9c3_output_0_ce0_local <= ap_const_logic_1;
        else 
            p_ZL9c3_output_0_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL9c3_output_0_ce1 <= p_ZL9c3_output_0_ce1_local;

    p_ZL9c3_output_0_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            p_ZL9c3_output_0_ce1_local <= ap_const_logic_1;
        else 
            p_ZL9c3_output_0_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL9c3_output_1_address0 <= zext_ln73_8_fu_508_p1(10 - 1 downto 0);
    p_ZL9c3_output_1_address1 <= zext_ln73_7_fu_496_p1(10 - 1 downto 0);
    p_ZL9c3_output_1_ce0 <= p_ZL9c3_output_1_ce0_local;

    p_ZL9c3_output_1_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            p_ZL9c3_output_1_ce0_local <= ap_const_logic_1;
        else 
            p_ZL9c3_output_1_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL9c3_output_1_ce1 <= p_ZL9c3_output_1_ce1_local;

    p_ZL9c3_output_1_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            p_ZL9c3_output_1_ce1_local <= ap_const_logic_1;
        else 
            p_ZL9c3_output_1_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    p_shl1_fu_439_p3 <= (trunc_ln76_reg_647 & ap_const_lv2_0);
    p_shl2_fu_455_p3 <= (trunc_ln73_reg_657 & ap_const_lv2_0);
    p_shl_fu_471_p3 <= (trunc_ln73_1_reg_667 & ap_const_lv2_0);
    s4_output_address0 <= zext_ln76_3_fu_573_p1(9 - 1 downto 0);
    s4_output_ce0 <= s4_output_ce0_local;

    s4_output_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter5, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1))) then 
            s4_output_ce0_local <= ap_const_logic_1;
        else 
            s4_output_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    s4_output_d0 <= select_ln76_fu_582_p3;
    s4_output_we0 <= s4_output_we0_local;

    s4_output_we0_local_assign_proc : process(ap_enable_reg_pp0_iter5, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1))) then 
            s4_output_we0_local <= ap_const_logic_1;
        else 
            s4_output_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    select_ln66_1_fu_271_p3 <= 
        add_ln66_fu_241_p2 when (icmp_ln67_reg_628(0) = '1') else 
        f_fu_88;
    select_ln66_fu_247_p3 <= 
        ap_const_lv3_0 when (icmp_ln67_reg_628(0) = '1') else 
        r_fu_80;
    select_ln67_1_fu_214_p3 <= 
        ap_const_lv6_1 when (icmp_ln67_fu_202_p2(0) = '1') else 
        add_ln67_1_fu_208_p2;
    select_ln67_fu_297_p3 <= 
        add_ln67_fu_278_p2 when (and_ln66_fu_265_p2(0) = '1') else 
        select_ln66_fu_247_p3;
    select_ln76_fu_582_p3 <= 
        sub_ln76_1_fu_577_p2 when (tmp_5_reg_712(0) = '1') else 
        zext_ln_reg_722;
        sext_ln76_fu_535_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sum_1_fu_530_p2),9));

    sub_ln76_1_fu_577_p2 <= std_logic_vector(unsigned(ap_const_lv6_0) - unsigned(tmp_5_cast_reg_717));
    sub_ln76_fu_547_p2 <= std_logic_vector(unsigned(ap_const_lv9_0) - unsigned(sext_ln76_fu_535_p1));
    sum_1_fu_530_p2 <= std_logic_vector(unsigned(add_ln73_1_reg_707) + unsigned(add_ln73_fu_526_p2));
    tmp_1_fu_321_p3 <= (select_ln66_1_fu_271_p3 & ap_const_lv1_0);
    tmp_2_fu_339_p3 <= (select_ln66_1_fu_271_p3 & ap_const_lv2_0);
    tmp_3_fu_371_p3 <= (select_ln67_fu_297_p3 & ap_const_lv1_0);
    tmp_4_fu_393_p3 <= (select_ln67_fu_297_p3 & ap_const_lv1_1);
    tmp_fu_309_p3 <= (select_ln66_1_fu_271_p3 & ap_const_lv3_0);
    trunc_ln73_1_fu_411_p1 <= add_ln73_3_fu_405_p2(8 - 1 downto 0);
    trunc_ln73_fu_389_p1 <= add_ln73_2_fu_383_p2(8 - 1 downto 0);
    trunc_ln76_fu_367_p1 <= add_ln76_fu_361_p2(7 - 1 downto 0);
    xor_ln66_fu_254_p2 <= (icmp_ln67_reg_628 xor ap_const_lv1_1);
    zext_ln68_fu_468_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln73_3_reg_662),10));
    zext_ln73_1_fu_317_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_fu_309_p3),9));
    zext_ln73_2_fu_329_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_1_fu_321_p3),9));
    zext_ln73_3_fu_379_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_3_fu_371_p3),9));
    zext_ln73_4_fu_401_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_4_fu_393_p3),9));
    zext_ln73_5_fu_484_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(c_1_mid2_reg_636),9));
    zext_ln73_6_fu_487_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(c_1_mid2_reg_636),10));
    zext_ln73_7_fu_496_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln73_4_fu_490_p2),64));
    zext_ln73_8_fu_508_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln73_5_fu_502_p2),64));
    zext_ln73_fu_305_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln66_1_fu_271_p3),8));
    zext_ln76_1_fu_347_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_2_fu_339_p3),8));
    zext_ln76_2_fu_357_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln67_fu_297_p3),8));
    zext_ln76_3_fu_573_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln76_1_reg_692_pp0_iter4_reg),64));
end behav;
