-- ==============================================================
-- Generated by Vitis HLS v2025.1.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity lenet_hls_fc_f6_Pipeline_F6_Output_Loop_p_ZL10f6_weights_64_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 8; 
             AddressWidth     : integer := 7; 
             AddressRange    : integer := 84
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of lenet_hls_fc_f6_Pipeline_F6_Output_Loop_p_ZL10f6_weights_64_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00011010", 1 => "00000100", 2 => "00101010", 3 => "00010000", 
    4 => "00100001", 5 => "11110001", 6 => "01100000", 7 => "11000101", 
    8 => "11010100", 9 => "00110000", 10 => "01010100", 11 => "11101010", 
    12 => "01010010", 13 => "00001100", 14 => "10111010", 15 => "11011111", 
    16 => "00011011", 17 => "00100000", 18 => "00001011", 19 => "10110111", 
    20 => "01010100", 21 => "01011000", 22 => "00000101", 23 => "11001101", 
    24 => "11011010", 25 => "00000011", 26 => "11110111", 27 => "00111010", 
    28 => "00111100", 29 => "11010010", 30 => "00101111", 31 => "11011001", 
    32 => "00101101", 33 => "11111010", 34 => "11110111", 35 => "00111011", 
    36 => "11001111", 37 => "00001110", 38 => "11000110", 39 => "01000001", 
    40 => "10111011", 41 => "11011111", 42 => "11101111", 43 => "00100110", 
    44 => "11101011", 45 => "11110001", 46 => "01001001", 47 => "00010000", 
    48 => "00100100", 49 => "00100110", 50 => "00100001", 51 => "11001010", 
    52 => "00100011", 53 => "00011000", 54 => "11111111", 55 => "11010100", 
    56 => "00010100", 57 => "00010010", 58 => "11110011", 59 => "11111100", 
    60 => "00100100", 61 => "01101001", 62 => "00011111", 63 => "00110001", 
    64 => "11101001", 65 => "10101100", 66 => "11001101", 67 => "11110101", 
    68 => "00110010", 69 => "10111100", 70 => "11101000", 71 => "11100100", 
    72 => "11011100", 73 => "11000011", 74 => "11111000", 75 => "11001101", 
    76 => "00010110", 77 => "11011000", 78 => "01011011", 79 => "11100000", 
    80 => "01110001", 81 => "00100000", 82 => "00000110", 83 => "01001001");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

