-- ==============================================================
-- Generated by Vitis HLS v2025.1.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity lenet_hls_fc_f6_Pipeline_F6_Output_Loop_p_ZL10f6_weights_41_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 8; 
             AddressWidth     : integer := 7; 
             AddressRange    : integer := 84
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of lenet_hls_fc_f6_Pipeline_F6_Output_Loop_p_ZL10f6_weights_41_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "11100011", 1 => "11101010", 2 => "11110101", 3 => "00000101", 
    4 => "11100101", 5 => "00000111", 6 => "00001010", 7 => "00000000", 
    8 => "11001010", 9 => "00100100", 10 => "00010111", 11 => "00000110", 
    12 => "00100110", 13 => "01000001", 14 => "11101000", 15 => "00111011", 
    16 => "00101010", 17 => "00001011", 18 => "01000100", 19 => "11100110", 
    20 => "11010010", 21 => "00000101", 22 => "00011010", 23 => "11010011", 
    24 => "00101001", 25 => "00011100", 26 => "00100001", 27 => "00101100", 
    28 => "11110101", 29 => "00001100", 30 => "00010111", 31 => "00010011", 
    32 => "11010001", 33 => "00100101", 34 => "11100011", 35 => "00011100", 
    36 => "00010010", 37 => "11010001", 38 => "11011101", 39 => "11001111", 
    40 => "00010111", 41 => "11100100", 42 => "11011111", 43 => "00001110", 
    44 => "00000101", 45 => "00100010", 46 => "11101100", 47 => "01000001", 
    48 => "11100110", 49 => "00010000", 50 => "11011101", 51 => "11111100", 
    52 => "00011000", 53 => "00110100", 54 => "00010101", 55 => "11101101", 
    56 => "00011100", 57 => "11011001", 58 => "00110110", 59 => "11101001", 
    60 => "00111100", 61 => "11010010", 62 => "00110010", 63 => "00100011", 
    64 => "00110100", 65 => "11011001", 66 => "11011111", 67 => "00000011", 
    68 => "11101110", 69 => "11111000", 70 => "11110001", 71 => "11101011", 
    72 => "00110001", 73 => "00110100", 74 => "00001101", 75 => "11011110", 
    76 => "11010110", 77 => "00011001", 78 => "00100000", 79 => "11100100", 
    80 => "00000110", 81 => "11111101", 82 => "11000100", 83 => "00001000");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

