-- ==============================================================
-- Generated by Vitis HLS v2025.1.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity lenet_hls_fc_f6_Pipeline_F6_Output_Loop_p_ZL10f6_weights_104_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 8; 
             AddressWidth     : integer := 7; 
             AddressRange    : integer := 84
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of lenet_hls_fc_f6_Pipeline_F6_Output_Loop_p_ZL10f6_weights_104_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "10111101", 1 => "00100011", 2 => "00010011", 3 => "11110110", 
    4 => "00110010", 5 => "00001110", 6 => "00010111", 7 => "11100000", 
    8 => "00101000", 9 => "11111100", 10 => "00001000", 11 => "00000110", 
    12 => "00100100", 13 => "01010011", 14 => "00110011", 15 => "11101010", 
    16 => "00000110", 17 => "11011111", 18 => "00001011", 19 => "11010101", 
    20 => "11010000", 21 => "11010100", 22 => "00001011", 23 => "00101000", 
    24 => "11100111", 25 => "00000100", 26 => "11000000", 27 => "00110101", 
    28 => "00010000", 29 => "00101010", 30 => "00100100", 31 => "11010000", 
    32 => "00101100", 33 => "11100010", 34 => "10110001", 35 => "01000111", 
    36 => "00101001", 37 => "00110011", 38 => "00011101", 39 => "11111110", 
    40 => "00011001", 41 => "00111100", 42 => "01000110", 43 => "11100011", 
    44 => "11101010", 45 => "11010000", 46 => "00000000", 47 => "11100000", 
    48 => "11110101", 49 => "00010100", 50 => "11100100", 51 => "00101110", 
    52 => "00010010", 53 => "11001100", 54 => "00110110", 55 => "00111101", 
    56 => "11010000", 57 => "10100100", 58 => "11001110", 59 => "11110011", 
    60 => "10101101", 61 => "11101100", 62 => "11010111", 63 => "11110101", 
    64 => "00110111", 65 => "00011111", 66 => "00110011", 67 => "11111100", 
    68 => "11100110", 69 => "00011011", 70 => "00110000", 71 => "00001010", 
    72 => "00010101", 73 => "11100011", 74 => "11001101", 75 => "11000111", 
    76 => "00000100", 77 => "11110101", 78 => "11100100", 79 => "00101101", 
    80 => "11000100", 81 => "11111000", 82 => "10111000", 83 => "00110100");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

