-- ==============================================================
-- Generated by Vitis HLS v2025.1.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity lenet_hls_fc_f6_Pipeline_F6_Output_Loop_p_ZL10f6_weights_54_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 8; 
             AddressWidth     : integer := 7; 
             AddressRange    : integer := 84
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of lenet_hls_fc_f6_Pipeline_F6_Output_Loop_p_ZL10f6_weights_54_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "11010010", 1 => "11111010", 2 => "11100011", 3 => "00001000", 
    4 => "00100111", 5 => "11110110", 6 => "10110100", 7 => "00111101", 
    8 => "11101101", 9 => "11111000", 10 => "11100100", 11 => "11111001", 
    12 => "10011011", 13 => "00001110", 14 => "01001101", 15 => "01000010", 
    16 => "00101010", 17 => "11001001", 18 => "11110001", 19 => "00011000", 
    20 => "00011000", 21 => "00110000", 22 => "11100101", 23 => "00011100", 
    24 => "11101010", 25 => "11000001", 26 => "11010110", 27 => "00010000", 
    28 => "00000110", 29 => "00001101", 30 => "00100110", 31 => "10111101", 
    32 => "11110001", 33 => "10011001", 34 => "00000101", 35 => "10111111", 
    36 => "01001010", 37 => "00000101", 38 => "11001111", 39 => "00001101", 
    40 => "01100011", 41 => "00011100", 42 => "11100011", 43 => "00001011", 
    44 => "10101001", 45 => "00010111", 46 => "11111101", 47 => "11101101", 
    48 => "11100111", 49 => "10010001", 50 => "00111100", 51 => "11100000", 
    52 => "00111101", 53 => "11101111", 54 => "01111111", 55 => "01100001", 
    56 => "00001100", 57 => "11110100", 58 => "01011101", 59 => "11111100", 
    60 => "10101000", 61 => "00011101", 62 => "10101010", 63 => "11111111", 
    64 => "00100011", 65 => "00111100", 66 => "00111001", 67 => "01001111", 
    68 => "00100111", 69 => "00100101", 70 => "01000000", 71 => "00111001", 
    72 => "01000000", 73 => "11111101", 74 => "11011000", 75 => "11111011", 
    76 => "01010011", 77 => "10110101", 78 => "00101010", 79 => "11100111", 
    80 => "00001101", 81 => "11101100", 82 => "00011000", 83 => "00001100");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

