-- ==============================================================
-- Generated by Vitis HLS v2025.1.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity lenet_hls_fc_f6_Pipeline_F6_Output_Loop_p_ZL10f6_weights_91_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 8; 
             AddressWidth     : integer := 7; 
             AddressRange    : integer := 84
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of lenet_hls_fc_f6_Pipeline_F6_Output_Loop_p_ZL10f6_weights_91_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00010110", 1 => "00111010", 2 => "00100000", 3 => "11000001", 
    4 => "00110011", 5 => "11011000", 6 => "01001011", 7 => "01000101", 
    8 => "11111111", 9 => "11010011", 10 => "01101100", 11 => "00001100", 
    12 => "01010111", 13 => "00111100", 14 => "11111000", 15 => "11110110", 
    16 => "00100000", 17 => "00011100", 18 => "11001100", 19 => "00101100", 
    20 => "00101110", 21 => "00010011", 22 => "00101011", 23 => "10100010", 
    24 => "00000000", 25 => "00011111", 26 => "11001011", 27 => "00010001", 
    28 => "10011010", 29 => "01001001", 30 => "01000001", 31 => "00110101", 
    32 => "00000000", 33 => "11100001", 34 => "11011111", 35 => "11000011", 
    36 => "10001111", 37 => "00011000", 38 => "00011110", 39 => "11110010", 
    40 => "10100011", 41 => "00001001", 42 => "11010100", 43 => "11001110", 
    44 => "00111111", 45 => "11101111", 46 => "01011110", 47 => "11010010", 
    48 => "00101000", 49 => "01011010", 50 => "00110101", 51 => "00011101", 
    52 => "00000110", 53 => "00111000", 54 => "00001110", 55 => "10110011", 
    56 => "00110111", 57 => "00101000", 58 => "11011011", 59 => "11010000", 
    60 => "11110111", 61 => "01001100", 62 => "00101111", 63 => "11010000", 
    64 => "11100010", 65 => "10101010", 66 => "11101111", 67 => "00101001", 
    68 => "11010000", 69 => "11011101", 70 => "11000001", 71 => "11111011", 
    72 => "00000110", 73 => "11111100", 74 => "11010110", 75 => "00101000", 
    76 => "00011111", 77 => "01100110", 78 => "00010100", 79 => "00111010", 
    80 => "11011001", 81 => "00100100", 82 => "00110111", 83 => "00111010");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

