-- ==============================================================
-- Generated by Vitis HLS v2025.1.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity lenet_hls_fc_f6_Pipeline_F6_Output_Loop_p_ZL10f6_weights_20_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 8; 
             AddressWidth     : integer := 7; 
             AddressRange    : integer := 84
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of lenet_hls_fc_f6_Pipeline_F6_Output_Loop_p_ZL10f6_weights_20_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00011011", 1 => "11100010", 2 => "00110100", 3 => "11110101", 
    4 => "00011100", 5 => "00110010", 6 => "11110110", 7 => "00010101", 
    8 => "11101101", 9 => "00110111", 10 => "11010110", 11 => "00011110", 
    12 => "00000000", 13 => "00101010", 14 => "11010000", 15 => "00000100", 
    16 => "11110000", 17 => "11000111", 18 => "11011011", 19 => "11101111", 
    20 => "00111010", 21 => "00101011", 22 => "11100101", 23 => "00010110", 
    24 => "11100101", 25 => "00011011", 26 => "00100010", 27 => "00011011", 
    28 => "00100100", 29 => "11110100", 30 => "00010100", 31 => "00101101", 
    32 => "00110111", 33 => "11011011", 34 => "00101001", 35 => "11000111", 
    36 => "11111010", 37 => "00010110", 38 => "11011100", 39 => "11100100", 
    40 => "00101010", 41 => "00100010", 42 => "11111100", 43 => "00111010", 
    44 => "00100101", 45 => "11000110", 46 => "11110001", 47 => "11110111", 
    48 => "00011111", 49 => "00011010", 50 => "00110101", 51 => "00001010", 
    52 => "00010011", 53 => "11000101", 54 => "00011000", 55 => "11010010", 
    56 => "11010101", 57 => "11111000", 58 => "00000110", 59 => "11110010", 
    60 => "00110110", 61 => "00110011", 62 => "11010001", 63 => "11101110", 
    64 => "11101111", 65 => "11100001", 66 => "11100010", 67 => "11011110", 
    68 => "01000010", 69 => "00100111", 70 => "11001001", 71 => "00010011", 
    72 => "11101100", 73 => "00001001", 74 => "11011011", 75 => "11100110", 
    76 => "11110101", 77 => "00110100", 78 => "00101111", 79 => "11000110", 
    80 => "00110111", 81 => "11110011", 82 => "00011000", 83 => "11101100");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

