-- ==============================================================
-- Generated by Vitis HLS v2025.1.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity lenet_hls_fc_f6_Pipeline_F6_Output_Loop_p_ZL10f6_weights_4_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 8; 
             AddressWidth     : integer := 7; 
             AddressRange    : integer := 84
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of lenet_hls_fc_f6_Pipeline_F6_Output_Loop_p_ZL10f6_weights_4_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00000101", 1 => "11111110", 2 => "00111001", 3 => "00111011", 
    4 => "01001011", 5 => "00100000", 6 => "00101110", 7 => "11010100", 
    8 => "00000100", 9 => "11011000", 10 => "11001100", 11 => "00000000", 
    12 => "00000000", 13 => "00011111", 14 => "01010101", 15 => "11101001", 
    16 => "11010011", 17 => "00001110", 18 => "00000101", 19 => "11010110", 
    20 => "00001110", 21 => "11111000", 22 => "00100011", 23 => "00110011", 
    24 => "11101001", 25 => "00001011", 26 => "00010110", 27 => "00000011", 
    28 => "00111001", 29 => "00001011", 30 => "00111010", 31 => "11011001", 
    32 => "11000001", 33 => "00000101", 34 => "11111011", 35 => "10111101", 
    36 => "00110011", 37 => "00011110", 38 => "11101011", 39 => "01100011", 
    40 => "11011001", 41 => "00000010", 42 => "00011010", 43 => "00101111", 
    44 => "11100100", 45 => "10110111", 46 => "00011010", 47 => "00100100", 
    48 => "00010101", 49 => "11010010", 50 => "11100011", 51 => "11100011", 
    52 => "11111000", 53 => "00000110", 54 => "00101100", 55 => "00011100", 
    56 => "11010000", 57 => "00111000", 58 => "11111010", 59 => "11101110", 
    60 => "11101111", 61 => "00010101", 62 => "00010111", 63 => "00010100", 
    64 => "11010010", 65 => "11001010", 66 => "00001010", 67 => "01000010", 
    68 => "10110010", 69 => "01001000", 70 => "00000100", 71 => "00001100", 
    72 => "11100110", 73 => "11011001", 74 => "00011111", 75 => "00110001", 
    76 => "11100011", 77 => "11111010", 78 => "00101001", 79 => "00101101", 
    80 => "11101011", 81 => "11110111", 82 => "11101100", 83 => "11101100");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

