-- ==============================================================
-- Generated by Vitis HLS v2025.1.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity lenet_hls_fc_f6_Pipeline_F6_Output_Loop_p_ZL10f6_weights_21_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 8; 
             AddressWidth     : integer := 7; 
             AddressRange    : integer := 84
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of lenet_hls_fc_f6_Pipeline_F6_Output_Loop_p_ZL10f6_weights_21_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "11011111", 1 => "11111000", 2 => "11011010", 3 => "11001111", 
    4 => "00100100", 5 => "00100010", 6 => "00000111", 7 => "01000110", 
    8 => "11001100", 9 => "00110010", 10 => "11000110", 11 => "01000110", 
    12 => "11111111", 13 => "01001011", 14 => "00010011", 15 => "11100101", 
    16 => "10011111", 17 => "00101110", 18 => "11001110", 19 => "10101010", 
    20 => "10011010", 21 => "11111100", 22 => "01010101", 23 => "00011101", 
    24 => "10101111", 25 => "00011111", 26 => "11011111", 27 => "11101010", 
    28 => "11011100", 29 => "11110011", 30 => "00011100", 31 => "00110000", 
    32 => "00001110", 33 => "10110101", 34 => "11111110", 35 => "00000101", 
    36 => "11011101", 37 => "00110011", 38 => "11110010", 39 => "00110001", 
    40 => "00100001", 41 => "01001101", 42 => "11100110", 43 => "11110011", 
    44 => "00101101", 45 => "00000101", 46 => "11110111", 47 => "11101000", 
    48 => "11110110", 49 => "00110011", 50 => "01100000", 51 => "00101001", 
    52 => "00001110", 53 => "11010110", 54 => "00000010", 55 => "00001000", 
    56 => "11111110", 57 => "11110101", 58 => "11111101", 59 => "11011111", 
    60 => "11100101", 61 => "11111001", 62 => "11011000", 63 => "00000111", 
    64 => "11010001", 65 => "11100000", 66 => "00110101", 67 => "00110001", 
    68 => "11111100", 69 => "10110111", 70 => "00010110", 71 => "01011101", 
    72 => "00001010", 73 => "00011001", 74 => "10111011", 75 => "11110110", 
    76 => "00010101", 77 => "11010010", 78 => "11001101", 79 => "01001110", 
    80 => "11000110", 81 => "11100110", 82 => "00110000", 83 => "01011011");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

