-- ==============================================================
-- Generated by Vitis HLS v2025.1.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity lenet_hls_fc_f6_Pipeline_F6_Output_Loop_p_ZL10f6_weights_119_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 8; 
             AddressWidth     : integer := 7; 
             AddressRange    : integer := 84
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of lenet_hls_fc_f6_Pipeline_F6_Output_Loop_p_ZL10f6_weights_119_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "10110111", 1 => "00110111", 2 => "00110101", 3 => "00111100", 
    4 => "11111110", 5 => "00100101", 6 => "00011101", 7 => "10101011", 
    8 => "11100011", 9 => "11110001", 10 => "11100110", 11 => "10100111", 
    12 => "10011100", 13 => "00111011", 14 => "00110101", 15 => "00010110", 
    16 => "01011110", 17 => "00001110", 18 => "00010010", 19 => "00010111", 
    20 => "00111000", 21 => "00001010", 22 => "00001001", 23 => "00010001", 
    24 => "11111011", 25 => "11100000", 26 => "00100101", 27 => "00100001", 
    28 => "00001100", 29 => "00100001", 30 => "00010111", 31 => "10100001", 
    32 => "00001111", 33 => "11010000", 34 => "00001011", 35 => "10100100", 
    36 => "01000000", 37 => "11110101", 38 => "00001010", 39 => "11110010", 
    40 => "00001000", 41 => "11000010", 42 => "11110100", 43 => "01011010", 
    44 => "10100000", 45 => "00011111", 46 => "00100100", 47 => "00010111", 
    48 => "01110010", 49 => "11011101", 50 => "11100111", 51 => "11110010", 
    52 => "00010101", 53 => "11001011", 54 => "01000001", 55 => "11111100", 
    56 => "10111111", 57 => "01010101", 58 => "01011001", 59 => "00111110", 
    60 => "11111110", 61 => "01100000", 62 => "11001101", 63 => "11011101", 
    64 => "11000100", 65 => "00010011", 66 => "00010001", 67 => "01001111", 
    68 => "00010001", 69 => "00111110", 70 => "00011000", 71 => "11001000", 
    72 => "00110111", 73 => "11110101", 74 => "01000011", 75 => "01000101", 
    76 => "00111110", 77 => "11100111", 78 => "00101011", 79 => "10011111", 
    80 => "00011100", 81 => "11100100", 82 => "11100010", 83 => "10101011");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

