-- ==============================================================
-- Generated by Vitis HLS v2025.1.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity lenet_hls_fc_f6_Pipeline_F6_Output_Loop_p_ZL10f6_weights_78_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 8; 
             AddressWidth     : integer := 7; 
             AddressRange    : integer := 84
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of lenet_hls_fc_f6_Pipeline_F6_Output_Loop_p_ZL10f6_weights_78_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "11001100", 1 => "11100110", 2 => "00011000", 3 => "01001111", 
    4 => "11001110", 5 => "10110110", 6 => "00111001", 7 => "00101101", 
    8 => "11100001", 9 => "11001101", 10 => "01001011", 11 => "00000011", 
    12 => "00001100", 13 => "00101001", 14 => "00001111", 15 => "11101010", 
    16 => "00111100", 17 => "00111010", 18 => "01000000", 19 => "00011000", 
    20 => "11111101", 21 => "11101010", 22 => "11000010", 23 => "11111000", 
    24 => "01000111", 25 => "11110111", 26 => "11111011", 27 => "00110110", 
    28 => "11010000", 29 => "00111110", 30 => "00010100", 31 => "00000101", 
    32 => "00100011", 33 => "00101100", 34 => "00101111", 35 => "10111011", 
    36 => "11011000", 37 => "11111010", 38 => "00011101", 39 => "11011110", 
    40 => "00100010", 41 => "11111111", 42 => "11101010", 43 => "00100100", 
    44 => "00000111", 45 => "00101001", 46 => "00101101", 47 => "00101101", 
    48 => "01000001", 49 => "01010011", 50 => "00101100", 51 => "11010000", 
    52 => "00011100", 53 => "00010111", 54 => "00000111", 55 => "11111011", 
    56 => "00100000", 57 => "00110010", 58 => "11101000", 59 => "11010001", 
    60 => "11101110", 61 => "00010010", 62 => "01001001", 63 => "00100100", 
    64 => "11111100", 65 => "00010111", 66 => "00111000", 67 => "00101111", 
    68 => "00010000", 69 => "00011101", 70 => "11010111", 71 => "11111010", 
    72 => "11011010", 73 => "00101111", 74 => "01000100", 75 => "00101010", 
    76 => "00011011", 77 => "00110001", 78 => "00101110", 79 => "11111010", 
    80 => "11010011", 81 => "00001001", 82 => "00100101", 83 => "11100100");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

