-- ==============================================================
-- Generated by Vitis HLS v2025.1.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity lenet_hls_fc_f6_Pipeline_F6_Output_Loop_p_ZL10f6_weights_14_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 8; 
             AddressWidth     : integer := 7; 
             AddressRange    : integer := 84
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of lenet_hls_fc_f6_Pipeline_F6_Output_Loop_p_ZL10f6_weights_14_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00100000", 1 => "00001100", 2 => "00011000", 3 => "01010000", 
    4 => "11000111", 5 => "00100000", 6 => "00011000", 7 => "11101010", 
    8 => "11110110", 9 => "11110110", 10 => "01000110", 11 => "00111100", 
    12 => "11000000", 13 => "00010101", 14 => "10100111", 15 => "00100110", 
    16 => "00111001", 17 => "00100000", 18 => "00000101", 19 => "11010011", 
    20 => "00110001", 21 => "00111010", 22 => "11001011", 23 => "11111011", 
    24 => "00111010", 25 => "11110011", 26 => "11101100", 27 => "00011110", 
    28 => "00011000", 29 => "00100011", 30 => "10101110", 31 => "00001110", 
    32 => "00010110", 33 => "01100001", 34 => "11100000", 35 => "00001100", 
    36 => "11011101", 37 => "11101101", 38 => "00001000", 39 => "00011010", 
    40 => "11010011", 41 => "11010111", 42 => "01000111", 43 => "00000110", 
    44 => "01000110", 45 => "00001001", 46 => "00000011", 47 => "00001010", 
    48 => "10010110", 49 => "10101000", 50 => "10111101", 51 => "11011010", 
    52 => "11101110", 53 => "11110101", 54 => "11111011", 55 => "00000000", 
    56 => "11010101", 57 => "00101100", 58 => "01010001", 59 => "11010010", 
    60 => "00010010", 61 => "11001001", 62 => "11110000", 63 => "00011101", 
    64 => "01001100", 65 => "11101000", 66 => "11100110", 67 => "11011011", 
    68 => "00011111", 69 => "00010000", 70 => "11000100", 71 => "11011000", 
    72 => "01001010", 73 => "11010110", 74 => "01011001", 75 => "11101010", 
    76 => "00011011", 77 => "10001001", 78 => "01011100", 79 => "00010101", 
    80 => "00110110", 81 => "11110001", 82 => "11011100", 83 => "00100001");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

