-- ==============================================================
-- Generated by Vitis HLS v2025.1.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity lenet_hls_fc_f6_Pipeline_F6_Output_Loop_p_ZL10f6_weights_28_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 7; 
             AddressWidth     : integer := 7; 
             AddressRange    : integer := 84
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of lenet_hls_fc_f6_Pipeline_F6_Output_Loop_p_ZL10f6_weights_28_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "1100010", 1 => "0011100", 2 => "1100100", 3 => "1010000", 
    4 => "1111000", 5 => "1111010", 6 => "1110011", 7 => "1101101", 
    8 => "1101100", 9 => "0011000", 10 => "0100101", 11 => "1110011", 
    12 => "0110101", 13 => "0110000", 14 => "0010111", 15 => "0010010", 
    16 => "1110111", 17 => "0000011", 18 => "0001111", 19 => "1110011", 
    20 => "1100111", 21 => "1011111", 22 => "0011000", 23 => "0111110", 
    24 => "1101110", 25 => "0001101", 26 => "0010000", 27 => "0001100", 
    28 => "0010001", 29 => "1010101", 30 => "1110011", 31 => "1100010", 
    32 => "0011011", 33 => "0111000", 34 => "0101110", 35 => "1000110", 
    36 => "1111111", 37 => "0000011", 38 => "1010010", 39 => "0010010", 
    40 => "0000100", 41 => "0000111", 42 => "0001001", 43 => "0010100", 
    44 => "0000000", 45 => "0001101", 46 => "1001111", 47 => "0000111", 
    48 => "0111000", 49 => "1011010", 50 => "0111010", 51 => "1100111", 
    52 => "0100010", 53 => "0011111", 54 => "0001011", 55 => "0001000", 
    56 => "0111101", 57 => "1110111", 58 => "0011111", 59 => "0010011", 
    60 => "0111000", 61 => "0000101", 62 => "0101011", 63 => "1111011", 
    64 => "0101111", 65 => "1000110", 66 => "1100100", 67 => "0000100", 
    68 => "0010100", 69 => "0011011", 70 => "1001001", 71 => "1001111", 
    72 => "0001110", 73 => "0011111", 74 => "1100110", 75 => "0101001", 
    76 => "0011100", 77 => "1110111", 78 => "1010101", 79 => "0001100", 
    80 => "0101001", 81 => "0001111", 82 => "0001001", 83 => "0011000");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

