-- ==============================================================
-- Generated by Vitis HLS v2025.1.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity lenet_hls_fc_f6_Pipeline_F6_Output_Loop_p_ZL10f6_weights_43_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 8; 
             AddressWidth     : integer := 7; 
             AddressRange    : integer := 84
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of lenet_hls_fc_f6_Pipeline_F6_Output_Loop_p_ZL10f6_weights_43_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "11110110", 1 => "00010111", 2 => "11110101", 3 => "00101101", 
    4 => "01011011", 5 => "11010100", 6 => "11011110", 7 => "10110011", 
    8 => "00100110", 9 => "11000011", 10 => "00011011", 11 => "01000111", 
    12 => "00110101", 13 => "00000110", 14 => "01001111", 15 => "11110110", 
    16 => "00011111", 17 => "00000101", 18 => "11111001", 19 => "11111111", 
    20 => "00110110", 21 => "11111010", 22 => "11001111", 23 => "00100111", 
    24 => "01000101", 25 => "00011111", 26 => "11000010", 27 => "00011101", 
    28 => "00100010", 29 => "00011110", 30 => "01000100", 31 => "00011111", 
    32 => "11001110", 33 => "01000000", 34 => "11010111", 35 => "10010111", 
    36 => "11110011", 37 => "11011000", 38 => "11110101", 39 => "01100000", 
    40 => "11110011", 41 => "00010010", 42 => "11101010", 43 => "00111100", 
    44 => "00000001", 45 => "00010010", 46 => "00011101", 47 => "11011000", 
    48 => "01010010", 49 => "00110011", 50 => "11011010", 51 => "11111111", 
    52 => "00110010", 53 => "11110010", 54 => "00001110", 55 => "11000000", 
    56 => "01000001", 57 => "00111110", 58 => "00110000", 59 => "11000010", 
    60 => "11100111", 61 => "00101100", 62 => "00101001", 63 => "10011100", 
    64 => "11101100", 65 => "11001101", 66 => "11001011", 67 => "00000101", 
    68 => "11111100", 69 => "00110100", 70 => "01010101", 71 => "11111101", 
    72 => "11100100", 73 => "11110000", 74 => "00011100", 75 => "00011111", 
    76 => "01000001", 77 => "11110100", 78 => "00010000", 79 => "00101011", 
    80 => "00110111", 81 => "00011011", 82 => "00110100", 83 => "00001011");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

