-- ==============================================================
-- Generated by Vitis HLS v2025.1.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity lenet_hls_fc_f6_Pipeline_F6_Output_Loop_p_ZL10f6_weights_75_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 8; 
             AddressWidth     : integer := 7; 
             AddressRange    : integer := 84
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of lenet_hls_fc_f6_Pipeline_F6_Output_Loop_p_ZL10f6_weights_75_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00101110", 1 => "00011000", 2 => "01010110", 3 => "10110011", 
    4 => "00011111", 5 => "11010101", 6 => "00001011", 7 => "00101000", 
    8 => "00100001", 9 => "11111111", 10 => "00101111", 11 => "00011101", 
    12 => "00001010", 13 => "11011000", 14 => "10110011", 15 => "00101101", 
    16 => "11111111", 17 => "00111010", 18 => "11011100", 19 => "11011101", 
    20 => "11111011", 21 => "00101101", 22 => "00100110", 23 => "11111010", 
    24 => "00001100", 25 => "00100100", 26 => "11011000", 27 => "11100000", 
    28 => "00000110", 29 => "00010000", 30 => "11101101", 31 => "00000110", 
    32 => "11010110", 33 => "00100011", 34 => "11110111", 35 => "00010000", 
    36 => "11011101", 37 => "11110111", 38 => "10110111", 39 => "01001001", 
    40 => "00010010", 41 => "10100011", 42 => "11100100", 43 => "10111011", 
    44 => "01001000", 45 => "11001101", 46 => "01101010", 47 => "11110110", 
    48 => "10111110", 49 => "00110100", 50 => "11110000", 51 => "11010100", 
    52 => "01010000", 53 => "11111111", 54 => "11110100", 55 => "00101001", 
    56 => "01111101", 57 => "01001001", 58 => "00110010", 59 => "11110111", 
    60 => "00100001", 61 => "01001101", 62 => "00011010", 63 => "01000010", 
    64 => "11011010", 65 => "00000111", 66 => "11101001", 67 => "00100011", 
    68 => "11011111", 69 => "11000001", 70 => "11101010", 71 => "00000101", 
    72 => "11001101", 73 => "00010011", 74 => "11110111", 75 => "00001010", 
    76 => "11101110", 77 => "10111100", 78 => "00101100", 79 => "00100000", 
    80 => "00001011", 81 => "11001110", 82 => "00101110", 83 => "00101001");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

