-- ==============================================================
-- Generated by Vitis HLS v2025.1.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity lenet_hls_fc_f6_Pipeline_F6_Output_Loop_p_ZL10f6_weights_94_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 8; 
             AddressWidth     : integer := 7; 
             AddressRange    : integer := 84
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of lenet_hls_fc_f6_Pipeline_F6_Output_Loop_p_ZL10f6_weights_94_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "11101011", 1 => "11100110", 2 => "01000011", 3 => "00000000", 
    4 => "11010000", 5 => "00000000", 6 => "11111000", 7 => "00100110", 
    8 => "11001010", 9 => "11000000", 10 => "11111010", 11 => "00110000", 
    12 => "11110011", 13 => "11000010", 14 => "00101101", 15 => "00111000", 
    16 => "01001000", 17 => "11111001", 18 => "00011011", 19 => "10111111", 
    20 => "00101001", 21 => "11011011", 22 => "11100101", 23 => "00001100", 
    24 => "00010101", 25 => "00101101", 26 => "00010001", 27 => "00010101", 
    28 => "00010100", 29 => "00110111", 30 => "11111110", 31 => "00110101", 
    32 => "00001101", 33 => "11111011", 34 => "11100100", 35 => "11011101", 
    36 => "00000101", 37 => "00010101", 38 => "00001000", 39 => "00100110", 
    40 => "00011000", 41 => "00011100", 42 => "11111010", 43 => "00001100", 
    44 => "11101010", 45 => "00011110", 46 => "11101100", 47 => "11101000", 
    48 => "00010010", 49 => "00000110", 50 => "00000011", 51 => "00011100", 
    52 => "00101001", 53 => "11000110", 54 => "11110101", 55 => "00001100", 
    56 => "11011010", 57 => "11100111", 58 => "11101101", 59 => "11110111", 
    60 => "00110011", 61 => "11111100", 62 => "00101100", 63 => "11010101", 
    64 => "00100110", 65 => "11101100", 66 => "11010010", 67 => "11111101", 
    68 => "11001011", 69 => "11011011", 70 => "00000010", 71 => "10111111", 
    72 => "11010010", 73 => "11101010", 74 => "11001101", 75 => "11101001", 
    76 => "00101001", 77 => "11000101", 78 => "11101111", 79 => "11011011", 
    80 => "00011001", 81 => "00100110", 82 => "00101010", 83 => "00000010");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

