-- ==============================================================
-- Generated by Vitis HLS v2025.1.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity lenet_hls_fc_f6_Pipeline_F6_Output_Loop_p_ZL10f6_weights_8_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 8; 
             AddressWidth     : integer := 7; 
             AddressRange    : integer := 84
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of lenet_hls_fc_f6_Pipeline_F6_Output_Loop_p_ZL10f6_weights_8_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00100001", 1 => "11111011", 2 => "00100000", 3 => "00011001", 
    4 => "11001010", 5 => "00000100", 6 => "11110110", 7 => "11111100", 
    8 => "11111110", 9 => "00100000", 10 => "00000000", 11 => "11010011", 
    12 => "11110110", 13 => "00001110", 14 => "00000010", 15 => "11111011", 
    16 => "01001110", 17 => "11000011", 18 => "01001111", 19 => "00110011", 
    20 => "01000010", 21 => "00000001", 22 => "11000111", 23 => "11100111", 
    24 => "11110111", 25 => "00110010", 26 => "00001111", 27 => "11011000", 
    28 => "11000111", 29 => "11011110", 30 => "11011000", 31 => "11011011", 
    32 => "00110100", 33 => "01010011", 34 => "00111111", 35 => "00101010", 
    36 => "00100000", 37 => "11111001", 38 => "11110110", 39 => "11000111", 
    40 => "11110100", 41 => "11110001", 42 => "00011100", 43 => "00101101", 
    44 => "11010001", 45 => "00001011", 46 => "00100110", 47 => "11101101", 
    48 => "11001010", 49 => "11111001", 50 => "11001110", 51 => "00010001", 
    52 => "00011101", 53 => "00011100", 54 => "11110010", 55 => "10111110", 
    56 => "11001101", 57 => "00100000", 58 => "00001100", 59 => "11001001", 
    60 => "01001100", 61 => "00110011", 62 => "11110110", 63 => "00101001", 
    64 => "11100010", 65 => "00011010", 66 => "11100101", 67 => "11111110", 
    68 => "00111011", 69 => "11000100", 70 => "11100100", 71 => "11001110", 
    72 => "00011111", 73 => "11011001", 74 => "11010111", 75 => "11101010", 
    76 => "00001011", 77 => "00110100", 78 => "00111111", 79 => "00000011", 
    80 => "00011000", 81 => "11101000", 82 => "00100000", 83 => "11100111");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

