-- ==============================================================
-- Generated by Vitis HLS v2025.1.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity lenet_hls_fc_f6_Pipeline_F6_Output_Loop_p_ZL10f6_weights_59_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 8; 
             AddressWidth     : integer := 7; 
             AddressRange    : integer := 84
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of lenet_hls_fc_f6_Pipeline_F6_Output_Loop_p_ZL10f6_weights_59_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00111001", 1 => "00001111", 2 => "11101111", 3 => "00011111", 
    4 => "00100010", 5 => "00001001", 6 => "11100010", 7 => "00011111", 
    8 => "00000001", 9 => "00010000", 10 => "01011000", 11 => "00100101", 
    12 => "11010000", 13 => "11101100", 14 => "00001000", 15 => "00110100", 
    16 => "00101011", 17 => "10100111", 18 => "11010101", 19 => "00011010", 
    20 => "00100110", 21 => "11101010", 22 => "11000011", 23 => "00101110", 
    24 => "00110110", 25 => "11101011", 26 => "11010111", 27 => "00011100", 
    28 => "00100010", 29 => "00100011", 30 => "11101111", 31 => "00101001", 
    32 => "11010101", 33 => "00101100", 34 => "00110110", 35 => "00101000", 
    36 => "00110101", 37 => "10111101", 38 => "11100001", 39 => "10111010", 
    40 => "00001111", 41 => "11101000", 42 => "00110111", 43 => "11011000", 
    44 => "11101110", 45 => "00100100", 46 => "11101010", 47 => "11100110", 
    48 => "11010111", 49 => "00000100", 50 => "00000111", 51 => "00011000", 
    52 => "00001100", 53 => "11010001", 54 => "11010101", 55 => "00000001", 
    56 => "00010100", 57 => "01000001", 58 => "00100100", 59 => "11111000", 
    60 => "11100010", 61 => "00100000", 62 => "00001111", 63 => "00011111", 
    64 => "11100000", 65 => "11110010", 66 => "00010010", 67 => "11000101", 
    68 => "00110101", 69 => "00100101", 70 => "00010011", 71 => "00000011", 
    72 => "00111001", 73 => "00010011", 74 => "01010111", 75 => "00010000", 
    76 => "00011011", 77 => "00101011", 78 => "00001110", 79 => "11001100", 
    80 => "11111101", 81 => "00011100", 82 => "11101010", 83 => "11011101");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

