-- ==============================================================
-- Generated by Vitis HLS v2025.1.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity lenet_hls_fc_f6_Pipeline_F6_Output_Loop_p_ZL10f6_weights_67_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 8; 
             AddressWidth     : integer := 7; 
             AddressRange    : integer := 84
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of lenet_hls_fc_f6_Pipeline_F6_Output_Loop_p_ZL10f6_weights_67_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "11001001", 1 => "11110110", 2 => "00110100", 3 => "11011010", 
    4 => "01111111", 5 => "11110010", 6 => "10111111", 7 => "00010011", 
    8 => "00100010", 9 => "11111110", 10 => "00001100", 11 => "00011111", 
    12 => "11101100", 13 => "11101000", 14 => "11100100", 15 => "00000111", 
    16 => "00000111", 17 => "00010001", 18 => "11100010", 19 => "00101111", 
    20 => "00100110", 21 => "11110110", 22 => "00010100", 23 => "01010010", 
    24 => "00100000", 25 => "00010100", 26 => "11110000", 27 => "00001110", 
    28 => "11111001", 29 => "11001111", 30 => "01101000", 31 => "00111001", 
    32 => "11101011", 33 => "00000011", 34 => "00110101", 35 => "11110100", 
    36 => "11011001", 37 => "00011101", 38 => "11000110", 39 => "11100000", 
    40 => "11111010", 41 => "10111101", 42 => "00101110", 43 => "00000011", 
    44 => "00101011", 45 => "11011001", 46 => "01011101", 47 => "10111010", 
    48 => "11111000", 49 => "10111101", 50 => "11011110", 51 => "00000100", 
    52 => "00110001", 53 => "00011101", 54 => "11000100", 55 => "00000111", 
    56 => "01111001", 57 => "01011111", 58 => "00011000", 59 => "00000001", 
    60 => "00000101", 61 => "01111111", 62 => "00101001", 63 => "11111001", 
    64 => "10101110", 65 => "00011001", 66 => "00101001", 67 => "00011101", 
    68 => "00001111", 69 => "10101001", 70 => "11010011", 71 => "01010010", 
    72 => "00011100", 73 => "01000000", 74 => "01000000", 75 => "00011010", 
    76 => "01001010", 77 => "11010010", 78 => "01010111", 79 => "11000111", 
    80 => "00111011", 81 => "11111100", 82 => "00010111", 83 => "11010011");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

