-- ==============================================================
-- Generated by Vitis HLS v2025.1.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity lenet_hls_fc_f6_Pipeline_F6_Output_Loop_p_ZL10f6_weights_114_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 8; 
             AddressWidth     : integer := 7; 
             AddressRange    : integer := 84
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of lenet_hls_fc_f6_Pipeline_F6_Output_Loop_p_ZL10f6_weights_114_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "11100000", 1 => "00101101", 2 => "11100111", 3 => "00100110", 
    4 => "00111110", 5 => "11111111", 6 => "11111110", 7 => "11101010", 
    8 => "11011111", 9 => "00001011", 10 => "11111000", 11 => "11110011", 
    12 => "11011011", 13 => "00011010", 14 => "00011111", 15 => "10111101", 
    16 => "00010011", 17 => "11111111", 18 => "11001100", 19 => "11101100", 
    20 => "11111100", 21 => "11010110", 22 => "10111011", 23 => "00110000", 
    24 => "01000011", 25 => "11101100", 26 => "00110111", 27 => "00001111", 
    28 => "00110110", 29 => "01000111", 30 => "00110011", 31 => "00100001", 
    32 => "11000101", 33 => "11011011", 34 => "00101110", 35 => "11101011", 
    36 => "10111111", 37 => "00010010", 38 => "11101101", 39 => "00010100", 
    40 => "11101000", 41 => "11110101", 42 => "11010111", 43 => "11011001", 
    44 => "00100011", 45 => "00100101", 46 => "00011110", 47 => "11010011", 
    48 => "11101110", 49 => "00101100", 50 => "11010101", 51 => "00011110", 
    52 => "00011111", 53 => "11011110", 54 => "00110110", 55 => "01000111", 
    56 => "11100101", 57 => "01000010", 58 => "11100111", 59 => "11010011", 
    60 => "00011001", 61 => "00101110", 62 => "11011101", 63 => "00010011", 
    64 => "11100101", 65 => "01001001", 66 => "00001001", 67 => "00010011", 
    68 => "00000100", 69 => "11101110", 70 => "00101010", 71 => "00110101", 
    72 => "11100010", 73 => "11011011", 74 => "00101111", 75 => "11011000", 
    76 => "00110010", 77 => "00001001", 78 => "11110111", 79 => "11100100", 
    80 => "00010100", 81 => "11100101", 82 => "00101100", 83 => "00010011");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

