-- ==============================================================
-- Generated by Vitis HLS v2025.1.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity lenet_hls_fc_f6_Pipeline_F6_Output_Loop_p_ZL10f6_weights_109_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 8; 
             AddressWidth     : integer := 7; 
             AddressRange    : integer := 84
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of lenet_hls_fc_f6_Pipeline_F6_Output_Loop_p_ZL10f6_weights_109_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "11010001", 1 => "00010011", 2 => "11110110", 3 => "00101111", 
    4 => "11100011", 5 => "11000101", 6 => "00010100", 7 => "11100011", 
    8 => "11100011", 9 => "11010101", 10 => "00101001", 11 => "11111001", 
    12 => "11111000", 13 => "11100110", 14 => "00010111", 15 => "00000100", 
    16 => "00110101", 17 => "00010010", 18 => "00101011", 19 => "00101011", 
    20 => "00011111", 21 => "11001100", 22 => "00111001", 23 => "11101010", 
    24 => "00001000", 25 => "11100101", 26 => "11101100", 27 => "11001100", 
    28 => "00010101", 29 => "00000101", 30 => "11101011", 31 => "11100011", 
    32 => "11000100", 33 => "11100011", 34 => "11100010", 35 => "00000111", 
    36 => "00000111", 37 => "01000100", 38 => "00110111", 39 => "00001101", 
    40 => "11100111", 41 => "00010010", 42 => "01000011", 43 => "11001110", 
    44 => "00010011", 45 => "10110101", 46 => "11001101", 47 => "00000000", 
    48 => "00100100", 49 => "11011011", 50 => "11000010", 51 => "00011010", 
    52 => "11101111", 53 => "00011011", 54 => "00000001", 55 => "11011111", 
    56 => "00000011", 57 => "11101101", 58 => "00001100", 59 => "00010001", 
    60 => "11101111", 61 => "10111101", 62 => "00010110", 63 => "11010111", 
    64 => "11101011", 65 => "01001100", 66 => "00100110", 67 => "11111100", 
    68 => "00000110", 69 => "11111001", 70 => "10111100", 71 => "00110101", 
    72 => "00100000", 73 => "00101011", 74 => "11111010", 75 => "00100111", 
    76 => "11100110", 77 => "00110101", 78 => "00100000", 79 => "00011111", 
    80 => "00001111", 81 => "00001100", 82 => "00011010", 83 => "11000100");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

