-- ==============================================================
-- Generated by Vitis HLS v2025.1.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity lenet_hls_fc_f6_Pipeline_F6_Output_Loop_p_ZL10f6_weights_38_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 8; 
             AddressWidth     : integer := 7; 
             AddressRange    : integer := 84
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of lenet_hls_fc_f6_Pipeline_F6_Output_Loop_p_ZL10f6_weights_38_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00000100", 1 => "00100110", 2 => "11001011", 3 => "00100110", 
    4 => "11001000", 5 => "11100011", 6 => "11010111", 7 => "00100100", 
    8 => "11101001", 9 => "01000011", 10 => "00010111", 11 => "11110101", 
    12 => "00001011", 13 => "11101111", 14 => "11011011", 15 => "00010011", 
    16 => "11101101", 17 => "10111110", 18 => "01001001", 19 => "11101000", 
    20 => "10110110", 21 => "11100100", 22 => "01101100", 23 => "00000000", 
    24 => "11111011", 25 => "11101010", 26 => "00000010", 27 => "11001100", 
    28 => "11111110", 29 => "11110101", 30 => "11011000", 31 => "00111111", 
    32 => "11011010", 33 => "00101010", 34 => "11110010", 35 => "01000010", 
    36 => "00000000", 37 => "01000001", 38 => "00111010", 39 => "11100101", 
    40 => "01010010", 41 => "00011001", 42 => "00010110", 43 => "00111100", 
    44 => "11001111", 45 => "00110011", 46 => "00000100", 47 => "00010110", 
    48 => "00011100", 49 => "11011001", 50 => "11111111", 51 => "11110101", 
    52 => "10110110", 53 => "11110100", 54 => "01001100", 55 => "00010100", 
    56 => "11101111", 57 => "11011100", 58 => "01001010", 59 => "01000110", 
    60 => "11101110", 61 => "00100010", 62 => "11101110", 63 => "00001000", 
    64 => "11100111", 65 => "01011111", 66 => "00110001", 67 => "11101101", 
    68 => "11111011", 69 => "11110001", 70 => "00010101", 71 => "00111000", 
    72 => "00101000", 73 => "11100111", 74 => "10110100", 75 => "11010101", 
    76 => "00111001", 77 => "11011000", 78 => "11100011", 79 => "00001011", 
    80 => "11111101", 81 => "11100100", 82 => "11111010", 83 => "00100100");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

