-- ==============================================================
-- Generated by Vitis HLS v2025.1.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity lenet_hls_fc_f6_Pipeline_F6_Output_Loop_p_ZL10f6_weights_27_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 8; 
             AddressWidth     : integer := 7; 
             AddressRange    : integer := 84
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of lenet_hls_fc_f6_Pipeline_F6_Output_Loop_p_ZL10f6_weights_27_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00110000", 1 => "11001110", 2 => "00011100", 3 => "00011001", 
    4 => "10110110", 5 => "11001110", 6 => "00110111", 7 => "11110011", 
    8 => "11011111", 9 => "01000101", 10 => "00011111", 11 => "00000001", 
    12 => "00101010", 13 => "01011111", 14 => "01010011", 15 => "10100000", 
    16 => "11100000", 17 => "01000111", 18 => "01011000", 19 => "11010100", 
    20 => "11010010", 21 => "10111010", 22 => "00010000", 23 => "11110100", 
    24 => "00011100", 25 => "00100000", 26 => "00101111", 27 => "01000011", 
    28 => "11001011", 29 => "00101001", 30 => "11110101", 31 => "11011100", 
    32 => "11010100", 33 => "11110001", 34 => "00010110", 35 => "00010011", 
    36 => "01000010", 37 => "00011010", 38 => "01001101", 39 => "10111011", 
    40 => "00101100", 41 => "11011100", 42 => "11111100", 43 => "11001011", 
    44 => "00101011", 45 => "11101101", 46 => "11110100", 47 => "01101111", 
    48 => "11111001", 49 => "00100100", 50 => "00111000", 51 => "00011110", 
    52 => "11111101", 53 => "00100100", 54 => "11101011", 55 => "10111001", 
    56 => "00000100", 57 => "00001010", 58 => "00011110", 59 => "11100111", 
    60 => "11001110", 61 => "11011111", 62 => "00111010", 63 => "10111110", 
    64 => "00010100", 65 => "11011010", 66 => "11101100", 67 => "11010001", 
    68 => "11001110", 69 => "01011010", 70 => "00000111", 71 => "00110001", 
    72 => "11100100", 73 => "00001001", 74 => "11111110", 75 => "11110001", 
    76 => "10101111", 77 => "01010001", 78 => "11001011", 79 => "01001100", 
    80 => "10110100", 81 => "11100011", 82 => "11110001", 83 => "11001001");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

