-- ==============================================================
-- Generated by Vitis HLS v2025.1.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity lenet_hls_fc_f6_Pipeline_F6_Output_Loop_p_ZL10f6_weights_19_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 8; 
             AddressWidth     : integer := 7; 
             AddressRange    : integer := 84
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of lenet_hls_fc_f6_Pipeline_F6_Output_Loop_p_ZL10f6_weights_19_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00010001", 1 => "00000001", 2 => "00111100", 3 => "00011000", 
    4 => "00100111", 5 => "00111010", 6 => "11101000", 7 => "11010010", 
    8 => "00010100", 9 => "11010000", 10 => "00011001", 11 => "00010011", 
    12 => "11011111", 13 => "11100110", 14 => "00100011", 15 => "00100001", 
    16 => "11001000", 17 => "00011110", 18 => "00001100", 19 => "11110001", 
    20 => "00011110", 21 => "11010100", 22 => "11011100", 23 => "11010001", 
    24 => "00011101", 25 => "11011101", 26 => "11001011", 27 => "00011110", 
    28 => "11001011", 29 => "00101110", 30 => "00110111", 31 => "11111001", 
    32 => "00011000", 33 => "00001100", 34 => "00011101", 35 => "00001010", 
    36 => "00011001", 37 => "11111100", 38 => "00000110", 39 => "00000011", 
    40 => "00000101", 41 => "11100001", 42 => "11100111", 43 => "00001111", 
    44 => "11110011", 45 => "00110000", 46 => "11110111", 47 => "00111111", 
    48 => "00100011", 49 => "00001011", 50 => "11100111", 51 => "00001111", 
    52 => "00001101", 53 => "11010110", 54 => "00000100", 55 => "11101110", 
    56 => "10111111", 57 => "11111011", 58 => "00011001", 59 => "11001101", 
    60 => "11000111", 61 => "00000011", 62 => "00011110", 63 => "00001001", 
    64 => "11110101", 65 => "11101011", 66 => "11101111", 67 => "11010010", 
    68 => "11101000", 69 => "00000001", 70 => "11011010", 71 => "11111110", 
    72 => "11101011", 73 => "11100101", 74 => "00001110", 75 => "11110110", 
    76 => "11110000", 77 => "00001100", 78 => "00101111", 79 => "00010000", 
    80 => "00100000", 81 => "00011000", 82 => "11001100", 83 => "00100101");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

