-- ==============================================================
-- Generated by Vitis HLS v2025.1.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity lenet_hls_fc_f6_Pipeline_F6_Output_Loop_p_ZL10f6_weights_106_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 8; 
             AddressWidth     : integer := 7; 
             AddressRange    : integer := 84
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of lenet_hls_fc_f6_Pipeline_F6_Output_Loop_p_ZL10f6_weights_106_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "11100001", 1 => "10111001", 2 => "00010110", 3 => "11110000", 
    4 => "11010100", 5 => "00001100", 6 => "11000001", 7 => "11111101", 
    8 => "00100000", 9 => "11111100", 10 => "00111001", 11 => "01010110", 
    12 => "11111001", 13 => "11010010", 14 => "00011000", 15 => "11101100", 
    16 => "00100110", 17 => "00010000", 18 => "00010000", 19 => "00101101", 
    20 => "11010001", 21 => "11001111", 22 => "11010100", 23 => "11100110", 
    24 => "00011001", 25 => "00011001", 26 => "11110101", 27 => "10111111", 
    28 => "11111101", 29 => "11110111", 30 => "11110011", 31 => "00101111", 
    32 => "11111001", 33 => "11101011", 34 => "00001000", 35 => "00011110", 
    36 => "11101110", 37 => "00111111", 38 => "00100110", 39 => "11011111", 
    40 => "00000110", 41 => "00010000", 42 => "11111100", 43 => "00000110", 
    44 => "01001001", 45 => "00010111", 46 => "00010010", 47 => "00001110", 
    48 => "11100010", 49 => "00110100", 50 => "00010011", 51 => "00010110", 
    52 => "00111111", 53 => "11001000", 54 => "00001100", 55 => "10110001", 
    56 => "00000111", 57 => "11111011", 58 => "11110100", 59 => "11111001", 
    60 => "10111111", 61 => "11000011", 62 => "00001101", 63 => "00010010", 
    64 => "01011110", 65 => "00011001", 66 => "11011111", 67 => "10111111", 
    68 => "00111001", 69 => "00010100", 70 => "11000001", 71 => "00110010", 
    72 => "11101010", 73 => "11100010", 74 => "00010110", 75 => "11101111", 
    76 => "11000000", 77 => "00100101", 78 => "00110111", 79 => "11110000", 
    80 => "00100100", 81 => "11111101", 82 => "11011001", 83 => "11111110");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

