-- ==============================================================
-- Generated by Vitis HLS v2025.1.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity lenet_hls_fc_f6_Pipeline_F6_Output_Loop_p_ZL10f6_weights_84_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 8; 
             AddressWidth     : integer := 7; 
             AddressRange    : integer := 84
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of lenet_hls_fc_f6_Pipeline_F6_Output_Loop_p_ZL10f6_weights_84_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "11101101", 1 => "10111001", 2 => "00001011", 3 => "11011100", 
    4 => "00000101", 5 => "00100110", 6 => "01010001", 7 => "11100101", 
    8 => "11100000", 9 => "00111010", 10 => "01000110", 11 => "00110011", 
    12 => "01101000", 13 => "00001111", 14 => "00011011", 15 => "11111001", 
    16 => "00011011", 17 => "11001000", 18 => "11111110", 19 => "00110011", 
    20 => "01011011", 21 => "01000011", 22 => "10111110", 23 => "00101101", 
    24 => "01000000", 25 => "00101011", 26 => "11101001", 27 => "11001001", 
    28 => "11100111", 29 => "01000110", 30 => "00110001", 31 => "11100000", 
    32 => "00100110", 33 => "00110100", 34 => "00110111", 35 => "00010100", 
    36 => "11101100", 37 => "00111001", 38 => "11011101", 39 => "11101011", 
    40 => "00000101", 41 => "00000101", 42 => "10011001", 43 => "01001110", 
    44 => "01010011", 45 => "00010101", 46 => "00111110", 47 => "11010100", 
    48 => "10101000", 49 => "00011011", 50 => "11101111", 51 => "00110101", 
    52 => "01001010", 53 => "11110011", 54 => "00001010", 55 => "00000011", 
    56 => "01000100", 57 => "00000100", 58 => "11010011", 59 => "11011101", 
    60 => "01101001", 61 => "00101110", 62 => "01010100", 63 => "10110001", 
    64 => "11111011", 65 => "11001100", 66 => "01000011", 67 => "00101001", 
    68 => "00010110", 69 => "11010011", 70 => "00001000", 71 => "10111011", 
    72 => "11110000", 73 => "00100101", 74 => "11101000", 75 => "00100101", 
    76 => "00000010", 77 => "01000100", 78 => "11111011", 79 => "00011101", 
    80 => "00001110", 81 => "00100000", 82 => "11100010", 83 => "01010011");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

