-- ==============================================================
-- Generated by Vitis HLS v2025.1.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity lenet_hls_fc_f6_Pipeline_F6_Output_Loop_p_ZL10f6_weights_87_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 7; 
             AddressWidth     : integer := 7; 
             AddressRange    : integer := 84
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of lenet_hls_fc_f6_Pipeline_F6_Output_Loop_p_ZL10f6_weights_87_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "0000010", 1 => "0000100", 2 => "0110001", 3 => "1001001", 
    4 => "0110010", 5 => "0001001", 6 => "0001111", 7 => "0011001", 
    8 => "0010001", 9 => "0011011", 10 => "1100111", 11 => "1001010", 
    12 => "0001101", 13 => "0111010", 14 => "0001000", 15 => "1100000", 
    16 => "1010111", 17 => "1110001", 18 => "0011111", 19 => "1010111", 
    20 => "0001010", 21 => "1101000", 22 => "0010100", 23 => "0000000", 
    24 => "0000011", 25 => "1101000", 26 => "1110010", 27 => "1111110", 
    28 => "1110101", 29 => "0000001", 30 => "1100010", 31 => "1101001", 
    32 => "0101001", 33 => "1001001", 34 => "0100010", 35 => "0010010", 
    36 => "1001101", 37 => "1011000", 38 => "1100001", 39 => "1110010", 
    40 => "1000111", 41 => "0100011", 42 => "1111111", 43 => "1010010", 
    44 => "0010110", 45 => "1001101", 46 => "1011010", 47 => "1111010", 
    48 => "1100000", 49 => "0101100", 50 => "1001110", 51 => "1111000", 
    52 => "1010011", 53 => "1111000", 54 => "0010101", 55 => "0110111", 
    56 => "0101100", 57 => "1010110", 58 => "1100001", 59 => "1011011", 
    60 => "1011010", 61 => "1111011", 62 => "0100011", 63 => "0101010", 
    64 => "1011000", 65 => "0011110", 66 => "1111111", 67 => "1110100", 
    68 => "1011110", 69 => "1111110", 70 => "1101101", 71 => "1010111", 
    72 => "1001010", 73 => "0100110", 74 => "1111011", 75 => "1100100", 
    76 => "1110000", 77 => "1101101", 78 => "1001111", 79 => "0010011", 
    80 => "0110010", 81 => "0101101", 82 => "0000000", 83 => "0010111");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

