-- ==============================================================
-- Generated by Vitis HLS v2025.1.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity lenet_hls_fc_f6_Pipeline_F6_Output_Loop_p_ZL10f6_weights_50_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 8; 
             AddressWidth     : integer := 7; 
             AddressRange    : integer := 84
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of lenet_hls_fc_f6_Pipeline_F6_Output_Loop_p_ZL10f6_weights_50_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "11011001", 1 => "00010011", 2 => "11001010", 3 => "00100111", 
    4 => "00100110", 5 => "11000100", 6 => "00101001", 7 => "00111110", 
    8 => "00011011", 9 => "00110001", 10 => "00011101", 11 => "00010110", 
    12 => "01001100", 13 => "00011010", 14 => "00111011", 15 => "11101001", 
    16 => "10111111", 17 => "10110110", 18 => "11001100", 19 => "00101010", 
    20 => "11001101", 21 => "00111001", 22 => "00001011", 23 => "11111100", 
    24 => "11110101", 25 => "00001110", 26 => "00101010", 27 => "00011011", 
    28 => "00010011", 29 => "11100101", 30 => "00010010", 31 => "11001000", 
    32 => "00000110", 33 => "00110101", 34 => "00101111", 35 => "00010111", 
    36 => "00100101", 37 => "00001001", 38 => "11010111", 39 => "00100000", 
    40 => "11010011", 41 => "01000100", 42 => "01101000", 43 => "10111110", 
    44 => "00011111", 45 => "00110111", 46 => "00101101", 47 => "00110101", 
    48 => "10111011", 49 => "00110101", 50 => "01000110", 51 => "11010011", 
    52 => "11111000", 53 => "00011000", 54 => "00010011", 55 => "00110000", 
    56 => "00011111", 57 => "10110110", 58 => "00001010", 59 => "11001010", 
    60 => "11100001", 61 => "10111100", 62 => "00011000", 63 => "00011110", 
    64 => "00001101", 65 => "11001101", 66 => "00010000", 67 => "00110000", 
    68 => "11110110", 69 => "11100011", 70 => "00110000", 71 => "11111111", 
    72 => "00100000", 73 => "00111100", 74 => "01000110", 75 => "11101100", 
    76 => "00100101", 77 => "11101011", 78 => "00100001", 79 => "00010000", 
    80 => "11000000", 81 => "10111111", 82 => "00001011", 83 => "01000011");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

