-- ==============================================================
-- Generated by Vitis HLS v2025.1.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity lenet_hls_fc_f6_Pipeline_F6_Output_Loop_p_ZL10f6_weights_17_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 8; 
             AddressWidth     : integer := 7; 
             AddressRange    : integer := 84
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of lenet_hls_fc_f6_Pipeline_F6_Output_Loop_p_ZL10f6_weights_17_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00010101", 1 => "00110010", 2 => "00100010", 3 => "00100000", 
    4 => "01010001", 5 => "11001010", 6 => "11100000", 7 => "00111001", 
    8 => "00001000", 9 => "10111100", 10 => "00101000", 11 => "00111001", 
    12 => "11011111", 13 => "11110110", 14 => "00010011", 15 => "10111010", 
    16 => "11011000", 17 => "00101100", 18 => "11010000", 19 => "00010001", 
    20 => "00101110", 21 => "00101110", 22 => "11110011", 23 => "01001001", 
    24 => "00011001", 25 => "11100111", 26 => "11010110", 27 => "00001111", 
    28 => "01001010", 29 => "00101100", 30 => "11110010", 31 => "11011111", 
    32 => "11010110", 33 => "11101011", 34 => "11000000", 35 => "11111000", 
    36 => "10110001", 37 => "00001000", 38 => "00011111", 39 => "00011011", 
    40 => "00110001", 41 => "11101011", 42 => "00001101", 43 => "00100011", 
    44 => "11110000", 45 => "10110101", 46 => "11111100", 47 => "11011100", 
    48 => "01000001", 49 => "11001001", 50 => "00010001", 51 => "00000101", 
    52 => "11001010", 53 => "11100101", 54 => "11100011", 55 => "00101111", 
    56 => "00010111", 57 => "11100100", 58 => "00000100", 59 => "00010100", 
    60 => "11000011", 61 => "00110001", 62 => "10111101", 63 => "00110110", 
    64 => "11101101", 65 => "00111011", 66 => "11100010", 67 => "11011000", 
    68 => "11010000", 69 => "11001001", 70 => "00110011", 71 => "00110111", 
    72 => "01010011", 73 => "11010010", 74 => "11111010", 75 => "11101001", 
    76 => "01000101", 77 => "11010111", 78 => "00011011", 79 => "00100001", 
    80 => "00101001", 81 => "00010010", 82 => "10110000", 83 => "00100110");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

