-- ==============================================================
-- Generated by Vitis HLS v2025.1.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity lenet_hls_exp_9_3_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    x : IN STD_LOGIC_VECTOR (8 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (7 downto 0) );
end;


architecture behav of lenet_hls_exp_9_3_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_19 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011001";
    constant ap_const_lv32_31 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110001";
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_16 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010110";
    constant ap_const_lv32_15 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010101";
    constant ap_const_lv32_14 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010100";
    constant ap_const_lv32_13 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010011";
    constant ap_const_lv32_12 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010010";
    constant ap_const_lv32_11 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010001";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv8_FF : STD_LOGIC_VECTOR (7 downto 0) := "11111111";

attribute shreg_extract : string;
    signal exp_x_msb_2_m_1_table_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal exp_x_msb_2_m_1_table_q0 : STD_LOGIC_VECTOR (24 downto 0);
    signal exp_x_msb_1_table_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal exp_x_msb_1_table_q0 : STD_LOGIC_VECTOR (24 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal exp_x_msb_2_m_1_reg_306 : STD_LOGIC_VECTOR (24 downto 0);
    signal exp_x_msb_1_reg_311 : STD_LOGIC_VECTOR (24 downto 0);
    signal exp_x_msb_1_reg_311_pp0_iter2_reg : STD_LOGIC_VECTOR (24 downto 0);
    signal y_lo_s_reg_317 : STD_LOGIC_VECTOR (24 downto 0);
    signal zext_ln219_fu_126_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln235_fu_131_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal exp_x_msb_2_m_1_table_ce0_local : STD_LOGIC;
    signal exp_x_msb_1_table_ce0_local : STD_LOGIC;
    signal y_lo_fu_92_p0 : STD_LOGIC_VECTOR (24 downto 0);
    signal y_lo_fu_92_p1 : STD_LOGIC_VECTOR (24 downto 0);
    signal tmp_fu_96_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_9_fu_104_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal x_msb_ind_2_fu_122_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal x_msb_ind_1_fu_114_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal y_lo_fu_92_p2 : STD_LOGIC_VECTOR (49 downto 0);
    signal y_l_fu_154_p2 : STD_LOGIC_VECTOR (24 downto 0);
    signal tmp_2_fu_166_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal overf_fu_158_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_3_fu_174_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_4_fu_182_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln245_1_fu_236_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln245_fu_230_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_5_fu_190_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_6_fu_198_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_8_fu_214_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_10_fu_222_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln245_4_fu_254_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_7_fu_206_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln245_5_fu_260_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln245_3_fu_248_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln245_6_fu_266_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln245_2_fu_242_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal overf_1_fu_272_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln_fu_278_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal x_int_reg : STD_LOGIC_VECTOR (8 downto 0);
    signal y_lo_fu_92_p00 : STD_LOGIC_VECTOR (49 downto 0);
    signal y_lo_fu_92_p10 : STD_LOGIC_VECTOR (49 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component lenet_hls_mul_25ns_25ns_50_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (24 downto 0);
        din1 : IN STD_LOGIC_VECTOR (24 downto 0);
        dout : OUT STD_LOGIC_VECTOR (49 downto 0) );
    end component;


    component lenet_hls_exp_9_3_s_exp_x_msb_2_m_1_table_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (4 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (24 downto 0) );
    end component;


    component lenet_hls_exp_9_3_s_exp_x_msb_1_table_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (4 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (24 downto 0) );
    end component;



begin
    exp_x_msb_2_m_1_table_U : component lenet_hls_exp_9_3_s_exp_x_msb_2_m_1_table_ROM_AUTO_1R
    generic map (
        DataWidth => 25,
        AddressRange => 32,
        AddressWidth => 5)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => exp_x_msb_2_m_1_table_address0,
        ce0 => exp_x_msb_2_m_1_table_ce0_local,
        q0 => exp_x_msb_2_m_1_table_q0);

    exp_x_msb_1_table_U : component lenet_hls_exp_9_3_s_exp_x_msb_1_table_ROM_AUTO_1R
    generic map (
        DataWidth => 25,
        AddressRange => 32,
        AddressWidth => 5)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => exp_x_msb_1_table_address0,
        ce0 => exp_x_msb_1_table_ce0_local,
        q0 => exp_x_msb_1_table_q0);

    mul_25ns_25ns_50_1_1_U5 : component lenet_hls_mul_25ns_25ns_50_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 25,
        din1_WIDTH => 25,
        dout_WIDTH => 50)
    port map (
        din0 => y_lo_fu_92_p0,
        din1 => y_lo_fu_92_p1,
        dout => y_lo_fu_92_p2);





    x_int_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            x_int_reg <= x;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                exp_x_msb_1_reg_311 <= exp_x_msb_1_table_q0;
                exp_x_msb_1_reg_311_pp0_iter2_reg <= exp_x_msb_1_reg_311;
                exp_x_msb_2_m_1_reg_306 <= exp_x_msb_2_m_1_table_q0;
                y_lo_s_reg_317 <= y_lo_fu_92_p2(49 downto 25);
            end if;
        end if;
    end process;
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
    ap_return <= 
        ap_const_lv8_FF when (overf_1_fu_272_p2(0) = '1') else 
        trunc_ln_fu_278_p4;
    exp_x_msb_1_table_address0 <= zext_ln235_fu_131_p1(5 - 1 downto 0);

    exp_x_msb_1_table_ce0_local_assign_proc : process(ap_block_pp0_stage0_11001)
    begin
        if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then 
            exp_x_msb_1_table_ce0_local <= ap_const_logic_1;
        else 
            exp_x_msb_1_table_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    exp_x_msb_2_m_1_table_address0 <= zext_ln219_fu_126_p1(5 - 1 downto 0);

    exp_x_msb_2_m_1_table_ce0_local_assign_proc : process(ap_block_pp0_stage0_11001)
    begin
        if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then 
            exp_x_msb_2_m_1_table_ce0_local <= ap_const_logic_1;
        else 
            exp_x_msb_2_m_1_table_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    or_ln245_1_fu_236_p2 <= (tmp_4_fu_182_p3 or tmp_3_fu_174_p3);
    or_ln245_2_fu_242_p2 <= (or_ln245_fu_230_p2 or or_ln245_1_fu_236_p2);
    or_ln245_3_fu_248_p2 <= (tmp_6_fu_198_p3 or tmp_5_fu_190_p3);
    or_ln245_4_fu_254_p2 <= (tmp_8_fu_214_p3 or tmp_10_fu_222_p3);
    or_ln245_5_fu_260_p2 <= (tmp_7_fu_206_p3 or or_ln245_4_fu_254_p2);
    or_ln245_6_fu_266_p2 <= (or_ln245_5_fu_260_p2 or or_ln245_3_fu_248_p2);
    or_ln245_fu_230_p2 <= (tmp_2_fu_166_p3 or overf_fu_158_p3);
    overf_1_fu_272_p2 <= (or_ln245_6_fu_266_p2 or or_ln245_2_fu_242_p2);
    overf_fu_158_p3 <= y_l_fu_154_p2(24 downto 24);
    tmp_10_fu_222_p3 <= y_l_fu_154_p2(16 downto 16);
    tmp_2_fu_166_p3 <= y_l_fu_154_p2(23 downto 23);
    tmp_3_fu_174_p3 <= y_l_fu_154_p2(22 downto 22);
    tmp_4_fu_182_p3 <= y_l_fu_154_p2(21 downto 21);
    tmp_5_fu_190_p3 <= y_l_fu_154_p2(20 downto 20);
    tmp_6_fu_198_p3 <= y_l_fu_154_p2(19 downto 19);
    tmp_7_fu_206_p3 <= y_l_fu_154_p2(18 downto 18);
    tmp_8_fu_214_p3 <= y_l_fu_154_p2(17 downto 17);
    tmp_9_fu_104_p4 <= x_int_reg(8 downto 5);
    tmp_fu_96_p3 <= x_int_reg(8 downto 8);
    trunc_ln_fu_278_p4 <= y_l_fu_154_p2(15 downto 8);
    x_msb_ind_1_fu_114_p3 <= (tmp_fu_96_p3 & tmp_9_fu_104_p4);
    x_msb_ind_2_fu_122_p1 <= x_int_reg(5 - 1 downto 0);
    y_l_fu_154_p2 <= std_logic_vector(unsigned(exp_x_msb_1_reg_311_pp0_iter2_reg) + unsigned(y_lo_s_reg_317));
    y_lo_fu_92_p0 <= y_lo_fu_92_p00(25 - 1 downto 0);
    y_lo_fu_92_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(exp_x_msb_2_m_1_reg_306),50));
    y_lo_fu_92_p1 <= y_lo_fu_92_p10(25 - 1 downto 0);
    y_lo_fu_92_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(exp_x_msb_1_reg_311),50));
    zext_ln219_fu_126_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(x_msb_ind_2_fu_122_p1),64));
    zext_ln235_fu_131_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(x_msb_ind_1_fu_114_p3),64));
end behav;
