-- ==============================================================
-- Generated by Vitis HLS v2025.1.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity lenet_hls_fc_f6_Pipeline_F6_Output_Loop_p_ZL10f6_weights_37_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 8; 
             AddressWidth     : integer := 7; 
             AddressRange    : integer := 84
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of lenet_hls_fc_f6_Pipeline_F6_Output_Loop_p_ZL10f6_weights_37_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "11010010", 1 => "01100010", 2 => "11101001", 3 => "11011010", 
    4 => "00001011", 5 => "11011100", 6 => "00001111", 7 => "00110001", 
    8 => "11110101", 9 => "10110101", 10 => "00111010", 11 => "00011111", 
    12 => "01011001", 13 => "01000100", 14 => "01100100", 15 => "11000001", 
    16 => "11011101", 17 => "01010110", 18 => "10101011", 19 => "10110100", 
    20 => "00101111", 21 => "00000001", 22 => "00101110", 23 => "11010011", 
    24 => "00110010", 25 => "00001010", 26 => "00001110", 27 => "11110111", 
    28 => "11101011", 29 => "01010101", 30 => "01010011", 31 => "00100111", 
    32 => "00011011", 33 => "11101001", 34 => "00000000", 35 => "11101001", 
    36 => "11100010", 37 => "00011011", 38 => "00000010", 39 => "00010100", 
    40 => "11110101", 41 => "11000011", 42 => "00001100", 43 => "11111111", 
    44 => "11010100", 45 => "11110000", 46 => "01001011", 47 => "11100001", 
    48 => "00100011", 49 => "00111000", 50 => "01000000", 51 => "11011111", 
    52 => "11101011", 53 => "00101010", 54 => "01111111", 55 => "11110001", 
    56 => "11111100", 57 => "11110000", 58 => "11011100", 59 => "11101101", 
    60 => "00110011", 61 => "00111100", 62 => "10111010", 63 => "11100100", 
    64 => "00000101", 65 => "11000001", 66 => "00011011", 67 => "01001010", 
    68 => "11011010", 69 => "00011101", 70 => "11000101", 71 => "00000111", 
    72 => "10101000", 73 => "00000001", 74 => "11101100", 75 => "11001000", 
    76 => "11110001", 77 => "01100101", 78 => "11110101", 79 => "01011111", 
    80 => "11100111", 81 => "11100100", 82 => "00100110", 83 => "01000111");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

