-- ==============================================================
-- Generated by Vitis HLS v2025.1.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity lenet_hls_fc_f6_Pipeline_F6_Output_Loop_p_ZL10f6_weights_30_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 8; 
             AddressWidth     : integer := 7; 
             AddressRange    : integer := 84
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of lenet_hls_fc_f6_Pipeline_F6_Output_Loop_p_ZL10f6_weights_30_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00010000", 1 => "00111111", 2 => "11110111", 3 => "11111001", 
    4 => "11111010", 5 => "11001010", 6 => "00011110", 7 => "11001111", 
    8 => "11011101", 9 => "11101010", 10 => "11101000", 11 => "11011111", 
    12 => "00001001", 13 => "00010110", 14 => "11100000", 15 => "11111001", 
    16 => "11111011", 17 => "11100110", 18 => "11001011", 19 => "11000101", 
    20 => "00111010", 21 => "00001010", 22 => "00000010", 23 => "00100000", 
    24 => "00000001", 25 => "11011010", 26 => "11001101", 27 => "00110110", 
    28 => "11110101", 29 => "00101100", 30 => "00101000", 31 => "01001010", 
    32 => "00000101", 33 => "11011011", 34 => "11010001", 35 => "11110111", 
    36 => "11101001", 37 => "00011100", 38 => "00000001", 39 => "11110111", 
    40 => "00000011", 41 => "00000000", 42 => "01001001", 43 => "00100010", 
    44 => "00001101", 45 => "11101101", 46 => "11011011", 47 => "11110000", 
    48 => "00010110", 49 => "00011000", 50 => "01001111", 51 => "00010101", 
    52 => "11011001", 53 => "11111011", 54 => "00010001", 55 => "11011100", 
    56 => "00001000", 57 => "11011110", 58 => "11110100", 59 => "00011010", 
    60 => "11010111", 61 => "00100001", 62 => "11010111", 63 => "00111101", 
    64 => "11000110", 65 => "00100111", 66 => "11100110", 67 => "00100101", 
    68 => "11100000", 69 => "00101010", 70 => "00001000", 71 => "00101101", 
    72 => "11101000", 73 => "00011101", 74 => "00010001", 75 => "10111010", 
    76 => "11110001", 77 => "01000101", 78 => "00001100", 79 => "00001100", 
    80 => "11101000", 81 => "11000001", 82 => "00010011", 83 => "00111101");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

