-- ==============================================================
-- Generated by Vitis HLS v2025.1.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity lenet_hls_fc_f6_Pipeline_F6_Output_Loop_p_ZL10f6_weights_111_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 8; 
             AddressWidth     : integer := 7; 
             AddressRange    : integer := 84
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of lenet_hls_fc_f6_Pipeline_F6_Output_Loop_p_ZL10f6_weights_111_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "11110110", 1 => "11100111", 2 => "00011001", 3 => "00100001", 
    4 => "00000011", 5 => "00011001", 6 => "00001111", 7 => "10111001", 
    8 => "11110001", 9 => "00100000", 10 => "11100100", 11 => "11010000", 
    12 => "11010111", 13 => "00001111", 14 => "00000101", 15 => "00110000", 
    16 => "00001010", 17 => "00000111", 18 => "00011111", 19 => "00001011", 
    20 => "00101001", 21 => "11101110", 22 => "00100100", 23 => "01001101", 
    24 => "00001101", 25 => "11101110", 26 => "11000101", 27 => "00101101", 
    28 => "01001001", 29 => "10101001", 30 => "01010100", 31 => "11100011", 
    32 => "00010100", 33 => "11111001", 34 => "00010111", 35 => "00001100", 
    36 => "01000101", 37 => "11101010", 38 => "11110000", 39 => "00001111", 
    40 => "00001001", 41 => "11111111", 42 => "11111001", 43 => "00000111", 
    44 => "11110001", 45 => "00010011", 46 => "00000011", 47 => "00010100", 
    48 => "11100101", 49 => "10110100", 50 => "00010000", 51 => "11011001", 
    52 => "00101111", 53 => "11001010", 54 => "00011011", 55 => "00111100", 
    56 => "11011110", 57 => "00100001", 58 => "01000101", 59 => "00110111", 
    60 => "00100101", 61 => "00110011", 62 => "00100101", 63 => "11100111", 
    64 => "11000010", 65 => "00101110", 66 => "00011011", 67 => "00010111", 
    68 => "11001001", 69 => "10111010", 70 => "00001111", 71 => "11111100", 
    72 => "01000111", 73 => "00000110", 74 => "00100110", 75 => "00001000", 
    76 => "11101100", 77 => "00010010", 78 => "11111110", 79 => "11001100", 
    80 => "00110111", 81 => "00101111", 82 => "11000101", 83 => "00011110");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

