-- ==============================================================
-- Generated by Vitis HLS v2025.1.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity lenet_hls_fc_f6_Pipeline_F6_Output_Loop_p_ZL10f6_weights_65_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 8; 
             AddressWidth     : integer := 7; 
             AddressRange    : integer := 84
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of lenet_hls_fc_f6_Pipeline_F6_Output_Loop_p_ZL10f6_weights_65_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "11000001", 1 => "00100101", 2 => "00110110", 3 => "11110000", 
    4 => "00101111", 5 => "10110111", 6 => "11101101", 7 => "00100100", 
    8 => "11000110", 9 => "00100011", 10 => "00000000", 11 => "00010110", 
    12 => "00011101", 13 => "01001111", 14 => "00011111", 15 => "00100000", 
    16 => "00011010", 17 => "00001010", 18 => "00100010", 19 => "11110100", 
    20 => "00110001", 21 => "00100011", 22 => "00111100", 23 => "00011011", 
    24 => "11101011", 25 => "00001101", 26 => "11101000", 27 => "11010101", 
    28 => "11110111", 29 => "00000101", 30 => "00101001", 31 => "00001111", 
    32 => "00001100", 33 => "11101001", 34 => "11011010", 35 => "00101101", 
    36 => "00011101", 37 => "00010101", 38 => "00011001", 39 => "00101010", 
    40 => "00010000", 41 => "00001000", 42 => "11010110", 43 => "00101000", 
    44 => "00111111", 45 => "00011101", 46 => "00000111", 47 => "11011011", 
    48 => "11111101", 49 => "00010101", 50 => "00111011", 51 => "11000100", 
    52 => "00110000", 53 => "11011001", 54 => "00110001", 55 => "00110001", 
    56 => "00100100", 57 => "11100011", 58 => "01000000", 59 => "11100110", 
    60 => "11110101", 61 => "01001001", 62 => "00010011", 63 => "11011011", 
    64 => "00010001", 65 => "00001001", 66 => "00011001", 67 => "00110001", 
    68 => "00001100", 69 => "00010100", 70 => "11100111", 71 => "00001111", 
    72 => "00011100", 73 => "11100001", 74 => "00010110", 75 => "11111111", 
    76 => "00101110", 77 => "00100100", 78 => "01000100", 79 => "11111000", 
    80 => "00011011", 81 => "11001011", 82 => "11010110", 83 => "00010010");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

