-- ==============================================================
-- Generated by Vitis HLS v2025.1.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity lenet_hls_fc_f6_Pipeline_F6_Output_Loop_p_ZL10f6_weights_12_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 8; 
             AddressWidth     : integer := 7; 
             AddressRange    : integer := 84
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of lenet_hls_fc_f6_Pipeline_F6_Output_Loop_p_ZL10f6_weights_12_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00000000", 1 => "10010001", 2 => "01011001", 3 => "00000001", 
    4 => "11101000", 5 => "00100011", 6 => "00010011", 7 => "00011101", 
    8 => "11011111", 9 => "01001110", 10 => "10110010", 11 => "00011100", 
    12 => "10101110", 13 => "11100000", 14 => "11011001", 15 => "01101000", 
    16 => "11101110", 17 => "01011001", 18 => "01000101", 19 => "10111110", 
    20 => "11101110", 21 => "11101010", 22 => "01001100", 23 => "01100011", 
    24 => "11010101", 25 => "01011100", 26 => "11011100", 27 => "01010100", 
    28 => "00111011", 29 => "10110010", 30 => "01001001", 31 => "01010101", 
    32 => "11001000", 33 => "00010011", 34 => "00101010", 35 => "00101111", 
    36 => "00001100", 37 => "00001101", 38 => "10101010", 39 => "00111001", 
    40 => "00010111", 41 => "11110110", 42 => "11001101", 43 => "00011011", 
    44 => "00000010", 45 => "00100100", 46 => "01001010", 47 => "11010001", 
    48 => "00110100", 49 => "11010110", 50 => "10101110", 51 => "11001010", 
    52 => "11110000", 53 => "00100011", 54 => "10101100", 55 => "00110110", 
    56 => "00000010", 57 => "00111000", 58 => "01000111", 59 => "11011011", 
    60 => "11011011", 61 => "11110010", 62 => "01000101", 63 => "11101001", 
    64 => "00100001", 65 => "01010100", 66 => "11011010", 67 => "00011010", 
    68 => "11100011", 69 => "10111000", 70 => "11101110", 71 => "01101000", 
    72 => "11011000", 73 => "11001101", 74 => "10101101", 75 => "01000011", 
    76 => "11111110", 77 => "10111011", 78 => "00000100", 79 => "11011011", 
    80 => "00110011", 81 => "11000011", 82 => "00111000", 83 => "00010100");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

