-- ==============================================================
-- Generated by Vitis HLS v2025.1.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity lenet_hls_fc_f6_Pipeline_F6_Output_Loop_p_ZL10f6_weights_88_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 8; 
             AddressWidth     : integer := 7; 
             AddressRange    : integer := 84
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of lenet_hls_fc_f6_Pipeline_F6_Output_Loop_p_ZL10f6_weights_88_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "11001101", 1 => "00001100", 2 => "11111111", 3 => "00000110", 
    4 => "11010000", 5 => "00100010", 6 => "00000010", 7 => "00011110", 
    8 => "11110011", 9 => "11001001", 10 => "00010111", 11 => "00100001", 
    12 => "11101000", 13 => "00010000", 14 => "00110010", 15 => "11110000", 
    16 => "11111110", 17 => "00110010", 18 => "00001001", 19 => "11100000", 
    20 => "00001001", 21 => "11000100", 22 => "00101101", 23 => "11011110", 
    24 => "00100111", 25 => "11111010", 26 => "11101011", 27 => "11011000", 
    28 => "11010110", 29 => "00001111", 30 => "00101000", 31 => "00001000", 
    32 => "11100110", 33 => "00010100", 34 => "00100001", 35 => "11010111", 
    36 => "11111000", 37 => "11101101", 38 => "11111010", 39 => "00000011", 
    40 => "00100110", 41 => "01000011", 42 => "00001010", 43 => "11100000", 
    44 => "00111110", 45 => "00001001", 46 => "01001101", 47 => "11010111", 
    48 => "11100110", 49 => "00110100", 50 => "00100000", 51 => "11100010", 
    52 => "00111101", 53 => "00010011", 54 => "11010101", 55 => "00100010", 
    56 => "01010001", 57 => "00011010", 58 => "00101110", 59 => "11011001", 
    60 => "11100010", 61 => "00111000", 62 => "01000000", 63 => "11001011", 
    64 => "10110001", 65 => "00110011", 66 => "00001001", 67 => "11111010", 
    68 => "11010111", 69 => "00001010", 70 => "00111001", 71 => "01000000", 
    72 => "11011000", 73 => "11111110", 74 => "11111001", 75 => "11111100", 
    76 => "00011101", 77 => "00010010", 78 => "00101110", 79 => "11011111", 
    80 => "11111100", 81 => "00010000", 82 => "11101110", 83 => "10111010");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

