-- ==============================================================
-- Generated by Vitis HLS v2025.1.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity lenet_hls_fc_f6_Pipeline_F6_Output_Loop_p_ZL10f6_weights_23_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 8; 
             AddressWidth     : integer := 7; 
             AddressRange    : integer := 84
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of lenet_hls_fc_f6_Pipeline_F6_Output_Loop_p_ZL10f6_weights_23_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "11101101", 1 => "10101100", 2 => "11011000", 3 => "10111111", 
    4 => "01001101", 5 => "00011001", 6 => "00101101", 7 => "10101000", 
    8 => "11001110", 9 => "11010011", 10 => "00011001", 11 => "00101000", 
    12 => "00100001", 13 => "11100001", 14 => "10100011", 15 => "00010010", 
    16 => "00101101", 17 => "00110100", 18 => "11000001", 19 => "00110001", 
    20 => "00010001", 21 => "11111101", 22 => "11101111", 23 => "11100111", 
    24 => "00101110", 25 => "01011011", 26 => "00010101", 27 => "10101000", 
    28 => "11010001", 29 => "01010001", 30 => "11010110", 31 => "00111001", 
    32 => "11001011", 33 => "01111111", 34 => "11111100", 35 => "11101000", 
    36 => "01000110", 37 => "11111101", 38 => "00011111", 39 => "01010101", 
    40 => "00111010", 41 => "10111010", 42 => "11010100", 43 => "11111100", 
    44 => "01011001", 45 => "11101001", 46 => "11011101", 47 => "00001001", 
    48 => "10101000", 49 => "00011001", 50 => "10011111", 51 => "11001011", 
    52 => "00111010", 53 => "00010000", 54 => "10101010", 55 => "00000110", 
    56 => "00101000", 57 => "00100111", 58 => "11101000", 59 => "10100010", 
    60 => "00011111", 61 => "11000101", 62 => "00111110", 63 => "10100110", 
    64 => "01111000", 65 => "11111110", 66 => "10000000", 67 => "11110000", 
    68 => "00100010", 69 => "10011100", 70 => "11001010", 71 => "10100010", 
    72 => "00000001", 73 => "10010011", 74 => "00010000", 75 => "00111011", 
    76 => "00000011", 77 => "01000111", 78 => "01001110", 79 => "01011011", 
    80 => "00001100", 81 => "00101100", 82 => "11010000", 83 => "00100100");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

