-- ==============================================================
-- Generated by Vitis HLS v2025.1.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity lenet_hls_fc_f6_Pipeline_F6_Output_Loop_p_ZL10f6_weights_93_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 8; 
             AddressWidth     : integer := 7; 
             AddressRange    : integer := 84
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of lenet_hls_fc_f6_Pipeline_F6_Output_Loop_p_ZL10f6_weights_93_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "11010010", 1 => "00111110", 2 => "10001110", 3 => "00011110", 
    4 => "00110001", 5 => "11000110", 6 => "00101111", 7 => "01001100", 
    8 => "00001111", 9 => "00100110", 10 => "00111111", 11 => "11011010", 
    12 => "11100010", 13 => "00111101", 14 => "00001011", 15 => "00000001", 
    16 => "00011001", 17 => "11001011", 18 => "11110000", 19 => "00000111", 
    20 => "01001001", 21 => "00000101", 22 => "11001011", 23 => "11110101", 
    24 => "00010001", 25 => "11110111", 26 => "00001001", 27 => "00010000", 
    28 => "00011011", 29 => "00010110", 30 => "11001111", 31 => "11110011", 
    32 => "11101001", 33 => "11101100", 34 => "00000110", 35 => "00010011", 
    36 => "01000100", 37 => "11100111", 38 => "00111111", 39 => "00001101", 
    40 => "11110101", 41 => "01000101", 42 => "11110010", 43 => "00100011", 
    44 => "01000111", 45 => "00110011", 46 => "00000100", 47 => "11111001", 
    48 => "11001010", 49 => "00000010", 50 => "01010010", 51 => "00010000", 
    52 => "11001100", 53 => "00000101", 54 => "00000011", 55 => "00100111", 
    56 => "11010111", 57 => "10011011", 58 => "00110001", 59 => "00010011", 
    60 => "11110111", 61 => "00011100", 62 => "11101100", 63 => "00001001", 
    64 => "00110001", 65 => "11100001", 66 => "01001100", 67 => "00100001", 
    68 => "00010101", 69 => "00010001", 70 => "00000001", 71 => "00001000", 
    72 => "01001101", 73 => "00010011", 74 => "01000010", 75 => "00101111", 
    76 => "11111010", 77 => "00101011", 78 => "00011100", 79 => "00011001", 
    80 => "11001101", 81 => "00110111", 82 => "00001101", 83 => "00010111");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

