-- ==============================================================
-- Generated by Vitis HLS v2025.1.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity lenet_hls_fc_f6_Pipeline_F6_Output_Loop_p_ZL10f6_weights_5_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 8; 
             AddressWidth     : integer := 7; 
             AddressRange    : integer := 84
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of lenet_hls_fc_f6_Pipeline_F6_Output_Loop_p_ZL10f6_weights_5_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "11011100", 1 => "11101011", 2 => "01001111", 3 => "11111111", 
    4 => "00100010", 5 => "00010011", 6 => "11101011", 7 => "00010100", 
    8 => "11110101", 9 => "00001110", 10 => "00111110", 11 => "11100110", 
    12 => "00111000", 13 => "11111100", 14 => "01000000", 15 => "00101100", 
    16 => "11001011", 17 => "01001110", 18 => "10111111", 19 => "11101111", 
    20 => "00011000", 21 => "00101000", 22 => "01001011", 23 => "00101000", 
    24 => "11100011", 25 => "11110000", 26 => "11100010", 27 => "00011111", 
    28 => "01010010", 29 => "00010111", 30 => "01000001", 31 => "00100001", 
    32 => "11010010", 33 => "00000000", 34 => "00010011", 35 => "01000011", 
    36 => "01001110", 37 => "00011001", 38 => "10111100", 39 => "11001011", 
    40 => "00001010", 41 => "01000100", 42 => "00100010", 43 => "11011101", 
    44 => "00110000", 45 => "00001000", 46 => "00001100", 47 => "01100101", 
    48 => "00110110", 49 => "00011011", 50 => "11111100", 51 => "00011101", 
    52 => "00100101", 53 => "11001100", 54 => "00001111", 55 => "00101000", 
    56 => "01001000", 57 => "11101100", 58 => "11001100", 59 => "00110000", 
    60 => "00011000", 61 => "11101110", 62 => "11111011", 63 => "11110011", 
    64 => "00010100", 65 => "00001100", 66 => "11010100", 67 => "01000001", 
    68 => "11111000", 69 => "00011011", 70 => "11010101", 71 => "01001001", 
    72 => "01010011", 73 => "00100011", 74 => "11010100", 75 => "01011010", 
    76 => "11010111", 77 => "10101101", 78 => "10111100", 79 => "11111111", 
    80 => "11110111", 81 => "11111011", 82 => "00010001", 83 => "00010000");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

