-- ==============================================================
-- Generated by Vitis HLS v2025.1.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity lenet_hls_fc_f6_Pipeline_F6_Output_Loop_p_ZL10f6_weights_97_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 8; 
             AddressWidth     : integer := 7; 
             AddressRange    : integer := 84
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of lenet_hls_fc_f6_Pipeline_F6_Output_Loop_p_ZL10f6_weights_97_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00101001", 1 => "00100010", 2 => "00010100", 3 => "11100101", 
    4 => "00001010", 5 => "00011100", 6 => "00001000", 7 => "11111110", 
    8 => "11101111", 9 => "00101100", 10 => "11100111", 11 => "00111111", 
    12 => "11111011", 13 => "11101010", 14 => "00010110", 15 => "00001000", 
    16 => "11101101", 17 => "00110001", 18 => "00000000", 19 => "11010110", 
    20 => "00001100", 21 => "11101110", 22 => "00001111", 23 => "11000011", 
    24 => "00101100", 25 => "11011000", 26 => "00000100", 27 => "11110100", 
    28 => "00000000", 29 => "00110001", 30 => "11111010", 31 => "00001011", 
    32 => "11001011", 33 => "00110001", 34 => "11111000", 35 => "11101010", 
    36 => "11101101", 37 => "00100011", 38 => "11111000", 39 => "11000110", 
    40 => "11111101", 41 => "11010100", 42 => "11010101", 43 => "01000111", 
    44 => "11100100", 45 => "11100100", 46 => "01001000", 47 => "11111111", 
    48 => "11000110", 49 => "11001001", 50 => "00101111", 51 => "00100111", 
    52 => "01000100", 53 => "11111100", 54 => "00111000", 55 => "00000010", 
    56 => "00010010", 57 => "11010001", 58 => "00101111", 59 => "00010001", 
    60 => "11000101", 61 => "11100010", 62 => "11110010", 63 => "11011001", 
    64 => "11010001", 65 => "00010111", 66 => "11101000", 67 => "11110001", 
    68 => "00001100", 69 => "11101101", 70 => "11110010", 71 => "00000010", 
    72 => "00010100", 73 => "00010110", 74 => "00101111", 75 => "00100001", 
    76 => "11101000", 77 => "00101011", 78 => "11110100", 79 => "11011001", 
    80 => "00100000", 81 => "11010000", 82 => "11101111", 83 => "00110010");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

