-- ==============================================================
-- Generated by Vitis HLS v2025.1.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity lenet_hls_fc_f6_Pipeline_F6_Output_Loop_p_ZL10f6_weights_57_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 8; 
             AddressWidth     : integer := 7; 
             AddressRange    : integer := 84
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of lenet_hls_fc_f6_Pipeline_F6_Output_Loop_p_ZL10f6_weights_57_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "10111111", 1 => "11111001", 2 => "11101100", 3 => "11011111", 
    4 => "01001011", 5 => "11000101", 6 => "10011010", 7 => "00011010", 
    8 => "00100001", 9 => "11100100", 10 => "10110100", 11 => "00010000", 
    12 => "00110010", 13 => "00110001", 14 => "01001100", 15 => "00110101", 
    16 => "11101101", 17 => "01001100", 18 => "11110001", 19 => "10111101", 
    20 => "11001100", 21 => "10100000", 22 => "01011111", 23 => "00111110", 
    24 => "00000111", 25 => "00100110", 26 => "11010111", 27 => "10111001", 
    28 => "10111011", 29 => "00001100", 30 => "01111111", 31 => "11111100", 
    32 => "00110110", 33 => "00001111", 34 => "10110011", 35 => "10011101", 
    36 => "01000111", 37 => "01101110", 38 => "00010011", 39 => "01000011", 
    40 => "00110110", 41 => "00100101", 42 => "00100010", 43 => "00101100", 
    44 => "11010010", 45 => "00000111", 46 => "00010000", 47 => "11101000", 
    48 => "00010011", 49 => "00100110", 50 => "00010100", 51 => "00011110", 
    52 => "11111000", 53 => "11000001", 54 => "11111001", 55 => "11101101", 
    56 => "00000010", 57 => "11011011", 58 => "00101100", 59 => "11111111", 
    60 => "00100101", 61 => "00010000", 62 => "00011110", 63 => "11001100", 
    64 => "00101110", 65 => "00100011", 66 => "11110001", 67 => "11010010", 
    68 => "10011010", 69 => "00011100", 70 => "11111101", 71 => "01011010", 
    72 => "10110110", 73 => "11111110", 74 => "10111110", 75 => "11110001", 
    76 => "11111010", 77 => "00110010", 78 => "11110000", 79 => "00101100", 
    80 => "11101010", 81 => "00011110", 82 => "00000011", 83 => "00011100");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

