-- ==============================================================
-- Generated by Vitis HLS v2025.1.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity lenet_hls_fc_f6_Pipeline_F6_Output_Loop_p_ZL10f6_weights_115_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 8; 
             AddressWidth     : integer := 7; 
             AddressRange    : integer := 84
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of lenet_hls_fc_f6_Pipeline_F6_Output_Loop_p_ZL10f6_weights_115_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00010000", 1 => "11110010", 2 => "11110000", 3 => "00111011", 
    4 => "00010100", 5 => "11111010", 6 => "11111010", 7 => "00101110", 
    8 => "11101000", 9 => "00100011", 10 => "00001001", 11 => "11101101", 
    12 => "00000111", 13 => "00111111", 14 => "11110011", 15 => "10100110", 
    16 => "11100010", 17 => "11101111", 18 => "01010101", 19 => "11001110", 
    20 => "00110101", 21 => "11110001", 22 => "00110101", 23 => "10111101", 
    24 => "11111110", 25 => "00001100", 26 => "11100000", 27 => "11100011", 
    28 => "11111110", 29 => "00100100", 30 => "11011101", 31 => "00101000", 
    32 => "00001001", 33 => "00110110", 34 => "11001111", 35 => "11001110", 
    36 => "00000110", 37 => "00110111", 38 => "01001011", 39 => "11100110", 
    40 => "11011110", 41 => "00011010", 42 => "00011100", 43 => "11111011", 
    44 => "00011101", 45 => "11011100", 46 => "11011101", 47 => "11100100", 
    48 => "00100010", 49 => "00101010", 50 => "11111110", 51 => "11011001", 
    52 => "10100011", 53 => "11011101", 54 => "00010011", 55 => "10110011", 
    56 => "00110010", 57 => "11010000", 58 => "11001000", 59 => "00101010", 
    60 => "00111010", 61 => "11101111", 62 => "01001101", 63 => "00001100", 
    64 => "01001110", 65 => "01001000", 66 => "00111111", 67 => "10111110", 
    68 => "00110011", 69 => "01000111", 70 => "11000010", 71 => "00111110", 
    72 => "00110010", 73 => "11110111", 74 => "11111001", 75 => "00011011", 
    76 => "11001011", 77 => "01000101", 78 => "11100010", 79 => "00011110", 
    80 => "11111110", 81 => "00110010", 82 => "11111011", 83 => "00000110");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

